/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Statistics
{
    public class StatisticDataType : Message
    {
        public const string RosMessageName = "statistics_msgs/msg/StatisticDataType";

        // ############################################
        //  This file contains the commonly used constants for the statistics data type.
        // 
        //  The value 0 is reserved for unitialized statistic message data type.
        //  Range of values: [0, 255].
        //  Unallowed values: any value that is not specified in this file.
        // 
        // ############################################
        //  Constant for uninitialized
        public const byte STATISTICS_DATA_TYPE_UNINITIALIZED = 0;
        //  Allowed values
        public const byte STATISTICS_DATA_TYPE_AVERAGE = 1;
        public const byte STATISTICS_DATA_TYPE_MINIMUM = 2;
        public const byte STATISTICS_DATA_TYPE_MAXIMUM = 3;
        public const byte STATISTICS_DATA_TYPE_STDDEV = 4;
        public const byte STATISTICS_DATA_TYPE_SAMPLE_COUNT = 5;

        public StatisticDataType()
        {
        }
    }
}
#endif
