/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Rtcm
{
    public class Message : Message
    {
        public const string RosMessageName = "rtcm_msgs/msg/Message";

        //  A message representing a single RTCM message.
        public Header header { get; set; }
        public byte[] message { get; set; }

        public Message()
        {
            this.header = new Header();
            this.message = new byte[0];
        }

        public Message(Header header, byte[] message)
        {
            this.header = header;
            this.message = message;
        }
    }
}
#endif
