/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Nav2d
{
    public class Path2D : Message
    {
        public const string RosMessageName = "nav_2d_msgs/msg/Path2D";

        public Header header { get; set; }
        public Pose2D[] poses { get; set; }

        public Path2D()
        {
            this.header = new Header();
            this.poses = new Pose2D[0];
        }

        public Path2D(Header header, Pose2D[] poses)
        {
            this.header = header;
            this.poses = poses;
        }
    }
}
#endif
