/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Nav2d
{
    public class Pose2DStamped : Message
    {
        public const string RosMessageName = "nav_2d_msgs/msg/Pose2DStamped";

        public Header header { get; set; }
        public Pose2D pose { get; set; }

        public Pose2DStamped()
        {
            this.header = new Header();
            this.pose = new Pose2D();
        }

        public Pose2DStamped(Header header, Pose2D pose)
        {
            this.header = header;
            this.pose = pose;
        }
    }
}
#endif
