/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Nav2d
{
    public class Twist2D : Message
    {
        public const string RosMessageName = "nav_2d_msgs/msg/Twist2D";

        public double x { get; set; }
        public double y { get; set; }
        public double theta { get; set; }

        public Twist2D()
        {
            this.x = 0.0;
            this.y = 0.0;
            this.theta = 0.0;
        }

        public Twist2D(double x, double y, double theta)
        {
            this.x = x;
            this.y = y;
            this.theta = theta;
        }
    }
}
#endif
