/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Nav2d
{
    public class Twist2DStamped : Message
    {
        public const string RosMessageName = "nav_2d_msgs/msg/Twist2DStamped";

        public Header header { get; set; }
        public Twist2D velocity { get; set; }

        public Twist2DStamped()
        {
            this.header = new Header();
            this.velocity = new Twist2D();
        }

        public Twist2DStamped(Header header, Twist2D velocity)
        {
            this.header = header;
            this.velocity = velocity;
        }
    }
}
#endif
