/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Nav2d
{
    public class Twist2D32 : Message
    {
        public const string RosMessageName = "nav_2d_msgs/msg/Twist2D32";

        public float x { get; set; }
        public float y { get; set; }
        public float theta { get; set; }

        public Twist2D32()
        {
            this.x = 0.0f;
            this.y = 0.0f;
            this.theta = 0.0f;
        }

        public Twist2D32(float x, float y, float theta)
        {
            this.x = x;
            this.y = y;
            this.theta = theta;
        }
    }
}
#endif
