/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Sensor;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Rtabmap
{
    public class CameraModel : Message
    {
        public const string RosMessageName = "rtabmap_msgs/msg/CameraModel";

        public CameraInfo camera_info { get; set; }
        public Transform local_transform { get; set; }

        public CameraModel()
        {
            this.camera_info = new CameraInfo();
            this.local_transform = new Transform();
        }

        public CameraModel(CameraInfo camera_info, Transform local_transform)
        {
            this.camera_info = camera_info;
            this.local_transform = local_transform;
        }
    }
}
#endif
