/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Rtabmap
{
    public class CameraModels : Message
    {
        public const string RosMessageName = "rtabmap_msgs/msg/CameraModels";

        public CameraModel[] models { get; set; }

        public CameraModels()
        {
            this.models = new CameraModel[0];
        }

        public CameraModels(CameraModel[] models)
        {
            this.models = models;
        }
    }
}
#endif
