/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Rtabmap
{
    public class EnvSensor : Message
    {
        public const string RosMessageName = "rtabmap_msgs/msg/EnvSensor";

        public Header header { get; set; }
        //  EnvSensor
        public int type { get; set; }
        public double @value { get; set; }

        public EnvSensor()
        {
            this.header = new Header();
            this.type = 0;
            this.@value = 0.0;
        }

        public EnvSensor(Header header, int type, double @value)
        {
            this.header = header;
            this.type = type;
            this.@value = @value;
        }
    }
}
#endif
