/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Rtabmap
{
    public class GlobalDescriptor : Message
    {
        public const string RosMessageName = "rtabmap_msgs/msg/GlobalDescriptor";

        public Header header { get; set; }
        //  compressed global descriptor
        //  use rtabmap::util3d::uncompressData() from "rtabmap/core/util3d.h"
        public int type { get; set; }
        public byte[] info { get; set; }
        public byte[] data { get; set; }

        public GlobalDescriptor()
        {
            this.header = new Header();
            this.type = 0;
            this.info = new byte[0];
            this.data = new byte[0];
        }

        public GlobalDescriptor(Header header, int type, byte[] info, byte[] data)
        {
            this.header = header;
            this.type = type;
            this.info = info;
            this.data = data;
        }
    }
}
#endif
