/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Rtabmap
{
    public class Goal : Message
    {
        public const string RosMessageName = "rtabmap_msgs/msg/Goal";

        public Header header { get; set; }
        //  Set either node_id or node_label
        public int node_id { get; set; }
        public string node_label { get; set; }
        //  optional: if not set, the base frame of the robot is used
        public string frame_id { get; set; }

        public Goal()
        {
            this.header = new Header();
            this.node_id = 0;
            this.node_label = "";
            this.frame_id = "";
        }

        public Goal(Header header, int node_id, string node_label, string frame_id)
        {
            this.header = header;
            this.node_id = node_id;
            this.node_label = node_label;
            this.frame_id = frame_id;
        }
    }
}
#endif
