/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Rtabmap
{
    public class GPS : Message
    {
        public const string RosMessageName = "rtabmap_msgs/msg/GPS";

        public double stamp { get; set; }
        // in seconds
        public double longitude { get; set; }
        // DD format
        public double latitude { get; set; }
        // DD format
        public double altitude { get; set; }
        // in meters
        public double error { get; set; }
        // in meters
        public double bearing { get; set; }
        // North 0->360 deg

        public GPS()
        {
            this.stamp = 0.0;
            this.longitude = 0.0;
            this.latitude = 0.0;
            this.altitude = 0.0;
            this.error = 0.0;
            this.bearing = 0.0;
        }

        public GPS(double stamp, double longitude, double latitude, double altitude, double error, double bearing)
        {
            this.stamp = stamp;
            this.longitude = longitude;
            this.latitude = latitude;
            this.altitude = altitude;
            this.error = error;
            this.bearing = bearing;
        }
    }
}
#endif
