/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Rtabmap
{
    public class LandmarkDetections : Message
    {
        public const string RosMessageName = "rtabmap_msgs/msg/LandmarkDetections";

        //  header.stamp: the timestamp of the detection (e.g. image timestamp)
        //  header.frame_id: the base frame of pose (e.g., camera optical frame)
        public Header header { get; set; }
        public LandmarkDetection[] landmarks { get; set; }

        public LandmarkDetections()
        {
            this.header = new Header();
            this.landmarks = new LandmarkDetection[0];
        }

        public LandmarkDetections(Header header, LandmarkDetection[] landmarks)
        {
            this.header = header;
            this.landmarks = landmarks;
        }
    }
}
#endif
