/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Rtabmap
{
    public class Link : Message
    {
        public const string RosMessageName = "rtabmap_msgs/msg/Link";

        // class rtabmap::Link
        // {
        //    int from;
        //    int to;
        //    Type type;
        //    Transform transform;
        //    cv::Mat(6,6,CV_64FC1) information;
        // }
        public int from_id { get; set; }
        public int to_id { get; set; }
        public int type { get; set; }
        public Transform transform { get; set; }
        public double[] information { get; set; }

        public Link()
        {
            this.from_id = 0;
            this.to_id = 0;
            this.type = 0;
            this.transform = new Transform();
            this.information = new double[36];
        }

        public Link(int from_id, int to_id, int type, Transform transform, double[] information)
        {
            this.from_id = from_id;
            this.to_id = to_id;
            this.type = type;
            this.transform = transform;
            this.information = information;
        }
    }
}
#endif
