/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Rtabmap
{
    public class MapData : Message
    {
        public const string RosMessageName = "rtabmap_msgs/msg/MapData";

        public Header header { get; set; }
        // #################
        //  Optimized graph
        // #################
        public MapGraph graph { get; set; }
        // #################
        //  Graph data
        // #################
        public Node[] nodes { get; set; }

        public MapData()
        {
            this.header = new Header();
            this.graph = new MapGraph();
            this.nodes = new Node[0];
        }

        public MapData(Header header, MapGraph graph, Node[] nodes)
        {
            this.header = header;
            this.graph = graph;
            this.nodes = nodes;
        }
    }
}
#endif
