/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Rtabmap
{
    public class Node : Message
    {
        public const string RosMessageName = "rtabmap_msgs/msg/Node";

        // class rtabmap::Signature
        public int id { get; set; }
        public int map_id { get; set; }
        public int weight { get; set; }
        public double stamp { get; set; }
        public string label { get; set; }
        //  Pose from odometry not corrected
        public Pose pose { get; set; }
        //  std::multimap<wordId, index>
        //  std::vector<cv::Keypoint>
        //  std::vector<cv::Point3f>
        public int[] word_id_keys { get; set; }
        public int[] word_id_values { get; set; }
        public KeyPoint[] word_kpts { get; set; }
        public Point3f[] word_pts { get; set; }
        //  compressed descriptors
        //  use rtabmap::util3d::uncompressData() from "rtabmap/core/util3d.h"
        public byte[] word_descriptors { get; set; }
        public SensorData data { get; set; }

        public Node()
        {
            this.id = 0;
            this.map_id = 0;
            this.weight = 0;
            this.stamp = 0.0;
            this.label = "";
            this.pose = new Pose();
            this.word_id_keys = new int[0];
            this.word_id_values = new int[0];
            this.word_kpts = new KeyPoint[0];
            this.word_pts = new Point3f[0];
            this.word_descriptors = new byte[0];
            this.data = new SensorData();
        }

        public Node(int id, int map_id, int weight, double stamp, string label, Pose pose, int[] word_id_keys, int[] word_id_values, KeyPoint[] word_kpts, Point3f[] word_pts, byte[] word_descriptors, SensorData data)
        {
            this.id = id;
            this.map_id = map_id;
            this.weight = weight;
            this.stamp = stamp;
            this.label = label;
            this.pose = pose;
            this.word_id_keys = word_id_keys;
            this.word_id_values = word_id_values;
            this.word_kpts = word_kpts;
            this.word_pts = word_pts;
            this.word_descriptors = word_descriptors;
            this.data = data;
        }
    }
}
#endif
