/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Rtabmap
{
    public class Path : Message
    {
        public const string RosMessageName = "rtabmap_msgs/msg/Path";

        public Header header { get; set; }
        public int[] node_ids { get; set; }
        public Pose[] poses { get; set; }

        public Path()
        {
            this.header = new Header();
            this.node_ids = new int[0];
            this.poses = new Pose[0];
        }

        public Path(Header header, int[] node_ids, Pose[] poses)
        {
            this.header = header;
            this.node_ids = node_ids;
            this.poses = poses;
        }
    }
}
#endif
