/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Rtabmap
{
    public class Point3f : Message
    {
        public const string RosMessageName = "rtabmap_msgs/msg/Point3f";

        // class cv::Point3f
        // {
        //     float x;
        //     float y;
        //     float z;
        // }
        public float x { get; set; }
        public float y { get; set; }
        public float z { get; set; }

        public Point3f()
        {
            this.x = 0.0f;
            this.y = 0.0f;
            this.z = 0.0f;
        }

        public Point3f(float x, float y, float z)
        {
            this.x = x;
            this.y = y;
            this.z = z;
        }
    }
}
#endif
