/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Rtabmap
{
    public class RGBDImages : Message
    {
        public const string RosMessageName = "rtabmap_msgs/msg/RGBDImages";

        public Header header { get; set; }
        public RGBDImage[] rgbd_images { get; set; }

        public RGBDImages()
        {
            this.header = new Header();
            this.rgbd_images = new RGBDImage[0];
        }

        public RGBDImages(Header header, RGBDImage[] rgbd_images)
        {
            this.header = header;
            this.rgbd_images = rgbd_images;
        }
    }
}
#endif
