/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Sensor;

namespace RosSharp.RosBridgeClient.MessageTypes.Rtabmap
{
    public class ScanDescriptor : Message
    {
        public const string RosMessageName = "rtabmap_msgs/msg/ScanDescriptor";

        public Header header { get; set; }
        //  scan or scan_cloud is set
        public LaserScan scan { get; set; }
        public PointCloud2 scan_cloud { get; set; }
        public GlobalDescriptor global_descriptor { get; set; }

        public ScanDescriptor()
        {
            this.header = new Header();
            this.scan = new LaserScan();
            this.scan_cloud = new PointCloud2();
            this.global_descriptor = new GlobalDescriptor();
        }

        public ScanDescriptor(Header header, LaserScan scan, PointCloud2 scan_cloud, GlobalDescriptor global_descriptor)
        {
            this.header = header;
            this.scan = scan;
            this.scan_cloud = scan_cloud;
            this.global_descriptor = global_descriptor;
        }
    }
}
#endif
