/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Sensor;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Rtabmap
{
    public class SensorData : Message
    {
        public const string RosMessageName = "rtabmap_msgs/msg/SensorData";

        // class rtabmap::SensorData
        public Header header { get; set; }
        //  For RGB-D, left corresponds to rgb camera, and right corresponds to depth camera.
        //  Raw images
        public Image left { get; set; }
        public Image right { get; set; }
        //  Compressed images
        //  use rtabmap::util3d::uncompressImage() from "rtabmap/core/util3d.h"
        public byte[] left_compressed { get; set; }
        public byte[] right_compressed { get; set; }
        //  Camera info
        public CameraInfo[] left_camera_info { get; set; }
        public CameraInfo[] right_camera_info { get; set; }
        //  Transform from base frame to camera frame
        public Transform[] local_transform { get; set; }
        //  raw 2d or 3D laser scan
        public PointCloud2 laser_scan { get; set; }
        //  compressed 2D or 3D laser scan
        //  use rtabmap::util3d::uncompressData() from "rtabmap/core/util3d.h"
        public byte[] laser_scan_compressed { get; set; }
        public int laser_scan_max_pts { get; set; }
        public float laser_scan_max_range { get; set; }
        public int laser_scan_format { get; set; }
        //  local transform (base frame -> laser frame)
        public Transform laser_scan_local_transform { get; set; }
        //  compressed user data
        //  use rtabmap::util3d::uncompressData() from "rtabmap/core/util3d.h"
        public byte[] user_data { get; set; }
        //  compressed occupancy grid
        //  use rtabmap::util3d::uncompressData() from "rtabmap/core/util3d.h"
        public byte[] grid_ground { get; set; }
        public byte[] grid_obstacles { get; set; }
        public byte[] grid_empty_cells { get; set; }
        public float grid_cell_size { get; set; }
        public Point3f grid_view_point { get; set; }
        //  Local features
        public KeyPoint[] key_points { get; set; }
        public Point3f[] points { get; set; }
        //  compressed descriptors
        //  use rtabmap::util3d::uncompressData() from "rtabmap/core/util3d.h"
        public byte[] descriptors { get; set; }
        public GlobalDescriptor[] global_descriptors { get; set; }
        public EnvSensor[] env_sensors { get; set; }
        public Imu imu { get; set; }
        public Transform imu_local_transform { get; set; }
        public LandmarkDetection[] landmarks { get; set; }
        //  Ground truth
        public Pose ground_truth_pose { get; set; }
        //  GPS
        public GPS gps { get; set; }

        public SensorData()
        {
            this.header = new Header();
            this.left = new Image();
            this.right = new Image();
            this.left_compressed = new byte[0];
            this.right_compressed = new byte[0];
            this.left_camera_info = new CameraInfo[0];
            this.right_camera_info = new CameraInfo[0];
            this.local_transform = new Transform[0];
            this.laser_scan = new PointCloud2();
            this.laser_scan_compressed = new byte[0];
            this.laser_scan_max_pts = 0;
            this.laser_scan_max_range = 0.0f;
            this.laser_scan_format = 0;
            this.laser_scan_local_transform = new Transform();
            this.user_data = new byte[0];
            this.grid_ground = new byte[0];
            this.grid_obstacles = new byte[0];
            this.grid_empty_cells = new byte[0];
            this.grid_cell_size = 0.0f;
            this.grid_view_point = new Point3f();
            this.key_points = new KeyPoint[0];
            this.points = new Point3f[0];
            this.descriptors = new byte[0];
            this.global_descriptors = new GlobalDescriptor[0];
            this.env_sensors = new EnvSensor[0];
            this.imu = new Imu();
            this.imu_local_transform = new Transform();
            this.landmarks = new LandmarkDetection[0];
            this.ground_truth_pose = new Pose();
            this.gps = new GPS();
        }

        public SensorData(Header header, Image left, Image right, byte[] left_compressed, byte[] right_compressed, CameraInfo[] left_camera_info, CameraInfo[] right_camera_info, Transform[] local_transform, PointCloud2 laser_scan, byte[] laser_scan_compressed, int laser_scan_max_pts, float laser_scan_max_range, int laser_scan_format, Transform laser_scan_local_transform, byte[] user_data, byte[] grid_ground, byte[] grid_obstacles, byte[] grid_empty_cells, float grid_cell_size, Point3f grid_view_point, KeyPoint[] key_points, Point3f[] points, byte[] descriptors, GlobalDescriptor[] global_descriptors, EnvSensor[] env_sensors, Imu imu, Transform imu_local_transform, LandmarkDetection[] landmarks, Pose ground_truth_pose, GPS gps)
        {
            this.header = header;
            this.left = left;
            this.right = right;
            this.left_compressed = left_compressed;
            this.right_compressed = right_compressed;
            this.left_camera_info = left_camera_info;
            this.right_camera_info = right_camera_info;
            this.local_transform = local_transform;
            this.laser_scan = laser_scan;
            this.laser_scan_compressed = laser_scan_compressed;
            this.laser_scan_max_pts = laser_scan_max_pts;
            this.laser_scan_max_range = laser_scan_max_range;
            this.laser_scan_format = laser_scan_format;
            this.laser_scan_local_transform = laser_scan_local_transform;
            this.user_data = user_data;
            this.grid_ground = grid_ground;
            this.grid_obstacles = grid_obstacles;
            this.grid_empty_cells = grid_empty_cells;
            this.grid_cell_size = grid_cell_size;
            this.grid_view_point = grid_view_point;
            this.key_points = key_points;
            this.points = points;
            this.descriptors = descriptors;
            this.global_descriptors = global_descriptors;
            this.env_sensors = env_sensors;
            this.imu = imu;
            this.imu_local_transform = imu_local_transform;
            this.landmarks = landmarks;
            this.ground_truth_pose = ground_truth_pose;
            this.gps = gps;
        }
    }
}
#endif
