/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Rtabmap
{
    public class UserData : Message
    {
        public const string RosMessageName = "rtabmap_msgs/msg/UserData";

        public Header header { get; set; }
        //  OpenCV matrix containing the user data. A matrix of type CV_8UC1
        //  with 1 row is considered to be compressed (with rtabmap::compressData() method).
        //  If you have one dimension unsigned 8 bits uncompressed data, make sure to transpose it
        //  (to have multiple rows instead of multiple columns) in order to be detected as
        //  not compressed.
        public uint rows { get; set; }
        public uint cols { get; set; }
        public uint type { get; set; }
        public byte[] data { get; set; }

        public UserData()
        {
            this.header = new Header();
            this.rows = 0;
            this.cols = 0;
            this.type = 0;
            this.data = new byte[0];
        }

        public UserData(Header header, uint rows, uint cols, uint type, byte[] data)
        {
            this.header = header;
            this.rows = rows;
            this.cols = cols;
            this.type = type;
            this.data = data;
        }
    }
}
#endif
