/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.ArucoOpencv;

namespace RosSharp.RosBridgeClient.MessageTypes.ArucoOpencv
{
    public class ArucoDetection : Message
    {
        public const string RosMessageName = "aruco_opencv_msgs/msg/ArucoDetection";

        public Header header { get; set; }
        public MarkerPose[] markers { get; set; }
        public BoardPose[] boards { get; set; }

        public ArucoDetection()
        {
            this.header = new Header();
            this.markers = new MarkerPose[0];
            this.boards = new BoardPose[0];
        }

        public ArucoDetection(Header header, MarkerPose[] markers, BoardPose[] boards)
        {
            this.header = header;
            this.markers = markers;
            this.boards = boards;
        }
    }
}
#endif
