/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.ArucoOpencv
{
    public class BoardPose : Message
    {
        public const string RosMessageName = "aruco_opencv_msgs/msg/BoardPose";

        public string board_name { get; set; }
        public Pose pose { get; set; }

        public BoardPose()
        {
            this.board_name = "";
            this.pose = new Pose();
        }

        public BoardPose(string board_name, Pose pose)
        {
            this.board_name = board_name;
            this.pose = pose;
        }
    }
}
#endif
