/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces
{
    public class Altimeter : Message
    {
        public const string RosMessageName = "ros_gz_interfaces/msg/Altimeter";

        //  A message for Altimeter readings.
        //  Optional header data.
        public Header header { get; set; }
        //  Vertical position data, in meters.
        public double vertical_position { get; set; }
        //  Vertical velocity data, in meters/second.
        public double vertical_velocity { get; set; }
        //  Vertical reference.
        public double vertical_reference { get; set; }

        public Altimeter()
        {
            this.header = new Header();
            this.vertical_position = 0.0;
            this.vertical_velocity = 0.0;
            this.vertical_reference = 0.0;
        }

        public Altimeter(Header header, double vertical_position, double vertical_velocity, double vertical_reference)
        {
            this.header = header;
            this.vertical_position = vertical_position;
            this.vertical_velocity = vertical_velocity;
            this.vertical_reference = vertical_reference;
        }
    }
}
#endif
