/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces
{
    public class Contact : Message
    {
        public const string RosMessageName = "ros_gz_interfaces/msg/Contact";

        public Entity collision1 { get; set; }
        // Contact collision1
        public Entity collision2 { get; set; }
        // Contact collision2
        public Vector3[] positions { get; set; }
        // List of contact position
        public Vector3[] normals { get; set; }
        // List of contact normals
        public double[] depths { get; set; }
        // List of penetration depths
        public JointWrench[] wrenches { get; set; }
        // List of joint wrenches including forces/torques

        public Contact()
        {
            this.collision1 = new Entity();
            this.collision2 = new Entity();
            this.positions = new Vector3[0];
            this.normals = new Vector3[0];
            this.depths = new double[0];
            this.wrenches = new JointWrench[0];
        }

        public Contact(Entity collision1, Entity collision2, Vector3[] positions, Vector3[] normals, double[] depths, JointWrench[] wrenches)
        {
            this.collision1 = collision1;
            this.collision2 = collision2;
            this.positions = positions;
            this.normals = normals;
            this.depths = depths;
            this.wrenches = wrenches;
        }
    }
}
#endif
