/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces
{
    public class Contacts : Message
    {
        public const string RosMessageName = "ros_gz_interfaces/msg/Contacts";

        public Header header { get; set; }
        // Time stamp
        public Contact[] contacts { get; set; }
        // List of contacts

        public Contacts()
        {
            this.header = new Header();
            this.contacts = new Contact[0];
        }

        public Contacts(Header header, Contact[] contacts)
        {
            this.header = header;
            this.contacts = contacts;
        }
    }
}
#endif
