/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces
{
    public class Dataframe : Message
    {
        public const string RosMessageName = "ros_gz_interfaces/msg/Dataframe";

        //  Message containing some payload as well as sender and destination
        //  Intended for use with the comms system in Gazebo
        public Header header { get; set; }
        // Time stamp
        public string src_address { get; set; }
        // Address of the sender
        public string dst_address { get; set; }
        // Address of the destination
        public byte[] data { get; set; }
        // Payload
        public double rssi { get; set; }
        // Received Signal Strength Indicator

        public Dataframe()
        {
            this.header = new Header();
            this.src_address = "";
            this.dst_address = "";
            this.data = new byte[0];
            this.rssi = 0.0;
        }

        public Dataframe(Header header, string src_address, string dst_address, byte[] data, double rssi)
        {
            this.header = header;
            this.src_address = src_address;
            this.dst_address = dst_address;
            this.data = data;
            this.rssi = rssi;
        }
    }
}
#endif
