/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces
{
    public class EntityWrench : Message
    {
        public const string RosMessageName = "ros_gz_interfaces/msg/EntityWrench";

        public Header header { get; set; }
        // Time stamp
        public Entity entity { get; set; }
        // Entity
        public Wrench wrench { get; set; }
        // Wrench to be applied to entity

        public EntityWrench()
        {
            this.header = new Header();
            this.entity = new Entity();
            this.wrench = new Wrench();
        }

        public EntityWrench(Header header, Entity entity, Wrench wrench)
        {
            this.header = header;
            this.entity = entity;
            this.wrench = wrench;
        }
    }
}
#endif
