/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces
{
    public class Entity : Message
    {
        public const string RosMessageName = "ros_gz_interfaces/msg/Entity";

        //  Entity type: constant definition
        public const byte NONE = 0;
        public const byte LIGHT = 1;
        public const byte MODEL = 2;
        public const byte LINK = 3;
        public const byte VISUAL = 4;
        public const byte COLLISION = 5;
        public const byte SENSOR = 6;
        public const byte JOINT = 7;
        public ulong id { get; set; }
        // Entity unique identifier accross all types. Defaults to 0
        public string name { get; set; }
        // Entity name, which is not guaranteed to be unique.
        public byte type { get; set; }
        // Entity type.

        public Entity()
        {
            this.id = 0;
            this.name = "";
            this.type = 0;
        }

        public Entity(ulong id, string name, byte type)
        {
            this.id = id;
            this.name = name;
            this.type = type;
        }
    }
}
#endif
