/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces
{
    public class Float32Array : Message
    {
        public const string RosMessageName = "ros_gz_interfaces/msg/Float32Array";

        public float[] data { get; set; }

        public Float32Array()
        {
            this.data = new float[0];
        }

        public Float32Array(float[] data)
        {
            this.data = data;
        }
    }
}
#endif
