/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces
{
    public class GuiCamera : Message
    {
        public const string RosMessageName = "ros_gz_interfaces/msg/GuiCamera";

        //  Message for a GUI Camera.
        //  Optional header data.
        public Header header { get; set; }
        public string name { get; set; }
        public string view_controller { get; set; }
        public Pose pose { get; set; }
        public TrackVisual track { get; set; }
        //  Type of projection: "perspective" or "orthographic".
        public string projection_type { get; set; }

        public GuiCamera()
        {
            this.header = new Header();
            this.name = "";
            this.view_controller = "";
            this.pose = new Pose();
            this.track = new TrackVisual();
            this.projection_type = "";
        }

        public GuiCamera(Header header, string name, string view_controller, Pose pose, TrackVisual track, string projection_type)
        {
            this.header = header;
            this.name = name;
            this.view_controller = view_controller;
            this.pose = pose;
            this.track = track;
            this.projection_type = projection_type;
        }
    }
}
#endif
