/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces
{
    public class JointWrench : Message
    {
        public const string RosMessageName = "ros_gz_interfaces/msg/JointWrench";

        public Header header { get; set; }
        // Time stamp
        public String body_1_name { get; set; }
        // Body 1 name string
        public UInt32 body_1_id { get; set; }
        // Body 1 id
        public String body_2_name { get; set; }
        // Body 2 name string
        public UInt32 body_2_id { get; set; }
        // Body 2 id
        public Wrench body_1_wrench { get; set; }
        // Body 1 wrench
        public Wrench body_2_wrench { get; set; }
        // Body 2 wrench

        public JointWrench()
        {
            this.header = new Header();
            this.body_1_name = new String();
            this.body_1_id = new UInt32();
            this.body_2_name = new String();
            this.body_2_id = new UInt32();
            this.body_1_wrench = new Wrench();
            this.body_2_wrench = new Wrench();
        }

        public JointWrench(Header header, String body_1_name, UInt32 body_1_id, String body_2_name, UInt32 body_2_id, Wrench body_1_wrench, Wrench body_2_wrench)
        {
            this.header = header;
            this.body_1_name = body_1_name;
            this.body_1_id = body_1_id;
            this.body_2_name = body_2_name;
            this.body_2_id = body_2_id;
            this.body_1_wrench = body_1_wrench;
            this.body_2_wrench = body_2_wrench;
        }
    }
}
#endif
