/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces
{
    public class Light : Message
    {
        public const string RosMessageName = "ros_gz_interfaces/msg/Light";

        public Header header { get; set; }
        // Optional header data
        public string name { get; set; }
        // Light name
        //  Light type: constant definition
        public const byte POINT = 0;
        public const byte SPOT = 1;
        public const byte DIRECTIONAL = 2;
        public byte type { get; set; }
        // Light type (from constant definitions)
        public Pose pose { get; set; }
        // Light pose
        public ColorRGBA diffuse { get; set; }
        // Light diffuse emission
        public ColorRGBA specular { get; set; }
        // Light specular emission
        public float attenuation_constant { get; set; }
        // Constant variable in attenuation formula
        public float attenuation_linear { get; set; }
        // Linear variable in attenuation formula
        public float attenuation_quadratic { get; set; }
        // Quadratic variable in attenuation formula
        public Vector3 direction { get; set; }
        // Light direction
        public float range { get; set; }
        // Light range
        public bool cast_shadows { get; set; }
        // Enable/disable shadow casting
        public float spot_inner_angle { get; set; }
        // Spotlight inner cone angle
        public float spot_outer_angle { get; set; }
        // Spotlight outer cone angle
        public float spot_falloff { get; set; }
        // Falloff between inner and outer cone
        public uint id { get; set; }
        // Unique id of the light
        public uint parent_id { get; set; }
        // Unique id of the light's parent
        public float intensity { get; set; }
        // Light intensity

        public Light()
        {
            this.header = new Header();
            this.name = "";
            this.type = 0;
            this.pose = new Pose();
            this.diffuse = new ColorRGBA();
            this.specular = new ColorRGBA();
            this.attenuation_constant = 0.0f;
            this.attenuation_linear = 0.0f;
            this.attenuation_quadratic = 0.0f;
            this.direction = new Vector3();
            this.range = 0.0f;
            this.cast_shadows = false;
            this.spot_inner_angle = 0.0f;
            this.spot_outer_angle = 0.0f;
            this.spot_falloff = 0.0f;
            this.id = 0;
            this.parent_id = 0;
            this.intensity = 0.0f;
        }

        public Light(Header header, string name, byte type, Pose pose, ColorRGBA diffuse, ColorRGBA specular, float attenuation_constant, float attenuation_linear, float attenuation_quadratic, Vector3 direction, float range, bool cast_shadows, float spot_inner_angle, float spot_outer_angle, float spot_falloff, uint id, uint parent_id, float intensity)
        {
            this.header = header;
            this.name = name;
            this.type = type;
            this.pose = pose;
            this.diffuse = diffuse;
            this.specular = specular;
            this.attenuation_constant = attenuation_constant;
            this.attenuation_linear = attenuation_linear;
            this.attenuation_quadratic = attenuation_quadratic;
            this.direction = direction;
            this.range = range;
            this.cast_shadows = cast_shadows;
            this.spot_inner_angle = spot_inner_angle;
            this.spot_outer_angle = spot_outer_angle;
            this.spot_falloff = spot_falloff;
            this.id = id;
            this.parent_id = parent_id;
            this.intensity = intensity;
        }
    }
}
#endif
