/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces
{
    public class MaterialColor : Message
    {
        public const string RosMessageName = "ros_gz_interfaces/msg/MaterialColor";

        //  Entities that match to apply material color: constant definition
        public const byte FIRST = 0;
        public const byte ALL = 1;
        public Header header { get; set; }
        // Optional header data
        public Entity entity { get; set; }
        // Entity to change material color
        public ColorRGBA ambient { get; set; }
        // Ambient color
        public ColorRGBA diffuse { get; set; }
        // Diffuse color
        public ColorRGBA specular { get; set; }
        // Specular color
        public ColorRGBA emissive { get; set; }
        // Emissive color
        public double shininess { get; set; }
        // Specular exponent
        public byte entity_match { get; set; }
        // Entities that match to apply material color

        public MaterialColor()
        {
            this.header = new Header();
            this.entity = new Entity();
            this.ambient = new ColorRGBA();
            this.diffuse = new ColorRGBA();
            this.specular = new ColorRGBA();
            this.emissive = new ColorRGBA();
            this.shininess = 0.0;
            this.entity_match = 0;
        }

        public MaterialColor(Header header, Entity entity, ColorRGBA ambient, ColorRGBA diffuse, ColorRGBA specular, ColorRGBA emissive, double shininess, byte entity_match)
        {
            this.header = header;
            this.entity = entity;
            this.ambient = ambient;
            this.diffuse = diffuse;
            this.specular = specular;
            this.emissive = emissive;
            this.shininess = shininess;
            this.entity_match = entity_match;
        }
    }
}
#endif
