/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.RclInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces
{
    public class ParamVec : Message
    {
        public const string RosMessageName = "ros_gz_interfaces/msg/ParamVec";

        //  A message for a vector of parameters data.
        //  Optional header data.
        public Header header { get; set; }
        //  A set of name, value pairs
        public Parameter[] @params { get; set; }

        public ParamVec()
        {
            this.header = new Header();
            this.@params = new Parameter[0];
        }

        public ParamVec(Header header, Parameter[] @params)
        {
            this.header = header;
            this.@params = @params;
        }
    }
}
#endif
