/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces
{
    public class SensorNoise : Message
    {
        public const string RosMessageName = "ros_gz_interfaces/msg/SensorNoise";

        //  A message for specifying sensor noise.
        //  Noise type
        public const byte NONE = 0;
        public const byte GAUSSIAN = 2;
        public const byte GAUSSIAN_QUANTIZED = 3;
        //  Optional header data.
        public Header header { get; set; }
        //  The type of noise
        public byte type { get; set; }
        //  Noise mean
        //  Used by GAUSSIAN and GAUSSIAN_QUANTIZED
        public double mean { get; set; }
        //  Noise standard deviation
        //  Used by GAUSSIAN and GAUSSIAN_QUANTIZED
        public double stddev { get; set; }
        //  Noise mean bias
        //  Used by GAUSSIAN and GAUSSIAN_QUANTIZED
        public double bias_mean { get; set; }
        //  Noise standard deviation bias
        public double bias_stddev { get; set; }
        //  Noise precision
        //  Used by GAUSSIAN_QUANTIZED
        public double precision { get; set; }
        //  For type "gaussian*", the standard deviation of the noise used to
        //  drive a process to model slow variations in a sensor bias.
        public double dynamic_bias_stddev { get; set; }
        //  For type "gaussian*", the correlation time in seconds of the
        //  noise used to drive a process to model slow variations in a sensor bias.
        //  A typical value, when used, would be on the order of
        //  3600 seconds (1 hour).
        public double dynamic_bias_correlation_time { get; set; }

        public SensorNoise()
        {
            this.header = new Header();
            this.type = 0;
            this.mean = 0.0;
            this.stddev = 0.0;
            this.bias_mean = 0.0;
            this.bias_stddev = 0.0;
            this.precision = 0.0;
            this.dynamic_bias_stddev = 0.0;
            this.dynamic_bias_correlation_time = 0.0;
        }

        public SensorNoise(Header header, byte type, double mean, double stddev, double bias_mean, double bias_stddev, double precision, double dynamic_bias_stddev, double dynamic_bias_correlation_time)
        {
            this.header = header;
            this.type = type;
            this.mean = mean;
            this.stddev = stddev;
            this.bias_mean = bias_mean;
            this.bias_stddev = bias_stddev;
            this.precision = precision;
            this.dynamic_bias_stddev = dynamic_bias_stddev;
            this.dynamic_bias_correlation_time = dynamic_bias_correlation_time;
        }
    }
}
#endif
