/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces
{
    public class StringVec : Message
    {
        public const string RosMessageName = "ros_gz_interfaces/msg/StringVec";

        //  A message for a vector of string data.
        //  Optional header data.
        public Header header { get; set; }
        //  The vector of strings.
        public string[] data { get; set; }

        public StringVec()
        {
            this.header = new Header();
            this.data = new string[0];
        }

        public StringVec(Header header, string[] data)
        {
            this.header = header;
            this.data = data;
        }
    }
}
#endif
