/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces
{
    public class VideoRecord : Message
    {
        public const string RosMessageName = "ros_gz_interfaces/msg/VideoRecord";

        //  A message that allows for control of video recording functions.
        //  Optional header data.
        public Header header { get; set; }
        //  True to start video recording.
        public bool start { get; set; }
        //  True to stop video recording.
        public bool stop { get; set; }
        //  Video encoding format, e.g. "mp4", "ogv".
        public string format { get; set; }
        //  filename of the recorded video.
        public string save_filename { get; set; }

        public VideoRecord()
        {
            this.header = new Header();
            this.start = false;
            this.stop = false;
            this.format = "";
            this.save_filename = "";
        }

        public VideoRecord(Header header, bool start, bool stop, string format, string save_filename)
        {
            this.header = header;
            this.start = start;
            this.stop = stop;
            this.format = format;
            this.save_filename = save_filename;
        }
    }
}
#endif
