/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces;
using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces
{
    public class WorldControl : Message
    {
        public const string RosMessageName = "ros_gz_interfaces/msg/WorldControl";

        public bool pause { get; set; }
        // Paused state.
        public bool step { get; set; }
        public uint multi_step = 0;
        // Paused after stepping multi_step.
        public WorldReset reset { get; set; }
        public uint seed { get; set; }
        public Time run_to_sim_time { get; set; }
        // A simulation time in the future to run to and
        //  then pause.

        public WorldControl()
        {
            this.pause = false;
            this.step = false;
            this.reset = new WorldReset();
            this.seed = 0;
            this.run_to_sim_time = new Time();
        }

        public WorldControl(bool pause, bool step, uint multi_step, WorldReset reset, uint seed, Time run_to_sim_time)
        {
            this.pause = pause;
            this.step = step;
            this.multi_step = multi_step;
            this.reset = reset;
            this.seed = seed;
            this.run_to_sim_time = run_to_sim_time;
        }
    }
}
#endif
