/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.RosGzInterfaces
{
    public class WorldReset : Message
    {
        public const string RosMessageName = "ros_gz_interfaces/msg/WorldReset";

        public bool all = false;
        // Reset time and model
        public bool time_only = false;
        // Reset time only
        public bool model_only = false;
        // Reset model only

        public WorldReset()
        {
        }

        public WorldReset(bool all, bool time_only, bool model_only)
        {
            this.all = all;
            this.time_only = time_only;
            this.model_only = model_only;
        }
    }
}
#endif
