/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Diagnostic
{
    public class DiagnosticStatus : Message
    {
        public const string RosMessageName = "diagnostic_msgs/msg/DiagnosticStatus";

        //  This message holds the status of an individual component of the robot.
        //  Possible levels of operations.
        public const sbyte OK = 0;
        public const sbyte WARN = 1;
        public const sbyte ERROR = 2;
        public const sbyte STALE = 3;
        //  Level of operation enumerated above.
        public sbyte level { get; set; }
        //  A description of the test/component reporting.
        public string name { get; set; }
        //  A description of the status.
        public string message { get; set; }
        //  A hardware unique string.
        public string hardware_id { get; set; }
        //  An array of values associated with the status.
        public KeyValue[] values { get; set; }

        public DiagnosticStatus()
        {
            this.level = 0;
            this.name = "";
            this.message = "";
            this.hardware_id = "";
            this.values = new KeyValue[0];
        }

        public DiagnosticStatus(sbyte level, string name, string message, string hardware_id, KeyValue[] values)
        {
            this.level = level;
            this.name = name;
            this.message = message;
            this.hardware_id = hardware_id;
            this.values = values;
        }
    }
}
#endif
