/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Pcl
{
    public class ModelCoefficients : Message
    {
        public const string RosMessageName = "pcl_msgs/msg/ModelCoefficients";

        public Header header { get; set; }
        public float[] values { get; set; }

        public ModelCoefficients()
        {
            this.header = new Header();
            this.values = new float[0];
        }

        public ModelCoefficients(Header header, float[] values)
        {
            this.header = header;
            this.values = values;
        }
    }
}
#endif
