/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Sensor;

namespace RosSharp.RosBridgeClient.MessageTypes.Pcl
{
    public class PolygonMesh : Message
    {
        public const string RosMessageName = "pcl_msgs/msg/PolygonMesh";

        //  Separate header for the polygonal surface
        public Header header { get; set; }
        //  Vertices of the mesh as a point cloud
        public PointCloud2 cloud { get; set; }
        //  List of polygons
        public Vertices[] polygons { get; set; }

        public PolygonMesh()
        {
            this.header = new Header();
            this.cloud = new PointCloud2();
            this.polygons = new Vertices[0];
        }

        public PolygonMesh(Header header, PointCloud2 cloud, Vertices[] polygons)
        {
            this.header = header;
            this.cloud = cloud;
            this.polygons = polygons;
        }
    }
}
#endif
