/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.BlcmdInterfaces
{
    public class BLCMDStatus : Message
    {
        public const string RosMessageName = "blcmd_interfaces/msg/BLCMDStatus";

        // Msg for the blcmd status
        // status's of the BLCMD
        // faults
        public bool gate_fault { get; set; }
        public bool stall_fault { get; set; }
        public bool resolver_fault { get; set; }
        public bool overspeed_fault { get; set; }
        // id of the BLCMD
        public sbyte id { get; set; }

        public BLCMDStatus()
        {
            this.gate_fault = false;
            this.stall_fault = false;
            this.resolver_fault = false;
            this.overspeed_fault = false;
            this.id = 0;
        }

        public BLCMDStatus(bool gate_fault, bool stall_fault, bool resolver_fault, bool overspeed_fault, sbyte id)
        {
            this.gate_fault = gate_fault;
            this.stall_fault = stall_fault;
            this.resolver_fault = resolver_fault;
            this.overspeed_fault = overspeed_fault;
            this.id = id;
        }
    }
}
#endif
