/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.BlcmdInterfaces
{
    public class BLCMDStatusArray : Message
    {
        public const string RosMessageName = "blcmd_interfaces/msg/BLCMDStatusArray";

        // Msg to hold multiple BLCMDStatus msgs
        public BLCMDStatus[] blcmds { get; set; }

        public BLCMDStatusArray()
        {
            this.blcmds = new BLCMDStatus[0];
        }

        public BLCMDStatusArray(BLCMDStatus[] blcmds)
        {
            this.blcmds = blcmds;
        }
    }
}
#endif
