/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.BlcmdInterfaces
{
    public class SingleTelemetry : Message
    {
        public const string RosMessageName = "blcmd_interfaces/msg/SingleTelemetry";

        // BLCMDTelemetry used to give telemetry from the blcmds
        //  The Bus Index of the CMD
        public string bus { get; set; }
        //  The CMD Index that is being used
        public sbyte id { get; set; }
        //  The rotor velocity in rad/s
        public double rotor_velocity { get; set; }
        //  The q_current in A
        public double q_current { get; set; }
        //  The rotor interval
        public double rotor_interval { get; set; }
        //  The D Current in A
        public double d_current { get; set; }
        //  The resolver position
        public double resolver_position { get; set; }
        //  The resolver velocity
        public double resolver_velocity { get; set; }
        //  The power in W
        public double power { get; set; }
        //  The voltage in V
        public double voltage { get; set; }
        //  The temperature in C
        public double temperature { get; set; }

        public SingleTelemetry()
        {
            this.bus = "";
            this.id = 0;
            this.rotor_velocity = 0.0;
            this.q_current = 0.0;
            this.rotor_interval = 0.0;
            this.d_current = 0.0;
            this.resolver_position = 0.0;
            this.resolver_velocity = 0.0;
            this.power = 0.0;
            this.voltage = 0.0;
            this.temperature = 0.0;
        }

        public SingleTelemetry(string bus, sbyte id, double rotor_velocity, double q_current, double rotor_interval, double d_current, double resolver_position, double resolver_velocity, double power, double voltage, double temperature)
        {
            this.bus = bus;
            this.id = id;
            this.rotor_velocity = rotor_velocity;
            this.q_current = q_current;
            this.rotor_interval = rotor_interval;
            this.d_current = d_current;
            this.resolver_position = resolver_position;
            this.resolver_velocity = resolver_velocity;
            this.power = power;
            this.voltage = voltage;
            this.temperature = temperature;
        }
    }
}
#endif
