/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.BlcmdInterfaces
{
    public class Telemetry : Message
    {
        public const string RosMessageName = "blcmd_interfaces/msg/Telemetry";

        //  Container to hold BLCMDS Telemetry for all BLCMDS
        //  CMDFeedback array for wheel motors
        public SingleTelemetry[] wheels { get; set; }
        //  CMDFeedback array for wheel pivot motors (relevant for new suspension)
        public SingleTelemetry[] pivots { get; set; }

        public Telemetry()
        {
            this.wheels = new SingleTelemetry[0];
            this.pivots = new SingleTelemetry[0];
        }

        public Telemetry(SingleTelemetry[] wheels, SingleTelemetry[] pivots)
        {
            this.wheels = wheels;
            this.pivots = pivots;
        }
    }
}
#endif
