/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Moveit
{
    public class PipelineState : Message
    {
        public const string RosMessageName = "moveit_msgs/msg/PipelineState";

        //  Motion plan response that is processed
        public MotionPlanRequest request { get; set; }
        //  Current solution
        public MotionPlanResponse response { get; set; }
        //  Latest stage of the planning pipeline that got invoked
        public string pipeline_stage { get; set; }

        public PipelineState()
        {
            this.request = new MotionPlanRequest();
            this.response = new MotionPlanResponse();
            this.pipeline_stage = "";
        }

        public PipelineState(MotionPlanRequest request, MotionPlanResponse response, string pipeline_stage)
        {
            this.request = request;
            this.response = response;
            this.pipeline_stage = pipeline_stage;
        }
    }
}
#endif
