/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Yolo;

namespace RosSharp.RosBridgeClient.MessageTypes.Yolo
{
    public class BoundingBox2D : Message
    {
        public const string RosMessageName = "yolo_msgs/msg/BoundingBox2D";

        //  2D position and orientation of the bounding box center
        public Pose2D center { get; set; }
        //  total size of the bounding box, in pixels, surrounding the object's center
        public Vector2 size { get; set; }

        public BoundingBox2D()
        {
            this.center = new Pose2D();
            this.size = new Vector2();
        }

        public BoundingBox2D(Pose2D center, Vector2 size)
        {
            this.center = center;
            this.size = size;
        }
    }
}
#endif
