/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Yolo
{
    public class BoundingBox3D : Message
    {
        public const string RosMessageName = "yolo_msgs/msg/BoundingBox3D";

        //  3D position and orientation of the bounding box center
        public Pose center { get; set; }
        //  total size of the bounding box, in meters, surrounding the object's center
        public Vector3 size { get; set; }
        //  frame reference
        public string frame_id { get; set; }

        public BoundingBox3D()
        {
            this.center = new Pose();
            this.size = new Vector3();
            this.frame_id = "";
        }

        public BoundingBox3D(Pose center, Vector3 size, string frame_id)
        {
            this.center = center;
            this.size = size;
            this.frame_id = frame_id;
        }
    }
}
#endif
