/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Yolo;

namespace RosSharp.RosBridgeClient.MessageTypes.Yolo
{
    public class Detection : Message
    {
        public const string RosMessageName = "yolo_msgs/msg/Detection";

        //  defines a YOLO detection result
        //  class probability
        public int class_id { get; set; }
        public string class_name { get; set; }
        public double score { get; set; }
        //  ID for tracking
        public string id { get; set; }
        //  2D bounding box surrounding the object in pixels
        public BoundingBox2D bbox { get; set; }
        //  3D bounding box surrounding the object in meters
        public BoundingBox3D bbox3d { get; set; }
        //  segmentation mask of the detected object
        //  it is only the boundary of the segmented object
        public Mask mask { get; set; }
        //  keypoints for human pose estimation
        public KeyPoint2DArray keypoints { get; set; }
        //  keypoints for human pose estimation
        public KeyPoint3DArray keypoints3d { get; set; }

        public Detection()
        {
            this.class_id = 0;
            this.class_name = "";
            this.score = 0.0;
            this.id = "";
            this.bbox = new BoundingBox2D();
            this.bbox3d = new BoundingBox3D();
            this.mask = new Mask();
            this.keypoints = new KeyPoint2DArray();
            this.keypoints3d = new KeyPoint3DArray();
        }

        public Detection(int class_id, string class_name, double score, string id, BoundingBox2D bbox, BoundingBox3D bbox3d, Mask mask, KeyPoint2DArray keypoints, KeyPoint3DArray keypoints3d)
        {
            this.class_id = class_id;
            this.class_name = class_name;
            this.score = score;
            this.id = id;
            this.bbox = bbox;
            this.bbox3d = bbox3d;
            this.mask = mask;
            this.keypoints = keypoints;
            this.keypoints3d = keypoints3d;
        }
    }
}
#endif
