/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Yolo;

namespace RosSharp.RosBridgeClient.MessageTypes.Yolo
{
    public class DetectionArray : Message
    {
        public const string RosMessageName = "yolo_msgs/msg/DetectionArray";

        //  represents all YOLO detections in one frame
        public Header header { get; set; }
        public Detection[] detections { get; set; }

        public DetectionArray()
        {
            this.header = new Header();
            this.detections = new Detection[0];
        }

        public DetectionArray(Header header, Detection[] detections)
        {
            this.header = header;
            this.detections = detections;
        }
    }
}
#endif
