/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Yolo
{
    public class KeyPoint3D : Message
    {
        public const string RosMessageName = "yolo_msgs/msg/KeyPoint3D";

        //  one keypoint for human pose estimation
        //  id of the keypoint
        public int id { get; set; }
        //  3D point in meters
        public Point point { get; set; }
        //  conf of the keypoint
        public double score { get; set; }

        public KeyPoint3D()
        {
            this.id = 0;
            this.point = new Point();
            this.score = 0.0;
        }

        public KeyPoint3D(int id, Point point, double score)
        {
            this.id = id;
            this.point = point;
            this.score = score;
        }
    }
}
#endif
