/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Yolo;

namespace RosSharp.RosBridgeClient.MessageTypes.Yolo
{
    public class KeyPoint2DArray : Message
    {
        public const string RosMessageName = "yolo_msgs/msg/KeyPoint2DArray";

        //  represents all the keypoints for human pose estimation
        public KeyPoint2D[] data { get; set; }

        public KeyPoint2DArray()
        {
            this.data = new KeyPoint2D[0];
        }

        public KeyPoint2DArray(KeyPoint2D[] data)
        {
            this.data = data;
        }
    }
}
#endif
