/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Yolo;

namespace RosSharp.RosBridgeClient.MessageTypes.Yolo
{
    public class Pose2D : Message
    {
        public const string RosMessageName = "yolo_msgs/msg/Pose2D";

        //  2D position in pixel coordinates
        public Point2D position { get; set; }
        public double theta { get; set; }

        public Pose2D()
        {
            this.position = new Point2D();
            this.theta = 0.0;
        }

        public Pose2D(Point2D position, double theta)
        {
            this.position = position;
            this.theta = theta;
        }
    }
}
#endif
