/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Ackermann
{
    public class AckermannDriveStamped : Message
    {
        public const string RosMessageName = "ackermann_msgs/msg/AckermannDriveStamped";

        // # Time stamped drive command for robots with Ackermann steering.
        //   $Id$
        public Header header { get; set; }
        public AckermannDrive drive { get; set; }

        public AckermannDriveStamped()
        {
            this.header = new Header();
            this.drive = new AckermannDrive();
        }

        public AckermannDriveStamped(Header header, AckermannDrive drive)
        {
            this.header = header;
            this.drive = drive;
        }
    }
}
#endif
