/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Gps
{
    public class GPSFix : Message
    {
        public const string RosMessageName = "gps_msgs/msg/GPSFix";

        //  A more complete GPS fix to supplement sensor_msgs/NavSatFix.
        public Header header { get; set; }
        public GPSStatus status { get; set; }
        //  Latitude (degrees). Positive is north of equator; negative is south.
        public double latitude { get; set; }
        //  Longitude (degrees). Positive is east of prime meridian, negative west.
        public double longitude { get; set; }
        //  Altitude (meters). Positive is above reference (e.g., sea level).
        public double altitude { get; set; }
        //  Direction (degrees from north)
        public double track { get; set; }
        //  Ground speed (meters/second)
        public double speed { get; set; }
        //  Vertical speed (meters/second)
        public double climb { get; set; }
        //  Device orientation (units in degrees)
        public double pitch { get; set; }
        public double roll { get; set; }
        public double dip { get; set; }
        //  GPS time
        public double time { get; set; }
        // # Dilution of precision; Xdop<=0 means the value is unknown
        //  Total (positional-temporal) dilution of precision
        public double gdop { get; set; }
        //  Positional (3D) dilution of precision
        public double pdop { get; set; }
        //  Horizontal dilution of precision
        public double hdop { get; set; }
        //  Vertical dilution of precision
        public double vdop { get; set; }
        //  Temporal dilution of precision
        public double tdop { get; set; }
        // # Uncertainty of measurement, 95% confidence
        //  Spherical position uncertainty (meters) [epe]
        public double err { get; set; }
        //  Horizontal position uncertainty (meters) [eph]
        public double err_horz { get; set; }
        //  Vertical position uncertainty (meters) [epv]
        public double err_vert { get; set; }
        //  Track uncertainty (degrees) [epd]
        public double err_track { get; set; }
        //  Ground speed uncertainty (meters/second) [eps]
        public double err_speed { get; set; }
        //  Vertical speed uncertainty (meters/second) [epc]
        public double err_climb { get; set; }
        //  Temporal uncertainty [ept]
        public double err_time { get; set; }
        //  Orientation uncertainty (degrees)
        public double err_pitch { get; set; }
        public double err_roll { get; set; }
        public double err_dip { get; set; }
        //  Position covariance [m^2] defined relative to a tangential plane
        //  through the reported position. The components are East, North, and
        //  Up (ENU), in row-major order.
        public double[] position_covariance { get; set; }
        public const byte COVARIANCE_TYPE_UNKNOWN = 0;
        public const byte COVARIANCE_TYPE_APPROXIMATED = 1;
        public const byte COVARIANCE_TYPE_DIAGONAL_KNOWN = 2;
        public const byte COVARIANCE_TYPE_KNOWN = 3;
        public byte position_covariance_type { get; set; }

        public GPSFix()
        {
            this.header = new Header();
            this.status = new GPSStatus();
            this.latitude = 0.0;
            this.longitude = 0.0;
            this.altitude = 0.0;
            this.track = 0.0;
            this.speed = 0.0;
            this.climb = 0.0;
            this.pitch = 0.0;
            this.roll = 0.0;
            this.dip = 0.0;
            this.time = 0.0;
            this.gdop = 0.0;
            this.pdop = 0.0;
            this.hdop = 0.0;
            this.vdop = 0.0;
            this.tdop = 0.0;
            this.err = 0.0;
            this.err_horz = 0.0;
            this.err_vert = 0.0;
            this.err_track = 0.0;
            this.err_speed = 0.0;
            this.err_climb = 0.0;
            this.err_time = 0.0;
            this.err_pitch = 0.0;
            this.err_roll = 0.0;
            this.err_dip = 0.0;
            this.position_covariance = new double[9];
            this.position_covariance_type = 0;
        }

        public GPSFix(Header header, GPSStatus status, double latitude, double longitude, double altitude, double track, double speed, double climb, double pitch, double roll, double dip, double time, double gdop, double pdop, double hdop, double vdop, double tdop, double err, double err_horz, double err_vert, double err_track, double err_speed, double err_climb, double err_time, double err_pitch, double err_roll, double err_dip, double[] position_covariance, byte position_covariance_type)
        {
            this.header = header;
            this.status = status;
            this.latitude = latitude;
            this.longitude = longitude;
            this.altitude = altitude;
            this.track = track;
            this.speed = speed;
            this.climb = climb;
            this.pitch = pitch;
            this.roll = roll;
            this.dip = dip;
            this.time = time;
            this.gdop = gdop;
            this.pdop = pdop;
            this.hdop = hdop;
            this.vdop = vdop;
            this.tdop = tdop;
            this.err = err;
            this.err_horz = err_horz;
            this.err_vert = err_vert;
            this.err_track = err_track;
            this.err_speed = err_speed;
            this.err_climb = err_climb;
            this.err_time = err_time;
            this.err_pitch = err_pitch;
            this.err_roll = err_roll;
            this.err_dip = err_dip;
            this.position_covariance = position_covariance;
            this.position_covariance_type = position_covariance_type;
        }
    }
}
#endif
