/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Gps
{
    public class GPSStatus : Message
    {
        public const string RosMessageName = "gps_msgs/msg/GPSStatus";

        public Header header { get; set; }
        //  Satellites used in solution
        public ushort satellites_used { get; set; }
        // Number of satellites
        public int[] satellite_used_prn { get; set; }
        // PRN identifiers
        //  Satellites visible
        public ushort satellites_visible { get; set; }
        public int[] satellite_visible_prn { get; set; }
        // PRN identifiers
        public int[] satellite_visible_z { get; set; }
        // Elevation of satellites
        public int[] satellite_visible_azimuth { get; set; }
        // Azimuth of satellites
        public int[] satellite_visible_snr { get; set; }
        // Signal-to-noise ratios (dB)
        //  Measurement status
        public const short STATUS_NO_FIX = -1;
        // Unable to fix position
        public const short STATUS_FIX = 0;
        // Normal fix
        public const short STATUS_SBAS_FIX = 1;
        // Fixed using a satellite-based augmentation system
        public const short STATUS_GBAS_FIX = 2;
        // or a ground-based augmentation system
        public const short STATUS_DGPS_FIX = 18;
        // Fixed with DGPS
        public const short STATUS_WAAS_FIX = 33;
        // Fixed with WAAS
        public short status { get; set; }
        public const ushort SOURCE_NONE = 0;
        // No information is available
        public const ushort SOURCE_GPS = 1;
        // Using standard GPS location [only valid for position_source]
        public const ushort SOURCE_POINTS = 2;
        // Motion/orientation fix is derived from successive points
        public const ushort SOURCE_DOPPLER = 4;
        // Motion is derived using the Doppler effect
        public const ushort SOURCE_ALTIMETER = 8;
        // Using an altimeter
        public const ushort SOURCE_MAGNETIC = 16;
        // Using magnetic sensors
        public const ushort SOURCE_GYRO = 32;
        // Using gyroscopes
        public const ushort SOURCE_ACCEL = 64;
        // Using accelerometers
        public ushort motion_source { get; set; }
        // Source for speed, climb and track
        public ushort orientation_source { get; set; }
        // Source for device orientation
        public ushort position_source { get; set; }
        // Source for position

        public GPSStatus()
        {
            this.header = new Header();
            this.satellites_used = 0;
            this.satellite_used_prn = new int[0];
            this.satellites_visible = 0;
            this.satellite_visible_prn = new int[0];
            this.satellite_visible_z = new int[0];
            this.satellite_visible_azimuth = new int[0];
            this.satellite_visible_snr = new int[0];
            this.status = 0;
            this.motion_source = 0;
            this.orientation_source = 0;
            this.position_source = 0;
        }

        public GPSStatus(Header header, ushort satellites_used, int[] satellite_used_prn, ushort satellites_visible, int[] satellite_visible_prn, int[] satellite_visible_z, int[] satellite_visible_azimuth, int[] satellite_visible_snr, short status, ushort motion_source, ushort orientation_source, ushort position_source)
        {
            this.header = header;
            this.satellites_used = satellites_used;
            this.satellite_used_prn = satellite_used_prn;
            this.satellites_visible = satellites_visible;
            this.satellite_visible_prn = satellite_visible_prn;
            this.satellite_visible_z = satellite_visible_z;
            this.satellite_visible_azimuth = satellite_visible_azimuth;
            this.satellite_visible_snr = satellite_visible_snr;
            this.status = status;
            this.motion_source = motion_source;
            this.orientation_source = orientation_source;
            this.position_source = position_source;
        }
    }
}
#endif
