/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Sensor;

namespace RosSharp.RosBridgeClient.MessageTypes.Map
{
    public class PointCloud2Update : Message
    {
        public const string RosMessageName = "map_msgs/msg/PointCloud2Update";

        public const uint ADD = 0;
        public const uint DELETE = 1;
        public Header header { get; set; }
        public uint type { get; set; }
        // type of update, one of ADD or DELETE
        public PointCloud2 points { get; set; }

        public PointCloud2Update()
        {
            this.header = new Header();
            this.type = 0;
            this.points = new PointCloud2();
        }

        public PointCloud2Update(Header header, uint type, PointCloud2 points)
        {
            this.header = header;
            this.type = type;
            this.points = points;
        }
    }
}
#endif
