/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.ArmInterfaces
{
    public class KeyboardPoints : Message
    {
        public const string RosMessageName = "arm_interfaces/msg/KeyboardPoints";

        //  Array of 8 values containing pixel points of keyboard corners:
        //  [x1,y1, x2,y2, x3,y3, x4,y4] (i'm lazy)
        public int[] points { get; set; }
        //  camera resolution
        public int width { get; set; }
        public int height { get; set; }

        public KeyboardPoints()
        {
            this.points = new int[0];
            this.width = 0;
            this.height = 0;
        }

        public KeyboardPoints(int[] points, int width, int height)
        {
            this.points = points;
            this.width = width;
            this.height = height;
        }
    }
}
#endif
