/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Visualization
{
    public class MeshFile : Message
    {
        public const string RosMessageName = "visualization_msgs/msg/MeshFile";

        //  Used to send raw mesh files.
        //  The filename is used for both debug purposes and to provide a file extension
        //  for whatever parser is used.
        public string filename { get; set; }
        //  This stores the raw text of the mesh file.
        public byte[] data { get; set; }

        public MeshFile()
        {
            this.filename = "";
            this.data = new byte[0];
        }

        public MeshFile(string filename, byte[] data)
        {
            this.filename = filename;
            this.data = data;
        }
    }
}
#endif
