/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Visualization
{
    public class UVCoordinate : Message
    {
        public const string RosMessageName = "visualization_msgs/msg/UVCoordinate";

        //  Location of the pixel as a ratio of the width of a 2D texture.
        //  Values should be in range: [0.0-1.0].
        public float u { get; set; }
        public float v { get; set; }

        public UVCoordinate()
        {
            this.u = 0.0f;
            this.v = 0.0f;
        }

        public UVCoordinate(float u, float v)
        {
            this.u = u;
            this.v = v;
        }
    }
}
#endif
