/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Geographic
{
    public class BoundingBox : Message
    {
        public const string RosMessageName = "geographic_msgs/msg/BoundingBox";

        //  Geographic map bounding box.
        // 
        //  The two GeoPoints denote diagonally opposite corners of the box.
        // 
        //  If min_pt.latitude is NaN, the bounding box is "global", matching
        //  any valid latitude, longitude and altitude.
        // 
        //  If min_pt.altitude is NaN, the bounding box is two-dimensional and
        //  matches any altitude within the specified latitude and longitude
        //  range.
        public GeoPoint min_pt { get; set; }
        // lowest and most Southwestern corner
        public GeoPoint max_pt { get; set; }
        // highest and most Northeastern corner

        public BoundingBox()
        {
            this.min_pt = new GeoPoint();
            this.max_pt = new GeoPoint();
        }

        public BoundingBox(GeoPoint min_pt, GeoPoint max_pt)
        {
            this.min_pt = min_pt;
            this.max_pt = max_pt;
        }
    }
}
#endif
