/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.UniqueIdentifier;

namespace RosSharp.RosBridgeClient.MessageTypes.Geographic
{
    public class GeographicMap : Message
    {
        public const string RosMessageName = "geographic_msgs/msg/GeographicMap";

        //  Geographic map for a specified region.
        public Header header { get; set; }
        // stamp specifies time
        //  frame_id (normally /map)
        public UUID id { get; set; }
        // identifier for this map
        public BoundingBox bounds { get; set; }
        // 2D bounding box containing map
        public WayPoint[] points { get; set; }
        // way-points
        public MapFeature[] features { get; set; }
        // map features
        public KeyValue[] props { get; set; }
        // map properties

        public GeographicMap()
        {
            this.header = new Header();
            this.id = new UUID();
            this.bounds = new BoundingBox();
            this.points = new WayPoint[0];
            this.features = new MapFeature[0];
            this.props = new KeyValue[0];
        }

        public GeographicMap(Header header, UUID id, BoundingBox bounds, WayPoint[] points, MapFeature[] features, KeyValue[] props)
        {
            this.header = header;
            this.id = id;
            this.bounds = bounds;
            this.points = points;
            this.features = features;
            this.props = props;
        }
    }
}
#endif
