/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geographic;

namespace RosSharp.RosBridgeClient.MessageTypes.Geographic
{
    public class GeoPointStamped : Message
    {
        public const string RosMessageName = "geographic_msgs/msg/GeoPointStamped";

        public Header header { get; set; }
        public GeoPoint position { get; set; }

        public GeoPointStamped()
        {
            this.header = new Header();
            this.position = new GeoPoint();
        }

        public GeoPointStamped(Header header, GeoPoint position)
        {
            this.header = header;
            this.position = position;
        }
    }
}
#endif
