/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Geographic
{
    public class GeoPoseWithCovariance : Message
    {
        public const string RosMessageName = "geographic_msgs/msg/GeoPoseWithCovariance";

        //  Geographic pose, using the WGS 84 reference ellipsoid.
        // 
        //  Orientation uses the East-North-Up (ENU) frame of reference.
        //  (But, what about singularities at the poles?)
        public GeoPose pose { get; set; }
        //  Row-major representation of the 6x6 covariance matrix
        //  The orientation parameters use a fixed-axis representation.
        //  In order, the parameters are:
        //  (Lat, Lon, Alt, rotation about E (East) axis, rotation about N (North) axis, rotation about U (Up) axis)
        public double[] covariance { get; set; }

        public GeoPoseWithCovariance()
        {
            this.pose = new GeoPose();
            this.covariance = new double[36];
        }

        public GeoPoseWithCovariance(GeoPose pose, double[] covariance)
        {
            this.pose = pose;
            this.covariance = covariance;
        }
    }
}
#endif
