/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geographic;

namespace RosSharp.RosBridgeClient.MessageTypes.Geographic
{
    public class GeoPoseStamped : Message
    {
        public const string RosMessageName = "geographic_msgs/msg/GeoPoseStamped";

        public Header header { get; set; }
        public GeoPose pose { get; set; }

        public GeoPoseStamped()
        {
            this.header = new Header();
            this.pose = new GeoPose();
        }

        public GeoPoseStamped(Header header, GeoPose pose)
        {
            this.header = header;
            this.pose = pose;
        }
    }
}
#endif
