/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Geographic
{
    public class GeoPose : Message
    {
        public const string RosMessageName = "geographic_msgs/msg/GeoPose";

        //  Geographic pose, using the WGS 84 reference ellipsoid.
        // 
        //  Orientation uses the East-North-Up (ENU) frame of reference.
        //  (But, what about singularities at the poles?)
        public GeoPoint position { get; set; }
        public Quaternion orientation { get; set; }

        public GeoPose()
        {
            this.position = new GeoPoint();
            this.orientation = new Quaternion();
        }

        public GeoPose(GeoPoint position, Quaternion orientation)
        {
            this.position = position;
            this.orientation = orientation;
        }
    }
}
#endif
