/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Geographic
{
    public class KeyValue : Message
    {
        public const string RosMessageName = "geographic_msgs/msg/KeyValue";

        //  Geographic map tag (key, value) pair
        // 
        //  This is equivalent to diagnostic_msgs/KeyValue, repeated here to
        //  avoid introducing a trivial stack dependency.
        public string key { get; set; }
        // tag label
        public string @value { get; set; }
        // corresponding value

        public KeyValue()
        {
            this.key = "";
            this.@value = "";
        }

        public KeyValue(string key, string @value)
        {
            this.key = key;
            this.@value = @value;
        }
    }
}
#endif
