/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.UniqueIdentifier;

namespace RosSharp.RosBridgeClient.MessageTypes.Geographic
{
    public class RouteSegment : Message
    {
        public const string RosMessageName = "geographic_msgs/msg/RouteSegment";

        //  Route network segment.
        // 
        //  This is one directed edge of a RouteNetwork graph. It represents a
        //  known path from one way point to another.  If the path is two-way,
        //  there will be another RouteSegment with "start" and "end" reversed.
        public UUID id { get; set; }
        // Unique identifier for this segment
        public UUID start { get; set; }
        // beginning way point of segment
        public UUID end { get; set; }
        // ending way point of segment
        public KeyValue[] props { get; set; }
        // segment properties

        public RouteSegment()
        {
            this.id = new UUID();
            this.start = new UUID();
            this.end = new UUID();
            this.props = new KeyValue[0];
        }

        public RouteSegment(UUID id, UUID start, UUID end, KeyValue[] props)
        {
            this.id = id;
            this.start = start;
            this.end = end;
            this.props = props;
        }
    }
}
#endif
