/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.UniqueIdentifier;

namespace RosSharp.RosBridgeClient.MessageTypes.Geographic
{
    public class RouteNetwork : Message
    {
        public const string RosMessageName = "geographic_msgs/msg/RouteNetwork";

        //  Geographic map route network.
        // 
        //  A directed graph of WayPoint nodes and RouteSegment edges.  This
        //  information is extracted from the more-detailed contents of a
        //  GeographicMap.  A RouteNetwork contains only the way points and
        //  route segments of interest for path planning.
        public Header header { get; set; }
        public UUID id { get; set; }
        // This route network identifier
        public BoundingBox bounds { get; set; }
        // 2D bounding box for network
        public WayPoint[] points { get; set; }
        // Way points in this network
        public RouteSegment[] segments { get; set; }
        // Directed edges of this network
        public KeyValue[] props { get; set; }
        // Network key/value properties

        public RouteNetwork()
        {
            this.header = new Header();
            this.id = new UUID();
            this.bounds = new BoundingBox();
            this.points = new WayPoint[0];
            this.segments = new RouteSegment[0];
            this.props = new KeyValue[0];
        }

        public RouteNetwork(Header header, UUID id, BoundingBox bounds, WayPoint[] points, RouteSegment[] segments, KeyValue[] props)
        {
            this.header = header;
            this.id = id;
            this.bounds = bounds;
            this.points = points;
            this.segments = segments;
            this.props = props;
        }
    }
}
#endif
