/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.UniqueIdentifier;

namespace RosSharp.RosBridgeClient.MessageTypes.Geographic
{
    public class RoutePath : Message
    {
        public const string RosMessageName = "geographic_msgs/msg/RoutePath";

        //  Path through a route network.
        // 
        //  A path is a sequence of RouteSegment edges.  This information is
        //  extracted from a RouteNetwork graph.  A RoutePath lists the route
        //  segments needed to reach some chosen goal.
        public Header header { get; set; }
        public UUID network { get; set; }
        // Route network containing this path
        public UUID[] segments { get; set; }
        // Sequence of RouteSegment IDs
        public KeyValue[] props { get; set; }
        // Key/value properties

        public RoutePath()
        {
            this.header = new Header();
            this.network = new UUID();
            this.segments = new UUID[0];
            this.props = new KeyValue[0];
        }

        public RoutePath(Header header, UUID network, UUID[] segments, KeyValue[] props)
        {
            this.header = header;
            this.network = network;
            this.segments = segments;
            this.props = props;
        }
    }
}
#endif
