/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Camera
{
    public class GetCameraStreamStatsRequest : Message
    {
        public const string RosMessageName = "camera_msgs/srv/GetCameraStreamStats";

        public string[] serials { get; set; }
        public byte indent { get; set; }

        public GetCameraStreamStatsRequest()
        {
            this.serials = new string[0];
            this.indent = 0;
        }

        public GetCameraStreamStatsRequest(string[] serials, byte indent)
        {
            this.serials = serials;
            this.indent = indent;
        }
    }
}
#endif
