/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Camera
{
    public class GetIPListResponse : Message
    {
        public const string RosMessageName = "camera_msgs/srv/GetIPList";

        public string[] ips { get; set; }

        public GetIPListResponse()
        {
            this.ips = new string[0];
        }

        public GetIPListResponse(string[] ips)
        {
            this.ips = ips;
        }
    }
}
#endif
