/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.Nav2
{
    public class BehaviorTreeStatusChange : Message
    {
        public const string RosMessageName = "nav2_msgs/msg/BehaviorTreeStatusChange";

        public Time timestamp { get; set; }
        // internal behavior tree event timestamp. Typically this is wall clock time
        public string node_name { get; set; }
        public ushort uid { get; set; }
        // unique ID for this node
        public string previous_status { get; set; }
        // IDLE, RUNNING, SUCCESS or FAILURE
        public string current_status { get; set; }
        // IDLE, RUNNING, SUCCESS or FAILURE

        public BehaviorTreeStatusChange()
        {
            this.timestamp = new Time();
            this.node_name = "";
            this.uid = 0;
            this.previous_status = "";
            this.current_status = "";
        }

        public BehaviorTreeStatusChange(Time timestamp, string node_name, ushort uid, string previous_status, string current_status)
        {
            this.timestamp = timestamp;
            this.node_name = node_name;
            this.uid = uid;
            this.previous_status = previous_status;
            this.current_status = current_status;
        }
    }
}
#endif
