/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.Nav2
{
    public class BehaviorTreeLog : Message
    {
        public const string RosMessageName = "nav2_msgs/msg/BehaviorTreeLog";

        public Time timestamp { get; set; }
        // ROS time that this log message was sent.
        public BehaviorTreeStatusChange[] event_log { get; set; }

        public BehaviorTreeLog()
        {
            this.timestamp = new Time();
            this.event_log = new BehaviorTreeStatusChange[0];
        }

        public BehaviorTreeLog(Time timestamp, BehaviorTreeStatusChange[] event_log)
        {
            this.timestamp = timestamp;
            this.event_log = event_log;
        }
    }
}
#endif
