/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Nav2
{
    public class CollisionMonitorState : Message
    {
        public const string RosMessageName = "nav2_msgs/msg/CollisionMonitorState";

        //  Action type for robot in Collision Monitor
        public const byte DO_NOTHING = 0;
        // No action
        public const byte STOP = 1;
        // Stop the robot
        public const byte SLOWDOWN = 2;
        // Slowdown in percentage from current operating speed
        public const byte APPROACH = 3;
        // Keep constant time interval before collision
        public const byte LIMIT = 4;
        // Sets a limit of velocities if pts in range
        public byte action_type { get; set; }
        //  Name of triggered polygon
        public string polygon_name { get; set; }

        public CollisionMonitorState()
        {
            this.action_type = 0;
            this.polygon_name = "";
        }

        public CollisionMonitorState(byte action_type, string polygon_name)
        {
            this.action_type = action_type;
            this.polygon_name = polygon_name;
        }
    }
}
#endif
