/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Nav2
{
    public class CostmapMetaData : Message
    {
        public const string RosMessageName = "nav2_msgs/msg/CostmapMetaData";

        //  This hold basic information about the characteristics of the Costmap
        //  The time at which the static map was loaded
        public Time map_load_time { get; set; }
        //  The time of the last update to costmap
        public Time update_time { get; set; }
        //  The corresponding layer name
        public string layer { get; set; }
        //  The map resolution [m/cell]
        public float resolution { get; set; }
        //  Number of cells in the horizontal direction
        public uint size_x { get; set; }
        //  Number of cells in the vertical direction
        public uint size_y { get; set; }
        //  The origin of the costmap [m, m, rad].
        //  This is the real-world pose of the cell (0,0) in the map.
        public Pose origin { get; set; }

        public CostmapMetaData()
        {
            this.map_load_time = new Time();
            this.update_time = new Time();
            this.layer = "";
            this.resolution = 0.0f;
            this.size_x = 0;
            this.size_y = 0;
            this.origin = new Pose();
        }

        public CostmapMetaData(Time map_load_time, Time update_time, string layer, float resolution, uint size_x, uint size_y, Pose origin)
        {
            this.map_load_time = map_load_time;
            this.update_time = update_time;
            this.layer = layer;
            this.resolution = resolution;
            this.size_x = size_x;
            this.size_y = size_y;
            this.origin = origin;
        }
    }
}
#endif
