/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Nav2
{
    public class Costmap : Message
    {
        public const string RosMessageName = "nav2_msgs/msg/Costmap";

        //  This represents a 2-D grid map, in which each cell has an associated cost
        public Header header { get; set; }
        //  MetaData for the map
        public CostmapMetaData metadata { get; set; }
        //  The cost data, in row-major order, starting with (0,0).
        public byte[] data { get; set; }

        public Costmap()
        {
            this.header = new Header();
            this.metadata = new CostmapMetaData();
            this.data = new byte[0];
        }

        public Costmap(Header header, CostmapMetaData metadata, byte[] data)
        {
            this.header = header;
            this.metadata = metadata;
            this.data = data;
        }
    }
}
#endif
