/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Nav2
{
    public class CostmapFilterInfo : Message
    {
        public const string RosMessageName = "nav2_msgs/msg/CostmapFilterInfo";

        public Header header { get; set; }
        //  Type of plugin used (keepout filter, speed limit in m/s, speed limit in percent, etc...)
        //  0: keepout/lanes filter
        //  1: speed limit filter in % of maximum speed
        //  2: speed limit filter in absolute values (m/s)
        public byte type { get; set; }
        //  Name of filter mask topic
        public string filter_mask_topic { get; set; }
        //  Multiplier base offset and multiplier coefficient for conversion of OccGrid.
        //  Used to convert OccupancyGrid data values to filter space values.
        //  data -> into some other number space:
        //  space = data * multiplier + base
        public float @base { get; set; }
        public float multiplier { get; set; }

        public CostmapFilterInfo()
        {
            this.header = new Header();
            this.type = 0;
            this.filter_mask_topic = "";
            this.@base = 0.0f;
            this.multiplier = 0.0f;
        }

        public CostmapFilterInfo(Header header, byte type, string filter_mask_topic, float @base, float multiplier)
        {
            this.header = header;
            this.type = type;
            this.filter_mask_topic = filter_mask_topic;
            this.@base = @base;
            this.multiplier = multiplier;
        }
    }
}
#endif
