/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Nav2
{
    public class CostmapUpdate : Message
    {
        public const string RosMessageName = "nav2_msgs/msg/CostmapUpdate";

        //  Update msg for Costmap containing the modified part of Costmap
        public Header header { get; set; }
        public uint x { get; set; }
        public uint y { get; set; }
        public uint size_x { get; set; }
        public uint size_y { get; set; }
        //  The cost data, in row-major order, starting with (x,y) from 0-255 in Costmap format rather than OccupancyGrid 0-100.
        public byte[] data { get; set; }

        public CostmapUpdate()
        {
            this.header = new Header();
            this.x = 0;
            this.y = 0;
            this.size_x = 0;
            this.size_y = 0;
            this.data = new byte[0];
        }

        public CostmapUpdate(Header header, uint x, uint y, uint size_x, uint size_y, byte[] data)
        {
            this.header = header;
            this.x = x;
            this.y = y;
            this.size_x = size_x;
            this.size_y = size_y;
            this.data = data;
        }
    }
}
#endif
