/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Nav2
{
    public class ParticleCloud : Message
    {
        public const string RosMessageName = "nav2_msgs/msg/ParticleCloud";

        //  This represents a particle cloud containing particle poses and weights
        public Header header { get; set; }
        //  Array of particles in the cloud
        public Particle[] particles { get; set; }

        public ParticleCloud()
        {
            this.header = new Header();
            this.particles = new Particle[0];
        }

        public ParticleCloud(Header header, Particle[] particles)
        {
            this.header = header;
            this.particles = particles;
        }
    }
}
#endif
