/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Nav2
{
    public class Particle : Message
    {
        public const string RosMessageName = "nav2_msgs/msg/Particle";

        //  This represents an individual particle with weight produced by a particle filter
        public Pose pose { get; set; }
        public double weight { get; set; }

        public Particle()
        {
            this.pose = new Pose();
            this.weight = 0.0;
        }

        public Particle(Pose pose, double weight)
        {
            this.pose = pose;
            this.weight = weight;
        }
    }
}
#endif
