/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Nav2
{
    public class SpeedLimit : Message
    {
        public const string RosMessageName = "nav2_msgs/msg/SpeedLimit";

        public Header header { get; set; }
        //  Setting speed limit in percentage if true or in absolute values in false case
        public bool percentage { get; set; }
        //  Maximum allowed speed (in percent of maximum robot speed or in m/s depending
        //  on "percentage" value). When no-limit it is set to 0.0
        public double speed_limit { get; set; }

        public SpeedLimit()
        {
            this.header = new Header();
            this.percentage = false;
            this.speed_limit = 0.0;
        }

        public SpeedLimit(Header header, bool percentage, double speed_limit)
        {
            this.header = header;
            this.percentage = percentage;
            this.speed_limit = speed_limit;
        }
    }
}
#endif
