/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Nav2
{
    public class VoxelGrid : Message
    {
        public const string RosMessageName = "nav2_msgs/msg/VoxelGrid";

        public Header header { get; set; }
        public uint[] data { get; set; }
        public Point32 origin { get; set; }
        public Vector3 resolutions { get; set; }
        public uint size_x { get; set; }
        public uint size_y { get; set; }
        public uint size_z { get; set; }

        public VoxelGrid()
        {
            this.header = new Header();
            this.data = new uint[0];
            this.origin = new Point32();
            this.resolutions = new Vector3();
            this.size_x = 0;
            this.size_y = 0;
            this.size_z = 0;
        }

        public VoxelGrid(Header header, uint[] data, Point32 origin, Vector3 resolutions, uint size_x, uint size_y, uint size_z)
        {
            this.header = header;
            this.data = data;
            this.origin = origin;
            this.resolutions = resolutions;
            this.size_x = size_x;
            this.size_y = size_y;
            this.size_z = size_z;
        }
    }
}
#endif
