/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Vision;

namespace RosSharp.RosBridgeClient.MessageTypes.Vision
{
    public class BoundingBox2DArray : Message
    {
        public const string RosMessageName = "vision_msgs/msg/BoundingBox2DArray";

        public Header header { get; set; }
        public BoundingBox2D[] boxes { get; set; }

        public BoundingBox2DArray()
        {
            this.header = new Header();
            this.boxes = new BoundingBox2D[0];
        }

        public BoundingBox2DArray(Header header, BoundingBox2D[] boxes)
        {
            this.header = header;
            this.boxes = boxes;
        }
    }
}
#endif
