/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Vision
{
    public class Classification : Message
    {
        public const string RosMessageName = "vision_msgs/msg/Classification";

        //  Defines a classification result.
        // 
        //  This result does not contain any position information. It is designed for
        //    classifiers, which simply provide class probabilities given an instance of
        //    source data (e.g., an image or a point cloud).
        public Header header { get; set; }
        //  A list of class probabilities. This list need not provide a probability for
        //    every possible class, just ones that are nonzero, or above some
        //    user-defined threshold.
        public ObjectHypothesis[] results { get; set; }
        //  Source data that generated this classification are not a part of the message.
        //  If you need to access them, use an exact or approximate time synchronizer in
        //  your code, as this message's header should match the header of the source
        //  data.

        public Classification()
        {
            this.header = new Header();
            this.results = new ObjectHypothesis[0];
        }

        public Classification(Header header, ObjectHypothesis[] results)
        {
            this.header = header;
            this.results = results;
        }
    }
}
#endif
