/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Vision
{
    public class Detection3D : Message
    {
        public const string RosMessageName = "vision_msgs/msg/Detection3D";

        //  Defines a 3D detection result.
        // 
        //  This extends a basic 3D classification by including the pose of the
        //  detected object.
        public Header header { get; set; }
        //  Class probabilities. Does not have to include hypotheses for all possible
        //    object ids, the scores for any ids not listed are assumed to be 0.
        public ObjectHypothesisWithPose[] results { get; set; }
        //  3D bounding box surrounding the object.
        public BoundingBox3D bbox { get; set; }
        //  ID used for consistency across multiple detection messages. Detections
        //  of the same object in different detection messages should have the same id.
        //  This field may be empty.
        public string id { get; set; }
        //  Source data that generated this classification are not a part of the message.
        //  If you need to access them, use an exact or approximate time synchronizer in
        //  your code, as this message's header should match the header of the source
        //  data.

        public Detection3D()
        {
            this.header = new Header();
            this.results = new ObjectHypothesisWithPose[0];
            this.bbox = new BoundingBox3D();
            this.id = "";
        }

        public Detection3D(Header header, ObjectHypothesisWithPose[] results, BoundingBox3D bbox, string id)
        {
            this.header = header;
            this.results = results;
            this.bbox = bbox;
            this.id = id;
        }
    }
}
#endif
