/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Vision
{
    public class Detection2D : Message
    {
        public const string RosMessageName = "vision_msgs/msg/Detection2D";

        //  Defines a 2D detection result.
        // 
        //  This is similar to a 2D classification, but includes position information,
        //    allowing a classification result for a specific crop or image point to
        //    to be located in the larger image.
        public Header header { get; set; }
        //  Class probabilities
        public ObjectHypothesisWithPose[] results { get; set; }
        //  2D bounding box surrounding the object.
        public BoundingBox2D bbox { get; set; }
        //  ID used for consistency across multiple detection messages. Detections
        //  of the same object in different detection messages should have the same id.
        //  This field may be empty.
        public string id { get; set; }
        //  Source data that generated this detection are not a part of the message.
        //  If you need to access them, use an exact or approximate time synchronizer in
        //  your code, as this message's header should match the header of the source
        //  data.

        public Detection2D()
        {
            this.header = new Header();
            this.results = new ObjectHypothesisWithPose[0];
            this.bbox = new BoundingBox2D();
            this.id = "";
        }

        public Detection2D(Header header, ObjectHypothesisWithPose[] results, BoundingBox2D bbox, string id)
        {
            this.header = header;
            this.results = results;
            this.bbox = bbox;
            this.id = id;
        }
    }
}
#endif
