/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Vision;

namespace RosSharp.RosBridgeClient.MessageTypes.Vision
{
    public class LabelInfo : Message
    {
        public const string RosMessageName = "vision_msgs/msg/LabelInfo";

        //  Provides meta-information about a visual pipeline.
        // 
        //  This message serves a similar purpose to sensor_msgs/CameraInfo, but instead
        //    of being tied to hardware, it represents information about a specific
        //    computer vision pipeline. This information stays constant (or relatively
        //    constant) over time, and so it is wasteful to send it with each individual
        //    result. By listening to these messages, subscribers will receive
        //    the context in which published vision messages are to be interpreted.
        //  Each vision pipeline should publish its LabelInfo messages to its own topic,
        //    in a manner similar to CameraInfo.
        //  This message is meant to allow converting data from vision pipelines that
        //    return id based classifications back to human readable string class names.
        //  Used for sequencing
        public Header header { get; set; }
        //  An array of uint16 keys and string values containing the association
        //    between class identifiers and their names. According to the amount
        //    of classes and the datatype used to store their ids internally, the
        //    maxiumum class id allowed (65535 for uint16 and 255 for uint8) belongs to
        //    the "UNLABELED" class.
        public VisionClass[] class_map { get; set; }
        //  The value between 0-1 used as confidence threshold for the inference.
        public float threshold { get; set; }

        public LabelInfo()
        {
            this.header = new Header();
            this.class_map = new VisionClass[0];
            this.threshold = 0.0f;
        }

        public LabelInfo(Header header, VisionClass[] class_map, float threshold)
        {
            this.header = header;
            this.class_map = class_map;
            this.threshold = threshold;
        }
    }
}
#endif
