/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Vision
{
    public class Point2D : Message
    {
        public const string RosMessageName = "vision_msgs/msg/Point2D";

        //  Represents a 2D point in pixel coordinates.
        //  XY matches the sensor_msgs/Image convention: X is positive right and Y is positive down.
        public double x { get; set; }
        public double y { get; set; }

        public Point2D()
        {
            this.x = 0.0;
            this.y = 0.0;
        }

        public Point2D(double x, double y)
        {
            this.x = x;
            this.y = y;
        }
    }
}
#endif
