/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Vision
{
    public class VisionClass : Message
    {
        public const string RosMessageName = "vision_msgs/msg/VisionClass";

        //  A key value pair that maps an integer class_id to a string class label
        //    in computer vision systems.
        //  The int value that identifies the class.
        //  Elements identified with 65535, the maximum uint16 value are assumed
        //    to belong to the "UNLABELED" class. For vision pipelines using less
        //    than 255 classes the "UNLABELED" is the maximum value in the uint8
        //    range.
        public ushort class_id { get; set; }
        //  The name of the class represented by the class_id
        public string class_name { get; set; }

        public VisionClass()
        {
            this.class_id = 0;
            this.class_name = "";
        }

        public VisionClass(ushort class_id, string class_name)
        {
            this.class_id = class_id;
            this.class_name = class_name;
        }
    }
}
#endif
