/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.CmdInterfaces
{
    public class CMDFeedback : Message
    {
        public const string RosMessageName = "cmd_interfaces/msg/CMDFeedback";

        //  An angular velocity measurement and other relevant CMD values
        //  paired with a time they werer read.
        //  Used for reporting true velocities, currents, temperaturs and powers
        //  back to the PID tuner, for display on the GUI, and for dead
        //  reckoning
        //  Header
        public Header header { get; set; }
        //  The Bus Index of the CMD
        public sbyte bus { get; set; }
        //  The CMD Index that is being used
        public sbyte id { get; set; }
        //  Angular velocity of motor in rad/s (optional)
        public double omega { get; set; }
        //  Linear velocity in m/s (optional, for wheels or linear actuators)
        public double vel { get; set; }
        //  PWM duty cycle [0, 1]
        public double duty_cycle { get; set; }
        //  Current draw in Amps
        public double current { get; set; }
        //  Encoder interval
        public short interval { get; set; }

        public CMDFeedback()
        {
            this.header = new Header();
            this.bus = 0;
            this.id = 0;
            this.omega = 0.0;
            this.vel = 0.0;
            this.duty_cycle = 0.0;
            this.current = 0.0;
            this.interval = 0;
        }

        public CMDFeedback(Header header, sbyte bus, sbyte id, double omega, double vel, double duty_cycle, double current, short interval)
        {
            this.header = header;
            this.bus = bus;
            this.id = id;
            this.omega = omega;
            this.vel = vel;
            this.duty_cycle = duty_cycle;
            this.current = current;
            this.interval = interval;
        }
    }
}
#endif
