/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Bond
{
    public class Status : Message
    {
        public const string RosMessageName = "bond/msg/Status";

        public Header header { get; set; }
        public string id { get; set; }
        // ID of the bond
        public string instance_id { get; set; }
        // Unique ID for an individual in a bond
        public bool active { get; set; }
        //  Including the timeouts for the bond makes it easier to debug mis-matches
        //  between the two sides.
        public float heartbeat_timeout { get; set; }
        public float heartbeat_period { get; set; }

        public Status()
        {
            this.header = new Header();
            this.id = "";
            this.instance_id = "";
            this.active = false;
            this.heartbeat_timeout = 0.0f;
            this.heartbeat_period = 0.0f;
        }

        public Status(Header header, string id, string instance_id, bool active, float heartbeat_timeout, float heartbeat_period)
        {
            this.header = header;
            this.id = id;
            this.instance_id = instance_id;
            this.active = active;
            this.heartbeat_timeout = heartbeat_timeout;
            this.heartbeat_period = heartbeat_period;
        }
    }
}
#endif
