/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.NovaInterfaces
{
    public class ActuatorLimit : Message
    {
        public const string RosMessageName = "nova_interfaces/msg/ActuatorLimit";

        //  Limit switch activated on actuator
        //  Limit switch values have changed.
        public bool top { get; set; }
        public bool bottom { get; set; }

        public ActuatorLimit()
        {
            this.top = false;
            this.bottom = false;
        }

        public ActuatorLimit(bool top, bool bottom)
        {
            this.top = top;
            this.bottom = bottom;
        }
    }
}
#endif
