/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.NovaInterfaces
{
    public class BMESensor : Message
    {
        public const string RosMessageName = "nova_interfaces/msg/BMESensor";

        public float temperature { get; set; }
        public float humidity { get; set; }
        public int pressure { get; set; }
        public int altitude { get; set; }

        public BMESensor()
        {
            this.temperature = 0.0f;
            this.humidity = 0.0f;
            this.pressure = 0;
            this.altitude = 0;
        }

        public BMESensor(float temperature, float humidity, int pressure, int altitude)
        {
            this.temperature = temperature;
            this.humidity = humidity;
            this.pressure = pressure;
            this.altitude = altitude;
        }
    }
}
#endif
