/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.NovaInterfaces
{
    public class DistanceData : Message
    {
        public const string RosMessageName = "nova_interfaces/msg/DistanceData";

        //  Distance sensor measurements on the science platform
        //  Whether or not the distance sensor is producing valid readings
        public bool valid { get; set; }
        //  The average distance to the ground [cm]
        public float distance { get; set; }

        public DistanceData()
        {
            this.valid = false;
            this.distance = 0.0f;
        }

        public DistanceData(bool valid, float distance)
        {
            this.valid = valid;
            this.distance = distance;
        }
    }
}
#endif
