/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.NovaInterfaces
{
    public class DriveInfo : Message
    {
        public const string RosMessageName = "nova_interfaces/msg/DriveInfo";

        //  This Drive is used with the new ROS2 Control Based Drive
        //  The Old Interfaces are still left in the drive package
        //  speed multiplier
        public float multiplier { get; set; }
        // bool for locked
        public bool locked { get; set; }
        // bool for autonomous_mode
        public bool autonomous_mode { get; set; }
        // bool for gamepad connected
        public bool connected { get; set; }
        // enum for drive mode
        public const sbyte PIVOT = 1;
        public const sbyte STRAFE = 2;
        public const sbyte TANK = 3;
        // current drive mode of the rover
        public sbyte drive_mode { get; set; }

        public DriveInfo()
        {
            this.multiplier = 0.0f;
            this.locked = false;
            this.autonomous_mode = false;
            this.connected = false;
            this.drive_mode = 0;
        }

        public DriveInfo(float multiplier, bool locked, bool autonomous_mode, bool connected, sbyte drive_mode)
        {
            this.multiplier = multiplier;
            this.locked = locked;
            this.autonomous_mode = autonomous_mode;
            this.connected = connected;
            this.drive_mode = drive_mode;
        }
    }
}
#endif
