/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.NovaInterfaces
{
    public class DriveInput : Message
    {
        public const string RosMessageName = "nova_interfaces/msg/DriveInput";

        //  This DriveInput is used with the new ROS2 Control Based Drive
        //  The Old Interfaces are still left in the drive package
        //  Use DriveInputStamped or TwistStamped for Drive
        //  The speed value specifies the wheel speed (as a percentage)
        //    to drive at, between -1 and 1. This is equivalent to % RPM.
        public double speed { get; set; }
        //  The radius value specifies the turning radius of the rover in m, positive is left
        //  negative is right.
        public double radius { get; set; }
        //  The direction of the turning radius, left -1, right 1
        public sbyte direction { get; set; }

        public DriveInput()
        {
            this.speed = 0.0;
            this.radius = 0.0;
            this.direction = 0;
        }

        public DriveInput(double speed, double radius, sbyte direction)
        {
            this.speed = speed;
            this.radius = radius;
            this.direction = direction;
        }
    }
}
#endif
