/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.NovaInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.NovaInterfaces
{
    public class DriveInputStamped : Message
    {
        public const string RosMessageName = "nova_interfaces/msg/DriveInputStamped";

        public Header header { get; set; }
        public DriveInput drive_input { get; set; }

        public DriveInputStamped()
        {
            this.header = new Header();
            this.drive_input = new DriveInput();
        }

        public DriveInputStamped(Header header, DriveInput drive_input)
        {
            this.header = header;
            this.drive_input = drive_input;
        }
    }
}
#endif
