/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.NovaInterfaces
{
    public class EMCData : Message
    {
        public const string RosMessageName = "nova_interfaces/msg/EMCData";

        //  Stores the values of the on-board EMC sensor
        //  for the URC payload.
        //  Temperature [C]:
        public float temperature { get; set; }
        //  Pressure [Pa]:
        public float pressure { get; set; }
        //  Humidity [%]:
        public float humidity { get; set; }
        //  Wind [m/s]:
        public float wind { get; set; }

        public EMCData()
        {
            this.temperature = 0.0f;
            this.pressure = 0.0f;
            this.humidity = 0.0f;
            this.wind = 0.0f;
        }

        public EMCData(float temperature, float pressure, float humidity, float wind)
        {
            this.temperature = temperature;
            this.pressure = pressure;
            this.humidity = humidity;
            this.wind = wind;
        }
    }
}
#endif
