/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.NovaInterfaces
{
    public class HydraprobeData : Message
    {
        public const string RosMessageName = "nova_interfaces/msg/HydraprobeData";

        //  Displays hydraprobe data
        // 
        //  Conductivity:
        //    [uS/cm]
        public float conductivity { get; set; }
        //  Moisture:
        //    [%]
        public float moisture { get; set; }
        //  Temperature:
        //    [C]
        public float temperature { get; set; }
        //  Dielectric constant:
        //    []
        public float dielectric { get; set; }

        public HydraprobeData()
        {
            this.conductivity = 0.0f;
            this.moisture = 0.0f;
            this.temperature = 0.0f;
            this.dielectric = 0.0f;
        }

        public HydraprobeData(float conductivity, float moisture, float temperature, float dielectric)
        {
            this.conductivity = conductivity;
            this.moisture = moisture;
            this.temperature = temperature;
            this.dielectric = dielectric;
        }
    }
}
#endif
