/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.NovaInterfaces
{
    public class KilnMassData : Message
    {
        public const string RosMessageName = "nova_interfaces/msg/KilnMassData";

        //  Displays kilns and bilns data.
        //  Kiln Id
        public sbyte id { get; set; }
        //  Kiln Mass [g]
        public float mass { get; set; }

        public KilnMassData()
        {
            this.id = 0;
            this.mass = 0.0f;
        }

        public KilnMassData(sbyte id, float mass)
        {
            this.id = id;
            this.mass = mass;
        }
    }
}
#endif
