/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.NovaInterfaces
{
    public class KilnTempData : Message
    {
        public const string RosMessageName = "nova_interfaces/msg/KilnTempData";

        //  Displays kilns and bilns data.
        //  ex. 4C2#0(1/2/3/4)4 hex digits unsigned.
        //  Kiln Id
        public sbyte id { get; set; }
        //  Kiln Temperature [C]
        public int resistance { get; set; }

        public KilnTempData()
        {
            this.id = 0;
            this.resistance = 0;
        }

        public KilnTempData(sbyte id, int resistance)
        {
            this.id = id;
            this.resistance = resistance;
        }
    }
}
#endif
