/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.NovaInterfaces
{
    public class KilnData : Message
    {
        public const string RosMessageName = "nova_interfaces/msg/KilnData";

        //  for sending kiln data (converted temperatures readings) and kiln status
        public short[] temp { get; set; }
        // array to allow for additional sensors if ever implemented
        public bool state { get; set; }

        public KilnData()
        {
            this.temp = new short[2];
            this.state = false;
        }

        public KilnData(short[] temp, bool state)
        {
            this.temp = temp;
            this.state = state;
        }
    }
}
#endif
