/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.NovaInterfaces
{
    public class MicroscopeServoInfo : Message
    {
        public const string RosMessageName = "nova_interfaces/msg/MicroscopeServoInfo";

        //  current real angle of microscope servo
        public sbyte angle { get; set; }

        public MicroscopeServoInfo()
        {
            this.angle = 0;
        }

        public MicroscopeServoInfo(sbyte angle)
        {
            this.angle = angle;
        }
    }
}
#endif
