/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.NovaInterfaces
{
    public class RamanSpectrum : Message
    {
        public const string RosMessageName = "nova_interfaces/msg/RamanSpectrum";

        //  For raman spectrum
        public bool isvalid { get; set; }
        public ushort[] spectrum { get; set; }

        public RamanSpectrum()
        {
            this.isvalid = false;
            this.spectrum = new ushort[0];
        }

        public RamanSpectrum(bool isvalid, ushort[] spectrum)
        {
            this.isvalid = isvalid;
            this.spectrum = spectrum;
        }
    }
}
#endif
