/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.NovaInterfaces
{
    public class RamanState : Message
    {
        public const string RosMessageName = "nova_interfaces/msg/RamanState";

        //  For raman mechanical state
        public bool green_laser_on { get; set; }
        public bool red_laser_on { get; set; }
        public float filter_selection { get; set; }
        public float stepper_value { get; set; }
        public float mirror_servo { get; set; }

        public RamanState()
        {
            this.green_laser_on = false;
            this.red_laser_on = false;
            this.filter_selection = 0.0f;
            this.stepper_value = 0.0f;
            this.mirror_servo = 0.0f;
        }

        public RamanState(bool green_laser_on, bool red_laser_on, float filter_selection, float stepper_value, float mirror_servo)
        {
            this.green_laser_on = green_laser_on;
            this.red_laser_on = red_laser_on;
            this.filter_selection = filter_selection;
            this.stepper_value = stepper_value;
            this.mirror_servo = mirror_servo;
        }
    }
}
#endif
