/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.NovaInterfaces
{
    public class RoverPoseGPS : Message
    {
        public const string RosMessageName = "nova_interfaces/msg/RoverPoseGPS";

        //  Stores information about the GPS and IMU data
        public Header header { get; set; }
        //  If the data is valid
        public bool valid { get; set; }
        //  Were we able to get an accurate heading fix?
        public bool heading_valid { get; set; }
        //  GPS data
        public double latitude { get; set; }
        public double longitude { get; set; }
        //  IMU angles
        public float pitch { get; set; }
        public float roll { get; set; }
        public float yaw { get; set; }

        public RoverPoseGPS()
        {
            this.header = new Header();
            this.valid = false;
            this.heading_valid = false;
            this.latitude = 0.0;
            this.longitude = 0.0;
            this.pitch = 0.0f;
            this.roll = 0.0f;
            this.yaw = 0.0f;
        }

        public RoverPoseGPS(Header header, bool valid, bool heading_valid, double latitude, double longitude, float pitch, float roll, float yaw)
        {
            this.header = header;
            this.valid = valid;
            this.heading_valid = heading_valid;
            this.latitude = latitude;
            this.longitude = longitude;
            this.pitch = pitch;
            this.roll = roll;
            this.yaw = yaw;
        }
    }
}
#endif
