/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.NovaInterfaces
{
    public class SpectrometerData : Message
    {
        public const string RosMessageName = "nova_interfaces/msg/SpectrometerData";

        //  This has the raw spectrometer data from the reader.
        //  It handles all the values from one particular cuvette.
        //  This defines if the data is valid or not
        public bool valid { get; set; }
        //  The current cuvette that has been read (1 - 20)
        public int cuvette { get; set; }
        //  The current scan of the cuvette (0 - 9)
        public int scan { get; set; }
        //  The current BCA data
        //  Should be 6 digits in the array
        public int[] bca { get; set; }
        //  The current FDA data
        public int[] fda { get; set; }

        public SpectrometerData()
        {
            this.valid = false;
            this.cuvette = 0;
            this.scan = 0;
            this.bca = new int[0];
            this.fda = new int[0];
        }

        public SpectrometerData(bool valid, int cuvette, int scan, int[] bca, int[] fda)
        {
            this.valid = valid;
            this.cuvette = cuvette;
            this.scan = scan;
            this.bca = bca;
            this.fda = fda;
        }
    }
}
#endif
