/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.NovaInterfaces
{
    public class Status : Message
    {
        public const string RosMessageName = "nova_interfaces/msg/Status";

        //  The current status of the rover autonomous stack
        public sbyte status { get; set; }
        //  enum for the current status
        public const sbyte IDLE = 0;
        public const sbyte TRAVERSING = 1;
        public const sbyte SEARCHING = 2;
        public const sbyte ARRIVED_SUCCESSFULLY = 3;
        public const sbyte ARRIVED_UNSUCCESSFULLY = 4;

        public Status()
        {
            this.status = 0;
        }

        public Status(sbyte status)
        {
            this.status = status;
        }
    }
}
#endif
