/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.NovaInterfaces
{
    public class UVVisSpecData : Message
    {
        public const string RosMessageName = "nova_interfaces/msg/UVVisSpecData";

        //  This has the raw spectrometer data from the camera.
        //  The current Luminance data
        public float[] luminance { get; set; }

        public UVVisSpecData()
        {
            this.luminance = new float[0];
        }

        public UVVisSpecData(float[] luminance)
        {
            this.luminance = luminance;
        }
    }
}
#endif
