/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class CorStatusInfo : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/CorStatusInfo";

        //  CorStatusInfo - Status information for UBX-RXM-COR
        //  Constants for protocol in statusInfo
        public const byte PROTOCOL_UNKNOWN = 0;
        public const byte PROTOCOL_RTCM3 = 1;
        public const byte PROTOCOL_SPARTN = 2;
        public const byte PROTOCOL_UBX_RXM_PMP = 29;
        public const byte PROTOCOL_UBX_RXM_QZSSL6 = 30;
        //  Constants for error status
        public const byte ERR_UNKNOWN = 0;
        public const byte ERR_ERROR_FREE = 1;
        public const byte ERR_ERRONEOUS = 2;
        //  Constants for message usage
        public const byte MSG_USED_UNKNOWN = 0;
        public const byte MSG_NOT_USED = 1;
        public const byte MSG_USED = 2;
        //  Constants for encryption and decryption status
        public const byte MSG_ENCRYPTION_UNKNOWN = 0;
        public const byte MSG_NOT_ENCRYPTED = 1;
        public const byte MSG_ENCRYPTED = 2;
        public const byte MSG_DECRYPTION_UNKNOWN = 0;
        public const byte MSG_NOT_DECRYPTED = 1;
        public const byte MSG_DECRYPTED = 2;
        //  Fields
        public byte protocol { get; set; }
        // Input correction data protocol (refer to constants)
        public byte err_status { get; set; }
        // Error status of the received correction message
        public byte msg_used { get; set; }
        // Status of receiver using the input message
        public ushort correction_id { get; set; }
        // Identifier for the correction stream (station ID)
        public bool msg_type_valid { get; set; }
        // Validity of the msgType field
        public bool msg_sub_type_valid { get; set; }
        // Validity of the msgSubType field
        public bool msg_input_handle { get; set; }
        // Input handling support of the input message
        public byte msg_encrypted { get; set; }
        // Encryption status of the input message
        public byte msg_decrypted { get; set; }
        // Decryption status of the input message

        public CorStatusInfo()
        {
            this.protocol = 0;
            this.err_status = 0;
            this.msg_used = 0;
            this.correction_id = 0;
            this.msg_type_valid = false;
            this.msg_sub_type_valid = false;
            this.msg_input_handle = false;
            this.msg_encrypted = 0;
            this.msg_decrypted = 0;
        }

        public CorStatusInfo(byte protocol, byte err_status, byte msg_used, ushort correction_id, bool msg_type_valid, bool msg_sub_type_valid, bool msg_input_handle, byte msg_encrypted, byte msg_decrypted)
        {
            this.protocol = protocol;
            this.err_status = err_status;
            this.msg_used = msg_used;
            this.correction_id = correction_id;
            this.msg_type_valid = msg_type_valid;
            this.msg_sub_type_valid = msg_sub_type_valid;
            this.msg_input_handle = msg_input_handle;
            this.msg_encrypted = msg_encrypted;
            this.msg_decrypted = msg_decrypted;
        }
    }
}
#endif
