/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class ESFMeasDataItem : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/ESFMeasDataItem";

        public uint data_field { get; set; }
        // data
        public byte data_type { get; set; }
        // refer to manual

        public ESFMeasDataItem()
        {
            this.data_field = 0;
            this.data_type = 0;
        }

        public ESFMeasDataItem(uint data_field, byte data_type)
        {
            this.data_field = data_field;
            this.data_type = data_type;
        }
    }
}
#endif
