/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class GpsFix : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/GpsFix";

        public const byte GPS_NO_FIX = 0;
        public const byte GPS_DEAD_RECKONING_ONLY = 1;
        public const byte GPS_FIX_2D = 2;
        public const byte GPS_FIX_3D = 3;
        public const byte GPS_PLUS_DEAD_RECKONING = 4;
        public const byte GPS_TIME_ONLY = 5;
        public byte fix_type { get; set; }
        // gps fix type

        public GpsFix()
        {
            this.fix_type = 0;
        }

        public GpsFix(byte fix_type)
        {
            this.fix_type = fix_type;
        }
    }
}
#endif
