/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class MapMatching : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/MapMatching";

        public const byte MAP_MATCHING_NONE = 0;
        public const byte MAP_MATCHING_VALID_NOT_USED = 1;
        public const byte MAP_MATCHING_VALID_AND_USED = 2;
        public const byte MAP_MATCHING_VALID_DEAD_RECKONING = 3;
        public byte status { get; set; }
        // map matching status

        public MapMatching()
        {
            this.status = 0;
        }

        public MapMatching(byte status)
        {
            this.status = status;
        }
    }
}
#endif
