/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class OrbEphInfo : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/OrbEphInfo";

        //  Bit field structure for eph
        public const byte EPH_USABILITY_UNKNOWN = 31;
        // The usability period is unknown
        public const byte EPH_USABILITY_OVER_450_MIN = 30;
        // The usability period is more than 450 minutes
        public const byte EPH_USABILITY_EXPIRED = 0;
        // Ephemeris can no longer be used
        public byte eph_usability { get; set; }
        // How long the receiver will be able to use the stored ephemeris data from now on.
        //  For 30 > n > 0, the usability period is between (n-1)*15 and n*15 minutes.
        public const byte EPH_SOURCE_NOT_AVAILABLE = 0;
        public const byte EPH_SOURCE_GNSS_TRANSMISSION = 1;
        public const byte EPH_SOURCE_EXTERNAL_AIDING = 2;
        public byte eph_source { get; set; }
        // Ephemeris source

        public OrbEphInfo()
        {
            this.eph_usability = 0;
            this.eph_source = 0;
        }

        public OrbEphInfo(byte eph_usability, byte eph_source)
        {
            this.eph_usability = eph_usability;
            this.eph_source = eph_source;
        }
    }
}
#endif
