/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class OrbSVFlag : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/OrbSVFlag";

        //  Bit field structure for svFlag
        public const byte HEALTH_UNKNOWN = 0;
        public const byte HEALTH_HEALTHY = 1;
        public const byte HEALTH_NOT_HEALTHY = 2;
        public byte health { get; set; }
        // SV health
        public const byte VISIBILITY_UNKNOWN = 0;
        public const byte VISIBILITY_BELOW_HORIZON = 1;
        public const byte VISIBILITY_ABOVE_HORIZON = 2;
        public const byte VISIBILITY_ABOVE_ELEVATION_MASK = 3;
        public byte visibility { get; set; }
        // SV visibility

        public OrbSVFlag()
        {
            this.health = 0;
            this.visibility = 0;
        }

        public OrbSVFlag(byte health, byte visibility)
        {
            this.health = health;
            this.visibility = visibility;
        }
    }
}
#endif
