/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class OtherOrbInfo : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/OtherOrbInfo";

        //  Bit field structure for otherOrb
        public const byte ANO_AOP_USABILITY_UNKNOWN = 31;
        // The usability period is unknown
        public const byte ANO_AOP_USABILITY_OVER_30_DAYS = 30;
        // The usability period is more than 30 days
        public const byte ANO_AOP_USABILITY_EXPIRED = 0;
        // Data can no longer be used
        public byte ano_aop_usability { get; set; }
        // How long the receiver will be able to use the orbit data from now on.
        //  For 30 > n > 0, the usability period is between n-1 and n days.
        public const byte TYPE_NO_ORBIT_DATA = 0;
        public const byte TYPE_ASSISTNOW_OFFLINE = 1;
        public const byte TYPE_ASSISTNOW_AUTONOMOUS = 2;
        public byte orb_type { get; set; }
        // Type of orbit data

        public OtherOrbInfo()
        {
            this.ano_aop_usability = 0;
            this.orb_type = 0;
        }

        public OtherOrbInfo(byte ano_aop_usability, byte orb_type)
        {
            this.ano_aop_usability = ano_aop_usability;
            this.orb_type = orb_type;
        }
    }
}
#endif
