/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class PSMStatus : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/PSMStatus";

        //  Power Save Mode for Status
        public const byte PSM_STATE_ACQUISITION = 0;
        public const byte PSM_STATE_TRACKING = 1;
        public const byte PSM_STATE_POWER_OPTIMIZED_TRACKING = 2;
        public const byte PSM_STATE_INACTIVE = 3;
        public byte state { get; set; }
        // power save mode state

        public PSMStatus()
        {
            this.state = 0;
        }

        public PSMStatus(byte state)
        {
            this.state = state;
        }
    }
}
#endif
