/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class RawxData : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/RawxData";

        //  RawxData.msg
        //  UBX-RXM-RAWX (0x02 0x15) - Multi-GNSS raw measurements
        //  Fields
        public double pr_mes { get; set; }
        // m - Pseudorange measurement
        public double cp_mes { get; set; }
        // cycles - Carrier phase measurement
        public float do_mes { get; set; }
        // Hz - Doppler measurement
        public byte gnss_id { get; set; }
        // GNSS identifier
        public byte sv_id { get; set; }
        // Satellite identifier
        public byte sig_id { get; set; }
        // Signal identifier
        public byte freq_id { get; set; }
        // Frequency slot for GLONASS
        public ushort locktime { get; set; }
        // ms - Carrier phase locktime counter
        public byte c_no { get; set; }
        // dBHz - Carrier-to-noise density ratio
        public byte pr_stdev { get; set; }
        // 0.01*2^n m - Estimated pseudorange standard deviation
        public byte cp_stdev { get; set; }
        // 0.004 cycles - Estimated carrier phase standard deviation
        public byte do_stdev { get; set; }
        // 0.002*2^n Hz - Estimated Doppler standard deviation
        public TrkStat trk_stat { get; set; }
        // Tracking status bitfield
        //  uint8 reserved1     # Reserved

        public RawxData()
        {
            this.pr_mes = 0.0;
            this.cp_mes = 0.0;
            this.do_mes = 0.0f;
            this.gnss_id = 0;
            this.sv_id = 0;
            this.sig_id = 0;
            this.freq_id = 0;
            this.locktime = 0;
            this.c_no = 0;
            this.pr_stdev = 0;
            this.cp_stdev = 0;
            this.do_stdev = 0;
            this.trk_stat = new TrkStat();
        }

        public RawxData(double pr_mes, double cp_mes, float do_mes, byte gnss_id, byte sv_id, byte sig_id, byte freq_id, ushort locktime, byte c_no, byte pr_stdev, byte cp_stdev, byte do_stdev, TrkStat trk_stat)
        {
            this.pr_mes = pr_mes;
            this.cp_mes = cp_mes;
            this.do_mes = do_mes;
            this.gnss_id = gnss_id;
            this.sv_id = sv_id;
            this.sig_id = sig_id;
            this.freq_id = freq_id;
            this.locktime = locktime;
            this.c_no = c_no;
            this.pr_stdev = pr_stdev;
            this.cp_stdev = cp_stdev;
            this.do_stdev = do_stdev;
            this.trk_stat = trk_stat;
        }
    }
}
#endif
