/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class RecStat : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/RecStat";

        //  RecStat.msg
        //  UBX-RXM-RAWX (0x02 0x15) - Receiver tracking status bitfield
        //  Fields
        public bool leap_sec { get; set; }
        // Leap seconds have been determined
        public bool clk_reset { get; set; }
        // Clock reset applied

        public RecStat()
        {
            this.leap_sec = false;
            this.clk_reset = false;
        }

        public RecStat(bool leap_sec, bool clk_reset)
        {
            this.leap_sec = leap_sec;
            this.clk_reset = clk_reset;
        }
    }
}
#endif
