/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class SatFlags : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/SatFlags";

        //  Bit field structure for flags in UBX-NAV-SAT (0x01 0x35)
        //  Signal quality indicator
        public const byte QUALITY_NO_SIGNAL = 0;
        public const byte QUALITY_SEARCHING = 1;
        public const byte QUALITY_ACQUIRED = 2;
        public const byte QUALITY_UNUSABLE = 3;
        public const byte QUALITY_CODE_LOCKED = 4;
        public const byte QUALITY_CARRIER_LOCKED = 5;
        public byte quality_ind { get; set; }
        //  Signal currently being used for navigation
        public bool sv_used { get; set; }
        //  Signal health flag
        public const byte HEALTH_UNKNOWN = 0;
        public const byte HEALTH_HEALTHY = 1;
        public const byte HEALTH_UNHEALTHY = 2;
        public byte health { get; set; }
        //  Differential correction data availability
        public bool diff_corr { get; set; }
        //  Carrier smoothed pseudorange used
        public bool smoothed { get; set; }
        //  Orbit source
        public const byte ORBIT_NO_INFO = 0;
        public const byte ORBIT_EPH_USED = 1;
        public const byte ORBIT_ALM_USED = 2;
        public const byte ORBIT_ASSISTNOW_OFFLINE = 3;
        public const byte ORBIT_ASSISTNOW_AUTONOMOUS = 4;
        public byte orbit_source { get; set; }
        //  Ephemeris availability
        public bool eph_avail { get; set; }
        //  Almanac availability
        public bool alm_avail { get; set; }
        //  AssistNow Offline data availability
        public bool ano_avail { get; set; }
        //  AssistNow Autonomous data availability
        public bool aop_avail { get; set; }
        //  Corrections used flags
        public bool sbas_corr_used { get; set; }
        public bool rtcm_corr_used { get; set; }
        public bool slas_corr_used { get; set; }
        public bool spartn_corr_used { get; set; }
        public bool pr_corr_used { get; set; }
        public bool cr_corr_used { get; set; }
        public bool do_corr_used { get; set; }
        public bool clas_corr_used { get; set; }

        public SatFlags()
        {
            this.quality_ind = 0;
            this.sv_used = false;
            this.health = 0;
            this.diff_corr = false;
            this.smoothed = false;
            this.orbit_source = 0;
            this.eph_avail = false;
            this.alm_avail = false;
            this.ano_avail = false;
            this.aop_avail = false;
            this.sbas_corr_used = false;
            this.rtcm_corr_used = false;
            this.slas_corr_used = false;
            this.spartn_corr_used = false;
            this.pr_corr_used = false;
            this.cr_corr_used = false;
            this.do_corr_used = false;
            this.clas_corr_used = false;
        }

        public SatFlags(byte quality_ind, bool sv_used, byte health, bool diff_corr, bool smoothed, byte orbit_source, bool eph_avail, bool alm_avail, bool ano_avail, bool aop_avail, bool sbas_corr_used, bool rtcm_corr_used, bool slas_corr_used, bool spartn_corr_used, bool pr_corr_used, bool cr_corr_used, bool do_corr_used, bool clas_corr_used)
        {
            this.quality_ind = quality_ind;
            this.sv_used = sv_used;
            this.health = health;
            this.diff_corr = diff_corr;
            this.smoothed = smoothed;
            this.orbit_source = orbit_source;
            this.eph_avail = eph_avail;
            this.alm_avail = alm_avail;
            this.ano_avail = ano_avail;
            this.aop_avail = aop_avail;
            this.sbas_corr_used = sbas_corr_used;
            this.rtcm_corr_used = rtcm_corr_used;
            this.slas_corr_used = slas_corr_used;
            this.spartn_corr_used = spartn_corr_used;
            this.pr_corr_used = pr_corr_used;
            this.cr_corr_used = cr_corr_used;
            this.do_corr_used = do_corr_used;
            this.clas_corr_used = clas_corr_used;
        }
    }
}
#endif
