/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class SBASService : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/SBASService";

        //  SBAS Services available
        public bool ranging { get; set; }
        // GEO may be used as ranging source
        public bool corrections { get; set; }
        // GEO is providing correction data
        public bool integrity { get; set; }
        // GEO is providing integrity
        public bool test_mode { get; set; }
        // GEO is in test mode
        public bool bad { get; set; }
        // Problem with signal or broadcast data indicated

        public SBASService()
        {
            this.ranging = false;
            this.corrections = false;
            this.integrity = false;
            this.test_mode = false;
            this.bad = false;
        }

        public SBASService(bool ranging, bool corrections, bool integrity, bool test_mode, bool bad)
        {
            this.ranging = ranging;
            this.corrections = corrections;
            this.integrity = integrity;
            this.test_mode = test_mode;
            this.bad = bad;
        }
    }
}
#endif
