/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class SBASStatusFlags : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/SBASStatusFlags";

        //  SBAS status flags
        public const byte INTEGRITY_UNKNOWN = 0;
        public const byte INTEGRITY_NOT_AVAILABLE = 1;
        public const byte INTEGRITY_USED = 2;
        public byte integrity_used { get; set; }
        // SBAS integrity used

        public SBASStatusFlags()
        {
            this.integrity_used = 0;
        }

        public SBASStatusFlags(byte integrity_used)
        {
            this.integrity_used = integrity_used;
        }
    }
}
#endif
