/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class SBASSvData : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/SBASSvData";

        //  Information for each Satellite in SBAS
        public byte svid { get; set; }
        // SV ID
        public byte reserved_1 { get; set; }
        // Reserved
        public byte udre { get; set; }
        // Monitoring status
        public byte sv_sys { get; set; }
        // System (WAAS/EGNOS/...)
        public byte sv_service { get; set; }
        // Services available, same as SERVICE
        public byte reserved_2 { get; set; }
        // Reserved
        public short prc { get; set; }
        // Pseudo Range correction in [cm]
        public byte[] reserved_3 { get; set; }
        // Reserved
        public short ic { get; set; }
        // Ionosphere correction in [cm]

        public SBASSvData()
        {
            this.svid = 0;
            this.reserved_1 = 0;
            this.udre = 0;
            this.sv_sys = 0;
            this.sv_service = 0;
            this.reserved_2 = 0;
            this.prc = 0;
            this.reserved_3 = new byte[2];
            this.ic = 0;
        }

        public SBASSvData(byte svid, byte reserved_1, byte udre, byte sv_sys, byte sv_service, byte reserved_2, short prc, byte[] reserved_3, short ic)
        {
            this.svid = svid;
            this.reserved_1 = reserved_1;
            this.udre = udre;
            this.sv_sys = sv_sys;
            this.sv_service = sv_service;
            this.reserved_2 = reserved_2;
            this.prc = prc;
            this.reserved_3 = reserved_3;
            this.ic = ic;
        }
    }
}
#endif
