/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class SigData : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/SigData";

        //  Information for each Signal in UBX-NAV-SIG
        //  Constants for Signal Quality Indicator
        public const byte QUALITY_NO_SIGNAL = 0;
        public const byte QUALITY_SEARCHING_SIGNAL = 1;
        public const byte QUALITY_SIGNAL_ACQUIRED = 2;
        public const byte QUALITY_SIGNAL_UNUSABLE = 3;
        public const byte QUALITY_CODE_LOCKED = 4;
        public const byte QUALITY_CODE_CARRIER_LOCKED = 5;
        //  6 and 7 are also considered as code and carrier locked and time synchronized
        //  Constants for Correction Source
        public const byte CORR_NONE = 0;
        public const byte CORR_SBAS = 1;
        public const byte CORR_BEIDOU = 2;
        public const byte CORR_RTCM2 = 3;
        public const byte CORR_RTCM3_OSR = 4;
        public const byte CORR_RTCM3_SSR = 5;
        public const byte CORR_QZSS_SLAS = 6;
        public const byte CORR_SPARTN = 7;
        public const byte CORR_CLAS = 8;
        //  Constants for Ionospheric Model
        public const byte IONO_NONE = 0;
        public const byte IONO_KLOB_GPS = 1;
        public const byte IONO_SBAS = 2;
        public const byte IONO_KLOB_BEIDOU = 3;
        //  8 is considered as Iono delay derived from dual frequency observations
        public byte gnss_id { get; set; }
        // GNSS identifier
        public byte sv_id { get; set; }
        // Satellite identifier
        public byte sig_id { get; set; }
        // New style signal identifier
        public byte freq_id { get; set; }
        // Frequency slot + 7 (GLONASS)
        public short pr_res { get; set; }
        // Pseudorange residual (scaled by 0.1)
        public byte cno { get; set; }
        // Carrier-to-noise density ratio
        public byte quality_ind { get; set; }
        // Signal quality indicator
        public byte corr_source { get; set; }
        // Correction source
        public byte iono_model { get; set; }
        // Ionospheric model used
        public SigFlags sig_flags { get; set; }
        // Signal related flags
        //  uint8[4] reserved_1 # Reserved

        public SigData()
        {
            this.gnss_id = 0;
            this.sv_id = 0;
            this.sig_id = 0;
            this.freq_id = 0;
            this.pr_res = 0;
            this.cno = 0;
            this.quality_ind = 0;
            this.corr_source = 0;
            this.iono_model = 0;
            this.sig_flags = new SigFlags();
        }

        public SigData(byte gnss_id, byte sv_id, byte sig_id, byte freq_id, short pr_res, byte cno, byte quality_ind, byte corr_source, byte iono_model, SigFlags sig_flags)
        {
            this.gnss_id = gnss_id;
            this.sv_id = sv_id;
            this.sig_id = sig_id;
            this.freq_id = freq_id;
            this.pr_res = pr_res;
            this.cno = cno;
            this.quality_ind = quality_ind;
            this.corr_source = corr_source;
            this.iono_model = iono_model;
            this.sig_flags = sig_flags;
        }
    }
}
#endif
