/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class SigLogEvent : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/SigLogEvent";

        //  Constants for Detection Types
        public const byte DETECTION_SIMULATED_SIGNAL = 0;
        public const byte DETECTION_ABNORMAL_SIGNAL = 1;
        public const byte DETECTION_INS_GNSS_MISMATCH = 2;
        public const byte DETECTION_ABRUPT_CHANGES = 3;
        public const byte DETECTION_BROADBAND_JAMMING = 4;
        public const byte DETECTION_NARROWBAND_JAMMING = 5;
        //  Constants for Event Types
        public const byte EVENT_STARTED = 0;
        public const byte EVENT_STOPPED = 1;
        public const byte EVENT_TRIGGERED = 2;
        public const byte EVENT_TIMED_OUT = 3;
        //  Fields
        public uint time_elapsed { get; set; }
        // s - Seconds elapsed since this event. Special value 0xFFFFFFFF: more than 45 days
        public byte detection_type { get; set; }
        // Type of the spoofing or jamming detection
        public byte event_type { get; set; }
        // Type of the event
        //  uint8[2] reserved_1    # Reserved

        public SigLogEvent()
        {
            this.time_elapsed = 0;
            this.detection_type = 0;
            this.event_type = 0;
        }

        public SigLogEvent(uint time_elapsed, byte detection_type, byte event_type)
        {
            this.time_elapsed = time_elapsed;
            this.detection_type = detection_type;
            this.event_type = event_type;
        }
    }
}
#endif
