/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class SpartnKeyInfo : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/SpartnKeyInfo";

        //  SpartnKeyInfo - Key information for UBX-RXM-SPARTNKEY
        //  Fields
        public byte reserved1 { get; set; }
        // Reserved
        public byte key_length_bytes { get; set; }
        // Key length in bytes
        public ushort valid_from_wno { get; set; }
        // GPS week number the key is valid from
        public uint valid_from_tow { get; set; }
        // GPS time of week the key is valid from

        public SpartnKeyInfo()
        {
            this.reserved1 = 0;
            this.key_length_bytes = 0;
            this.valid_from_wno = 0;
            this.valid_from_tow = 0;
        }

        public SpartnKeyInfo(byte reserved1, byte key_length_bytes, ushort valid_from_wno, uint valid_from_tow)
        {
            this.reserved1 = reserved1;
            this.key_length_bytes = key_length_bytes;
            this.valid_from_wno = valid_from_wno;
            this.valid_from_tow = valid_from_tow;
        }
    }
}
#endif
