/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class SpoofDet : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/SpoofDet";

        public const byte SPOOF_DET_UNKNOWN = 0;
        public const byte SPOOF_DET_NO_SPOOFING = 1;
        public const byte SPOOF_DET_SPOOFING = 2;
        public const byte SPOOF_DET_MULTIPLE_SPOOFING = 3;
        public byte state { get; set; }
        // spoofing det state

        public SpoofDet()
        {
            this.state = 0;
        }

        public SpoofDet(byte state)
        {
            this.state = state;
        }
    }
}
#endif
