/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class TrkStat : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/TrkStat";

        //  TrkStat.msg
        //  UBX-RXM-RAWX (0x02 0x15) - Tracking status bitfield for Multi-GNSS raw measurements
        //  Fields
        public bool pr_valid { get; set; }
        // Pseudorange valid
        public bool cp_valid { get; set; }
        // Carrier phase valid
        public bool half_cyc { get; set; }
        // Half cycle valid
        public bool sub_half_cyc { get; set; }
        // Half cycle subtracted from phase

        public TrkStat()
        {
            this.pr_valid = false;
            this.cp_valid = false;
            this.half_cyc = false;
            this.sub_half_cyc = false;
        }

        public TrkStat(bool pr_valid, bool cp_valid, bool half_cyc, bool sub_half_cyc)
        {
            this.pr_valid = pr_valid;
            this.cp_valid = cp_valid;
            this.half_cyc = half_cyc;
            this.sub_half_cyc = sub_half_cyc;
        }
    }
}
#endif
