/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXEsfMeas : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXEsfMeas";

        //  this message contains a UBX-ESF-MEAS (0x10 0x02) record
        //  External sesnor fusion measurement
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        public uint time_tag { get; set; }
        // time tag of measurement generated by external sensor
        public byte time_mark_sent { get; set; }
        // time mark signal was supplied just prior to sending this message: 0 = None, 1 = on Ext0, 2 = on Ext1
        public bool time_mark_edge { get; set; }
        // trigger on rising (0) or falling (1) edge of time mark signal
        public bool calib_ttag_valid { get; set; }
        // calibration time tag available. Always set to Zero
        public byte num_meas { get; set; }
        // Number of measurements contained in this message (optional, can be obtained from message size)
        public ushort id { get; set; }
        // identification number of data provideer
        public ESFMeasDataItem[] data { get; set; }
        // data array  of data_field & data_type
        public uint calib_ttag { get; set; }
        // receiver local time calibrated. This field must not be supplied when calb_ttag_valid is 0

        public UBXEsfMeas()
        {
            this.header = new Header();
            this.time_tag = 0;
            this.time_mark_sent = 0;
            this.time_mark_edge = false;
            this.calib_ttag_valid = false;
            this.num_meas = 0;
            this.id = 0;
            this.data = new ESFMeasDataItem[0];
            this.calib_ttag = 0;
        }

        public UBXEsfMeas(Header header, uint time_tag, byte time_mark_sent, bool time_mark_edge, bool calib_ttag_valid, byte num_meas, ushort id, ESFMeasDataItem[] data, uint calib_ttag)
        {
            this.header = header;
            this.time_tag = time_tag;
            this.time_mark_sent = time_mark_sent;
            this.time_mark_edge = time_mark_edge;
            this.calib_ttag_valid = calib_ttag_valid;
            this.num_meas = num_meas;
            this.id = id;
            this.data = data;
            this.calib_ttag = calib_ttag;
        }
    }
}
#endif
