/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXMonComms : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXMonComms";

        //  UBXMonComms - Overall communications monitoring message
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        //  Constants for protocol in prot_ids
        public const byte PROTOCOL_UBX = 0;
        public const byte PROTOCOL_NMEA = 1;
        public const byte PROTOCOL_RTCM2 = 2;
        public const byte PROTOCOL_RTCM3 = 5;
        public const byte PROTOCOL_SPARTN = 6;
        public const byte NO_PROTOCOL = 255;
        public byte version { get; set; }
        // Message version
        public byte n_ports { get; set; }
        // Number of ports reported
        public byte tx_errors { get; set; }
        // Transmit errors flags
        public byte reserved0 { get; set; }
        // Reserved byte
        public byte[] prot_ids { get; set; }
        // Protocol identifiers active on this device: [0-3]
        public CommsPortInfo[] ports { get; set; }
        // Array of CommsPortInfo for each reported port

        public UBXMonComms()
        {
            this.header = new Header();
            this.version = 0;
            this.n_ports = 0;
            this.tx_errors = 0;
            this.reserved0 = 0;
            this.prot_ids = new byte[4];
            this.ports = new CommsPortInfo[0];
        }

        public UBXMonComms(Header header, byte version, byte n_ports, byte tx_errors, byte reserved0, byte[] prot_ids, CommsPortInfo[] ports)
        {
            this.header = header;
            this.version = version;
            this.n_ports = n_ports;
            this.tx_errors = tx_errors;
            this.reserved0 = reserved0;
            this.prot_ids = prot_ids;
            this.ports = ports;
        }
    }
}
#endif
