/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXNavVelECEF : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXNavVelECEF";

        //  this message contains a UBX-NAV-VELECEF (0x01 0x11) record
        //  Velocity solution in ECEF
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        public uint itow { get; set; }
        // ms - GPS Time of week of the navigation epoch
        public int ecef_vx { get; set; }
        // cm/s - ECEF X velocity
        public int ecef_vy { get; set; }
        // cm/s - ECEF Y velocity
        public int ecef_vz { get; set; }
        // cm/s - ECEF Z velocity
        public uint s_acc { get; set; }
        // cm/s - velocity accuracy estimate

        public UBXNavVelECEF()
        {
            this.header = new Header();
            this.itow = 0;
            this.ecef_vx = 0;
            this.ecef_vy = 0;
            this.ecef_vz = 0;
            this.s_acc = 0;
        }

        public UBXNavVelECEF(Header header, uint itow, int ecef_vx, int ecef_vy, int ecef_vz, uint s_acc)
        {
            this.header = header;
            this.itow = itow;
            this.ecef_vx = ecef_vx;
            this.ecef_vy = ecef_vy;
            this.ecef_vz = ecef_vz;
            this.s_acc = s_acc;
        }
    }
}
#endif
