/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXNavPVT : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXNavPVT";

        //  this message contains a UBX-NAV-PVT (0x01 0x07) record
        //  Navigation position velocity time solution
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        public uint itow { get; set; }
        // ms - GPS Time of week of the navigation epoch
        public ushort year { get; set; }
        // y - year utc
        public byte month { get; set; }
        // month - month utc
        public byte day { get; set; }
        // d -day utc
        public byte hour { get; set; }
        // h - hour utc
        public byte min { get; set; }
        // min - min utc
        public byte sec { get; set; }
        // s - sec utc
        public bool valid_date { get; set; }
        // valid UTC date
        public bool valid_time { get; set; }
        // valid UTC time of day
        public bool fully_resolved { get; set; }
        // UTC Time of day has been fully resolved (no seconds uncertainty)
        public bool valid_mag { get; set; }
        // valid magnetic declination
        public uint t_acc { get; set; }
        // ns - time accuracy estimate (utc)
        public int nano { get; set; }
        // ns - fraction of second, range -1e9 to 1e9 (utc)
        public GpsFix gps_fix { get; set; }
        // GNSSFix type
        public bool gnss_fix_ok { get; set; }
        // valid fix (ie within DOP & accruacy masks)
        public bool diff_soln { get; set; }
        // differential corrections were applied
        public PSMPVT psm { get; set; }
        // power save mode state
        public bool head_veh_valid { get; set; }
        // heading of vehicle is valid, only set if the receiver is in sensor fusion mode
        public CarrSoln carr_soln { get; set; }
        // carrier phase rnage solution status
        public bool confirmed_avail { get; set; }
        // information about UTC date and time of day validity confirmation is available
        public bool confirmed_date { get; set; }
        // UTC Date validity could be confirmed
        public bool confirmed_time { get; set; }
        // UTC Time of Day validity could be confirmed
        public byte num_sv { get; set; }
        // Number of satellites used in Nav Solution
        public int lon { get; set; }
        // deg scale ie-7 - longitude
        public int lat { get; set; }
        // deg scale ie-7 - latitude
        public int height { get; set; }
        // mm - Height above ellipsoid
        public int hmsl { get; set; }
        // mm - Height above mean sea level
        public uint h_acc { get; set; }
        // mm - Horizontal accuracy estimate
        public uint v_acc { get; set; }
        // mm - Vertical accuracy estimate
        public int vel_n { get; set; }
        // mm/s - NED north velocity
        public int vel_e { get; set; }
        // mm/s - NED east velocity
        public int vel_d { get; set; }
        // mm/s - NED down velocity
        public int g_speed { get; set; }
        // mm/s - ground speed (2-D)
        public int head_mot { get; set; }
        // deg scale ie-5 - heading of motion (2-D)
        public uint s_acc { get; set; }
        // mm/s - speed accuracy estimate
        public uint head_acc { get; set; }
        // deg scale ie-5 - heading accruracy estime (both motion and vehicle)
        public ushort p_dop { get; set; }
        // scale 0.01 - Position DOP
        public bool invalid_llh { get; set; }
        // invalid lon, lat, height, hmsl
        public int head_veh { get; set; }
        // deg scale 1e-5 - Heading of vehicle (2-D), this is only valid when head_veh_valid is set,
        //  otherwise the output is set to the heading of motion
        public short mag_dec { get; set; }
        // deg scale 1e-2 - Magnetic declination. Only supported in ADR 4.10 and later
        public ushort mag_acc { get; set; }
        // deg scale ie-2 - Mangetic declination accuracy. Only supported in ADR 4.10 and later

        public UBXNavPVT()
        {
            this.header = new Header();
            this.itow = 0;
            this.year = 0;
            this.month = 0;
            this.day = 0;
            this.hour = 0;
            this.min = 0;
            this.sec = 0;
            this.valid_date = false;
            this.valid_time = false;
            this.fully_resolved = false;
            this.valid_mag = false;
            this.t_acc = 0;
            this.nano = 0;
            this.gps_fix = new GpsFix();
            this.gnss_fix_ok = false;
            this.diff_soln = false;
            this.psm = new PSMPVT();
            this.head_veh_valid = false;
            this.carr_soln = new CarrSoln();
            this.confirmed_avail = false;
            this.confirmed_date = false;
            this.confirmed_time = false;
            this.num_sv = 0;
            this.lon = 0;
            this.lat = 0;
            this.height = 0;
            this.hmsl = 0;
            this.h_acc = 0;
            this.v_acc = 0;
            this.vel_n = 0;
            this.vel_e = 0;
            this.vel_d = 0;
            this.g_speed = 0;
            this.head_mot = 0;
            this.s_acc = 0;
            this.head_acc = 0;
            this.p_dop = 0;
            this.invalid_llh = false;
            this.head_veh = 0;
            this.mag_dec = 0;
            this.mag_acc = 0;
        }

        public UBXNavPVT(Header header, uint itow, ushort year, byte month, byte day, byte hour, byte min, byte sec, bool valid_date, bool valid_time, bool fully_resolved, bool valid_mag, uint t_acc, int nano, GpsFix gps_fix, bool gnss_fix_ok, bool diff_soln, PSMPVT psm, bool head_veh_valid, CarrSoln carr_soln, bool confirmed_avail, bool confirmed_date, bool confirmed_time, byte num_sv, int lon, int lat, int height, int hmsl, uint h_acc, uint v_acc, int vel_n, int vel_e, int vel_d, int g_speed, int head_mot, uint s_acc, uint head_acc, ushort p_dop, bool invalid_llh, int head_veh, short mag_dec, ushort mag_acc)
        {
            this.header = header;
            this.itow = itow;
            this.year = year;
            this.month = month;
            this.day = day;
            this.hour = hour;
            this.min = min;
            this.sec = sec;
            this.valid_date = valid_date;
            this.valid_time = valid_time;
            this.fully_resolved = fully_resolved;
            this.valid_mag = valid_mag;
            this.t_acc = t_acc;
            this.nano = nano;
            this.gps_fix = gps_fix;
            this.gnss_fix_ok = gnss_fix_ok;
            this.diff_soln = diff_soln;
            this.psm = psm;
            this.head_veh_valid = head_veh_valid;
            this.carr_soln = carr_soln;
            this.confirmed_avail = confirmed_avail;
            this.confirmed_date = confirmed_date;
            this.confirmed_time = confirmed_time;
            this.num_sv = num_sv;
            this.lon = lon;
            this.lat = lat;
            this.height = height;
            this.hmsl = hmsl;
            this.h_acc = h_acc;
            this.v_acc = v_acc;
            this.vel_n = vel_n;
            this.vel_e = vel_e;
            this.vel_d = vel_d;
            this.g_speed = g_speed;
            this.head_mot = head_mot;
            this.s_acc = s_acc;
            this.head_acc = head_acc;
            this.p_dop = p_dop;
            this.invalid_llh = invalid_llh;
            this.head_veh = head_veh;
            this.mag_dec = mag_dec;
            this.mag_acc = mag_acc;
        }
    }
}
#endif
