/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXNavSvin : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXNavSvin";

        //  this message contains a UBX-NAV-SVIN (0x01 0x3b) record
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        public byte version { get; set; }
        // Message version
        public uint itow { get; set; }
        // ms - GPS Time of week of the navigation epoch
        public uint dur { get; set; }
        // s - Passed survey-in observation time
        public int mean_x { get; set; }
        // cm - Current survey-in mean position ECEF X coordinate
        public int mean_y { get; set; }
        // cm - Current survey-in mean position ECEF Y coordinate
        public int mean_z { get; set; }
        // cm - Current survey-in mean position ECEF Z coordinate
        public sbyte mean_x_hp { get; set; }
        // 0.1mm - Current high-precision survey-in mean position
        //  ECEF X coordinate. Must be in the range -99..+99.
        //  The current survey-in mean position ECEF X coordinate,
        //  in units of cm, is given by meanX + (0.01 * meanXHP)
        public sbyte mean_y_hp { get; set; }
        // 0.1mm - Current high-precision survey-in mean position
        //  ECEF Y coordinate. Must be in the range -99..+99.
        //  The current survey-in mean position ECEF Y coordinate,
        //  in units of cm, is given by meanY + (0.01 * meanYHP)
        public sbyte mean_z_hp { get; set; }
        // 0.1mm - Current high-precision survey-in mean position
        //  ECEF Z coordinate. Must be in the range -99..+99.
        //  The current survey-in mean position ECEF Z coordinate,
        //  in units of cm, is given by meanZ + (0.01 * meanZHP)
        public uint mean_acc { get; set; }
        // 0.1mm - Current survey-in mean position accuracy
        public uint obs { get; set; }
        // Number of position observations used during survey-in
        public bool valid { get; set; }
        // Survey-in position validity flag, 1 = valid, otherwise
        //  0
        public bool active { get; set; }
        // Survey-in in progress flag, 1 = in-progress, otherwise
        //  0

        public UBXNavSvin()
        {
            this.header = new Header();
            this.version = 0;
            this.itow = 0;
            this.dur = 0;
            this.mean_x = 0;
            this.mean_y = 0;
            this.mean_z = 0;
            this.mean_x_hp = 0;
            this.mean_y_hp = 0;
            this.mean_z_hp = 0;
            this.mean_acc = 0;
            this.obs = 0;
            this.valid = false;
            this.active = false;
        }

        public UBXNavSvin(Header header, byte version, uint itow, uint dur, int mean_x, int mean_y, int mean_z, sbyte mean_x_hp, sbyte mean_y_hp, sbyte mean_z_hp, uint mean_acc, uint obs, bool valid, bool active)
        {
            this.header = header;
            this.version = version;
            this.itow = itow;
            this.dur = dur;
            this.mean_x = mean_x;
            this.mean_y = mean_y;
            this.mean_z = mean_z;
            this.mean_x_hp = mean_x_hp;
            this.mean_y_hp = mean_y_hp;
            this.mean_z_hp = mean_z_hp;
            this.mean_acc = mean_acc;
            this.obs = obs;
            this.valid = valid;
            this.active = active;
        }
    }
}
#endif
