/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXNavSig : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXNavSig";

        //  UBX-NAV-SIG (0x01 0x43) - Signal information
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        public uint itow { get; set; }
        // ms - GPS Time of week of the navigation epoch
        public byte version { get; set; }
        // Message version
        public byte num_sigs { get; set; }
        // Number of signals
        public byte[] reserved_0 { get; set; }
        // Reserved
        public SigData[] sig_data { get; set; }
        // Repeated group of data for each signal

        public UBXNavSig()
        {
            this.header = new Header();
            this.itow = 0;
            this.version = 0;
            this.num_sigs = 0;
            this.reserved_0 = new byte[2];
            this.sig_data = new SigData[0];
        }

        public UBXNavSig(Header header, uint itow, byte version, byte num_sigs, byte[] reserved_0, SigData[] sig_data)
        {
            this.header = header;
            this.itow = itow;
            this.version = version;
            this.num_sigs = num_sigs;
            this.reserved_0 = reserved_0;
            this.sig_data = sig_data;
        }
    }
}
#endif
