/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXNavOrb : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXNavOrb";

        //  UBX-NAV-ORB (0x01 0x34) - GNSS orbit database info
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        public uint itow { get; set; }
        // ms - GPS Time of week of the navigation epoch
        public byte version { get; set; }
        // Message version (0x01 for this version)
        public byte num_sv { get; set; }
        // Number of SVs in the database
        public byte[] reserved_0 { get; set; }
        // Reserved
        public OrbSVInfo[] sv_info { get; set; }
        // Repeated group of data for each SV

        public UBXNavOrb()
        {
            this.header = new Header();
            this.itow = 0;
            this.version = 0;
            this.num_sv = 0;
            this.reserved_0 = new byte[2];
            this.sv_info = new OrbSVInfo[0];
        }

        public UBXNavOrb(Header header, uint itow, byte version, byte num_sv, byte[] reserved_0, OrbSVInfo[] sv_info)
        {
            this.header = header;
            this.itow = itow;
            this.version = version;
            this.num_sv = num_sv;
            this.reserved_0 = reserved_0;
            this.sv_info = sv_info;
        }
    }
}
#endif
