/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXNavClock : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXNavClock";

        //  this message contains a UBX-NAV-CLOCK (0x01 0x22) record clock solution
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        public uint itow { get; set; }
        // ms - GPS Time of week of the navigation epoch
        public int clk_b { get; set; }
        // ns - Clock bias
        public int clk_d { get; set; }
        // ns/s - Clock drift
        public uint t_acc { get; set; }
        // ns - Time accuracy estimate
        public uint f_acc { get; set; }
        // ps/s - Frequency accuracy estimate

        public UBXNavClock()
        {
            this.header = new Header();
            this.itow = 0;
            this.clk_b = 0;
            this.clk_d = 0;
            this.t_acc = 0;
            this.f_acc = 0;
        }

        public UBXNavClock(Header header, uint itow, int clk_b, int clk_d, uint t_acc, uint f_acc)
        {
            this.header = header;
            this.itow = itow;
            this.clk_b = clk_b;
            this.clk_d = clk_d;
            this.t_acc = t_acc;
            this.f_acc = f_acc;
        }
    }
}
#endif
