/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXNavSat : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXNavSat";

        //  UBX-NAV-SAT (0x01 0x35) - Satellite information
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        public uint itow { get; set; }
        // ms - GPS Time of week of the navigation epoch
        public byte version { get; set; }
        // Message version (0x01 for this version)
        public byte num_svs { get; set; }
        // Number of satellites
        //  uint8[2] reserved_0     # Reserved
        public SatInfo[] sv_info { get; set; }
        // Repeated group of data for each satellite

        public UBXNavSat()
        {
            this.header = new Header();
            this.itow = 0;
            this.version = 0;
            this.num_svs = 0;
            this.sv_info = new SatInfo[0];
        }

        public UBXNavSat(Header header, uint itow, byte version, byte num_svs, SatInfo[] sv_info)
        {
            this.header = header;
            this.itow = itow;
            this.version = version;
            this.num_svs = num_svs;
            this.sv_info = sv_info;
        }
    }
}
#endif
