/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXNavRelPosNED : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXNavRelPosNED";

        //  this message contains a UBX-NAV-ODO (0x01 0x3c) record
        //  Relative position information in NED frame
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        public byte version { get; set; }
        // message version
        public ushort ref_station_id { get; set; }
        // reference station ID. Must be in the range 0..4096
        public uint itow { get; set; }
        // ms - GPS Time of week of the navigation epoch
        public int rel_pos_n { get; set; }
        // cm - North component of relative position vector
        public int rel_pos_e { get; set; }
        // cm - East component of relative position vector
        public int rel_pos_d { get; set; }
        // cm - Down component of relative position vector
        public int rel_pos_length { get; set; }
        // cm - Length of the relative position vector
        public int rel_pos_heading { get; set; }
        // deg scale 1e-5 - Heading of the relative position vector
        public sbyte rel_pos_hp_n { get; set; }
        // mm scale 0.1 - full HP North is given by relPosN + (relPosHPN * 1e-2)
        public sbyte rel_pos_hp_e { get; set; }
        // mm scale 0.1 - full HP East is given by relPosE + (relPosHPE * 1e-2)
        public sbyte rel_pos_hp_d { get; set; }
        // mm scale 0.1 - full HP Down is given by relPosD + (relPosHPD * 1e-2)
        public sbyte rel_pos_hp_length { get; set; }
        // mm scale 0.1 - full HP length is given by relPosLength + (relPosHPLength * 1e-2)
        public uint acc_n { get; set; }
        // mm scale 0.1 - Accuracy of relative position North Component
        public uint acc_e { get; set; }
        // mm scale 0.1 - Accuracy of relative position East Component
        public uint acc_d { get; set; }
        // mm scale 0.1 - Accuracy of relative position Down Component
        public uint acc_length { get; set; }
        // mm scale 0.1 - Accuracy of length of the relative position vector
        public uint acc_heading { get; set; }
        // deg scale 1e-5 - Accuracy of heading of the relative position vector
        public bool gnss_fix_ok { get; set; }
        // A valid fix (i.e within DOP & accuracy masks)
        public bool diff_soln { get; set; }
        // differential corrections were applied
        public bool rel_pos_valid { get; set; }
        // relative position components and accuracies are valid and, in moving base mode only, if baseline is valid
        public CarrSoln carr_soln { get; set; }
        // carrier phase range solution
        public bool is_moving { get; set; }
        // if the received is operating in moving base mode
        public bool ref_pos_miss { get; set; }
        // if extrapolated reference position was used to compute moving base solution this epoch.
        public bool ref_obs_miss { get; set; }
        // if extrapolated reference observations were used to compute moving base solution this epoch.
        public bool rel_pos_heading_valid { get; set; }
        // relPosHeading is valid
        public bool rel_pos_normalized { get; set; }
        // components of the relative position vector (including the high-precision parts) are normalized

        public UBXNavRelPosNED()
        {
            this.header = new Header();
            this.version = 0;
            this.ref_station_id = 0;
            this.itow = 0;
            this.rel_pos_n = 0;
            this.rel_pos_e = 0;
            this.rel_pos_d = 0;
            this.rel_pos_length = 0;
            this.rel_pos_heading = 0;
            this.rel_pos_hp_n = 0;
            this.rel_pos_hp_e = 0;
            this.rel_pos_hp_d = 0;
            this.rel_pos_hp_length = 0;
            this.acc_n = 0;
            this.acc_e = 0;
            this.acc_d = 0;
            this.acc_length = 0;
            this.acc_heading = 0;
            this.gnss_fix_ok = false;
            this.diff_soln = false;
            this.rel_pos_valid = false;
            this.carr_soln = new CarrSoln();
            this.is_moving = false;
            this.ref_pos_miss = false;
            this.ref_obs_miss = false;
            this.rel_pos_heading_valid = false;
            this.rel_pos_normalized = false;
        }

        public UBXNavRelPosNED(Header header, byte version, ushort ref_station_id, uint itow, int rel_pos_n, int rel_pos_e, int rel_pos_d, int rel_pos_length, int rel_pos_heading, sbyte rel_pos_hp_n, sbyte rel_pos_hp_e, sbyte rel_pos_hp_d, sbyte rel_pos_hp_length, uint acc_n, uint acc_e, uint acc_d, uint acc_length, uint acc_heading, bool gnss_fix_ok, bool diff_soln, bool rel_pos_valid, CarrSoln carr_soln, bool is_moving, bool ref_pos_miss, bool ref_obs_miss, bool rel_pos_heading_valid, bool rel_pos_normalized)
        {
            this.header = header;
            this.version = version;
            this.ref_station_id = ref_station_id;
            this.itow = itow;
            this.rel_pos_n = rel_pos_n;
            this.rel_pos_e = rel_pos_e;
            this.rel_pos_d = rel_pos_d;
            this.rel_pos_length = rel_pos_length;
            this.rel_pos_heading = rel_pos_heading;
            this.rel_pos_hp_n = rel_pos_hp_n;
            this.rel_pos_hp_e = rel_pos_hp_e;
            this.rel_pos_hp_d = rel_pos_hp_d;
            this.rel_pos_hp_length = rel_pos_hp_length;
            this.acc_n = acc_n;
            this.acc_e = acc_e;
            this.acc_d = acc_d;
            this.acc_length = acc_length;
            this.acc_heading = acc_heading;
            this.gnss_fix_ok = gnss_fix_ok;
            this.diff_soln = diff_soln;
            this.rel_pos_valid = rel_pos_valid;
            this.carr_soln = carr_soln;
            this.is_moving = is_moving;
            this.ref_pos_miss = ref_pos_miss;
            this.ref_obs_miss = ref_obs_miss;
            this.rel_pos_heading_valid = rel_pos_heading_valid;
            this.rel_pos_normalized = rel_pos_normalized;
        }
    }
}
#endif
