/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXNavVelNED : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXNavVelNED";

        //  this message contains a UBX-NAV-VELNED (0x01 0x12) record
        //  Velocity solution in NED frame
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        public uint itow { get; set; }
        // ms - GPS Time of week of the navigation epoch
        public int vel_n { get; set; }
        // cm/s - NED north velocity
        public int vel_e { get; set; }
        // cm/s - NED east velocity
        public int vel_d { get; set; }
        // cm/s - NED down velocity
        public uint speed { get; set; }
        // cm/s - speed (3-D)
        public uint g_speed { get; set; }
        // cm/s - ground speed (2-D)
        public int heading { get; set; }
        // deg scale ie-5 - heading of motion (2-D)
        public uint s_acc { get; set; }
        // cm/s - speed accuracy estimate
        public uint c_acc { get; set; }
        // deg scale ie-5 - course/heading accruracy estime (both motion and vehicle)

        public UBXNavVelNED()
        {
            this.header = new Header();
            this.itow = 0;
            this.vel_n = 0;
            this.vel_e = 0;
            this.vel_d = 0;
            this.speed = 0;
            this.g_speed = 0;
            this.heading = 0;
            this.s_acc = 0;
            this.c_acc = 0;
        }

        public UBXNavVelNED(Header header, uint itow, int vel_n, int vel_e, int vel_d, uint speed, uint g_speed, int heading, uint s_acc, uint c_acc)
        {
            this.header = header;
            this.itow = itow;
            this.vel_n = vel_n;
            this.vel_e = vel_e;
            this.vel_d = vel_d;
            this.speed = speed;
            this.g_speed = g_speed;
            this.heading = heading;
            this.s_acc = s_acc;
            this.c_acc = c_acc;
        }
    }
}
#endif
