/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXNavHPPosLLH : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXNavHPPosLLH";

        //  this message contains a UBX-NAV-HPPOSLLH (0x01 0x14) record
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        public byte version { get; set; }
        // message version
        public bool invalid_lon { get; set; }
        public bool invalid_lat { get; set; }
        public bool invalid_height { get; set; }
        public bool invalid_hmsl { get; set; }
        // invalid height above mean sea level
        public bool invalid_lon_hp { get; set; }
        public bool invalid_lat_hp { get; set; }
        public bool invalid_height_hp { get; set; }
        public bool invalid_hmsl_hp { get; set; }
        // invalid height above mean sea level
        public uint itow { get; set; }
        // ms - GPS Time of week of the navigation epoch
        public int lon { get; set; }
        // deg scale 1e-7 - longitude
        public int lat { get; set; }
        // deg scale 1e-7 - latitude
        public int height { get; set; }
        // mm - height above ellipsoid
        public int hmsl { get; set; }
        // mm - height above mean sea level
        public sbyte lon_hp { get; set; }
        // deg scale 1e-9 - Precision longitude in deg * 1e-7 = lon +(lonHp * 1e-2)
        public sbyte lat_hp { get; set; }
        // deg scale 1e-9 - Precise latitude in deg  *  1e-7  =  lat  +(latHp * 1e-2)
        public sbyte height_hp { get; set; }
        // mm scale 0.1 - Precise height in mm = height + (heightHp * 0.1)
        public sbyte hmsl_hp { get; set; }
        // mm scale 0.1 - Precise height in mm =hMSL + (hMSLHp * 0.1)
        public uint h_acc { get; set; }
        // mm scale 0.1 - horizontal accuracy estimate
        public uint v_acc { get; set; }
        // mm scale 0.1 - vertical accuracy estimate

        public UBXNavHPPosLLH()
        {
            this.header = new Header();
            this.version = 0;
            this.invalid_lon = false;
            this.invalid_lat = false;
            this.invalid_height = false;
            this.invalid_hmsl = false;
            this.invalid_lon_hp = false;
            this.invalid_lat_hp = false;
            this.invalid_height_hp = false;
            this.invalid_hmsl_hp = false;
            this.itow = 0;
            this.lon = 0;
            this.lat = 0;
            this.height = 0;
            this.hmsl = 0;
            this.lon_hp = 0;
            this.lat_hp = 0;
            this.height_hp = 0;
            this.hmsl_hp = 0;
            this.h_acc = 0;
            this.v_acc = 0;
        }

        public UBXNavHPPosLLH(Header header, byte version, bool invalid_lon, bool invalid_lat, bool invalid_height, bool invalid_hmsl, bool invalid_lon_hp, bool invalid_lat_hp, bool invalid_height_hp, bool invalid_hmsl_hp, uint itow, int lon, int lat, int height, int hmsl, sbyte lon_hp, sbyte lat_hp, sbyte height_hp, sbyte hmsl_hp, uint h_acc, uint v_acc)
        {
            this.header = header;
            this.version = version;
            this.invalid_lon = invalid_lon;
            this.invalid_lat = invalid_lat;
            this.invalid_height = invalid_height;
            this.invalid_hmsl = invalid_hmsl;
            this.invalid_lon_hp = invalid_lon_hp;
            this.invalid_lat_hp = invalid_lat_hp;
            this.invalid_height_hp = invalid_height_hp;
            this.invalid_hmsl_hp = invalid_hmsl_hp;
            this.itow = itow;
            this.lon = lon;
            this.lat = lat;
            this.height = height;
            this.hmsl = hmsl;
            this.lon_hp = lon_hp;
            this.lat_hp = lat_hp;
            this.height_hp = height_hp;
            this.hmsl_hp = hmsl_hp;
            this.h_acc = h_acc;
            this.v_acc = v_acc;
        }
    }
}
#endif
