/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXNavDOP : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXNavDOP";

        //  this message contains a UBX-NAV-DOP (0x01 0x04) record dilution of precision
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        public uint itow { get; set; }
        // ms - GPS Time of week of the navigation epoch
        public uint g_dop { get; set; }
        // 0.01 - Geometric DOP
        public uint p_dop { get; set; }
        // 0.01 - Position DOP
        public uint t_dop { get; set; }
        // 0.01 - Time DOP
        public uint v_dop { get; set; }
        // 0.01 - Vertical DOP
        public uint h_dop { get; set; }
        // 0.01 - Horizontal DOP
        public uint n_dop { get; set; }
        // 0.01 - Northing DOP
        public uint e_dop { get; set; }
        // 0.01 - Easting DOP

        public UBXNavDOP()
        {
            this.header = new Header();
            this.itow = 0;
            this.g_dop = 0;
            this.p_dop = 0;
            this.t_dop = 0;
            this.v_dop = 0;
            this.h_dop = 0;
            this.n_dop = 0;
            this.e_dop = 0;
        }

        public UBXNavDOP(Header header, uint itow, uint g_dop, uint p_dop, uint t_dop, uint v_dop, uint h_dop, uint n_dop, uint e_dop)
        {
            this.header = header;
            this.itow = itow;
            this.g_dop = g_dop;
            this.p_dop = p_dop;
            this.t_dop = t_dop;
            this.v_dop = v_dop;
            this.h_dop = h_dop;
            this.n_dop = n_dop;
            this.e_dop = e_dop;
        }
    }
}
#endif
