/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXNavPosECEF : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXNavPosECEF";

        //  this message contains a UBX-NAV-POSECEF (0x01 0x01) record
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        public uint itow { get; set; }
        // ms - GPS Time of week of the navigation epoch
        public int ecef_x { get; set; }
        // cm - ECEF X coordinate
        public int ecef_y { get; set; }
        // cm - ECEF Y coordinate
        public int ecef_z { get; set; }
        // cm - ECEF Z coordinate
        public uint p_acc { get; set; }
        // cm - position accuracy estimate

        public UBXNavPosECEF()
        {
            this.header = new Header();
            this.itow = 0;
            this.ecef_x = 0;
            this.ecef_y = 0;
            this.ecef_z = 0;
            this.p_acc = 0;
        }

        public UBXNavPosECEF(Header header, uint itow, int ecef_x, int ecef_y, int ecef_z, uint p_acc)
        {
            this.header = header;
            this.itow = itow;
            this.ecef_x = ecef_x;
            this.ecef_y = ecef_y;
            this.ecef_z = ecef_z;
            this.p_acc = p_acc;
        }
    }
}
#endif
