/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXNavPosLLH : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXNavPosLLH";

        //  this message contains a UBX-NAV-POSLLH (0x01 0x02) record
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        public uint itow { get; set; }
        // ms - GPS Time of week of the navigation epoch
        public int lon { get; set; }
        // deg scale 1e-7 - longitude
        public int lat { get; set; }
        // deg scale 1e-7 - latitude
        public int height { get; set; }
        // mm - height above ellipsoid
        public int hmsl { get; set; }
        // mm - height above mean sea level
        public uint h_acc { get; set; }
        // mm - horizontal accuracy estimate
        public uint v_acc { get; set; }
        // mm - vertical accuracy estimate

        public UBXNavPosLLH()
        {
            this.header = new Header();
            this.itow = 0;
            this.lon = 0;
            this.lat = 0;
            this.height = 0;
            this.hmsl = 0;
            this.h_acc = 0;
            this.v_acc = 0;
        }

        public UBXNavPosLLH(Header header, uint itow, int lon, int lat, int height, int hmsl, uint h_acc, uint v_acc)
        {
            this.header = header;
            this.itow = itow;
            this.lon = lon;
            this.lat = lat;
            this.height = height;
            this.hmsl = hmsl;
            this.h_acc = h_acc;
            this.v_acc = v_acc;
        }
    }
}
#endif
