/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXNavStatus : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXNavStatus";

        //  this message contains a UBX-NAV-STATUS (0x01 0x03) record
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        public uint itow { get; set; }
        // ms - GPS Time of week of the navigation epoch
        public GpsFix gps_fix { get; set; }
        // gps fix
        //  navigation status flags
        public bool gps_fix_ok { get; set; }
        // position and velocity valid and within DOP and ACCMasks
        public bool diff_soln { get; set; }
        // differential corrections were applied
        public bool wkn_set { get; set; }
        // week number valid
        public bool tow_set { get; set; }
        // time of week valid
        //  navigation fix status information
        public bool diff_corr { get; set; }
        // differential corrections available
        public bool carr_soln_valid { get; set; }
        // valid carrSoln
        public MapMatching map_matching { get; set; }
        // map matching status
        //  further information about navigation output
        public PSMStatus psm { get; set; }
        // power save mode state
        public SpoofDet spoof_det { get; set; }
        public CarrSoln carr_soln { get; set; }
        // Carrier phase solution status
        public uint ttff { get; set; }
        // time to first fix (milliseond time tag)
        public uint msss { get; set; }
        // milliseconds since Startup/Reset

        public UBXNavStatus()
        {
            this.header = new Header();
            this.itow = 0;
            this.gps_fix = new GpsFix();
            this.gps_fix_ok = false;
            this.diff_soln = false;
            this.wkn_set = false;
            this.tow_set = false;
            this.diff_corr = false;
            this.carr_soln_valid = false;
            this.map_matching = new MapMatching();
            this.psm = new PSMStatus();
            this.spoof_det = new SpoofDet();
            this.carr_soln = new CarrSoln();
            this.ttff = 0;
            this.msss = 0;
        }

        public UBXNavStatus(Header header, uint itow, GpsFix gps_fix, bool gps_fix_ok, bool diff_soln, bool wkn_set, bool tow_set, bool diff_corr, bool carr_soln_valid, MapMatching map_matching, PSMStatus psm, SpoofDet spoof_det, CarrSoln carr_soln, uint ttff, uint msss)
        {
            this.header = header;
            this.itow = itow;
            this.gps_fix = gps_fix;
            this.gps_fix_ok = gps_fix_ok;
            this.diff_soln = diff_soln;
            this.wkn_set = wkn_set;
            this.tow_set = tow_set;
            this.diff_corr = diff_corr;
            this.carr_soln_valid = carr_soln_valid;
            this.map_matching = map_matching;
            this.psm = psm;
            this.spoof_det = spoof_det;
            this.carr_soln = carr_soln;
            this.ttff = ttff;
            this.msss = msss;
        }
    }
}
#endif
