/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXNavOdo : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXNavOdo";

        //  this message contains a UBX-NAV-ODO (0x01 0x09) record Odometer solution
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        public byte version { get; set; }
        // message version
        public uint itow { get; set; }
        // ms - GPS Time of week of the navigation epoch
        public uint distance { get; set; }
        // m - ground distance since last reset
        public uint total_distance { get; set; }
        // m - total comulative ground distance (since last cold start)
        public uint distance_std { get; set; }
        // m - ground distance accuracy (1-sigma)

        public UBXNavOdo()
        {
            this.header = new Header();
            this.version = 0;
            this.itow = 0;
            this.distance = 0;
            this.total_distance = 0;
            this.distance_std = 0;
        }

        public UBXNavOdo(Header header, byte version, uint itow, uint distance, uint total_distance, uint distance_std)
        {
            this.header = header;
            this.version = version;
            this.itow = itow;
            this.distance = distance;
            this.total_distance = total_distance;
            this.distance_std = distance_std;
        }
    }
}
#endif
