/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXNavEOE : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXNavEOE";

        //  this message contains a UBX-NAV-EOE (0x01 0x61) record End of Epoch
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        public uint itow { get; set; }
        // ms - GPS Time of week of the navigation epoch

        public UBXNavEOE()
        {
            this.header = new Header();
            this.itow = 0;
        }

        public UBXNavEOE(Header header, uint itow)
        {
            this.header = header;
            this.itow = itow;
        }
    }
}
#endif
