/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXRxmRTCM : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXRxmRTCM";

        //  this message contains a UBX-RXM-RTCM (0x02 0x32) record
        //  RTCM Input status
        //  This message shows info on a received RTCM input message. It is output upon successful parsing of an RTCM
        //  input message, irrespective of whether the RTCM message is supported or not by the receiver.
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        public byte version { get; set; }
        // message version (0x02 for this version)
        public bool crc_failed { get; set; }
        // 0 When RTCM received & CRC Ok, 1 when failed
        public byte msg_used { get; set; }
        // 2 = RTCM msg used sucessfully, 1 = Not Used, 0 = do not know
        public ushort sub_type { get; set; }
        // message subtype, only applicable to ublox proprietary RTCM 4072
        public ushort ref_station { get; set; }
        // reference station ID refer interface description
        public ushort msg_type { get; set; }
        // message type

        public UBXRxmRTCM()
        {
            this.header = new Header();
            this.version = 0;
            this.crc_failed = false;
            this.msg_used = 0;
            this.sub_type = 0;
            this.ref_station = 0;
            this.msg_type = 0;
        }

        public UBXRxmRTCM(Header header, byte version, bool crc_failed, byte msg_used, ushort sub_type, ushort ref_station, ushort msg_type)
        {
            this.header = header;
            this.version = version;
            this.crc_failed = crc_failed;
            this.msg_used = msg_used;
            this.sub_type = sub_type;
            this.ref_station = ref_station;
            this.msg_type = msg_type;
        }
    }
}
#endif
