/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXRxmRawx : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXRxmRawx";

        //  UBXRxmRAWX.msg
        //  UBX-RXM-RAWX (0x02 0x15) - Multi-GNSS raw measurements
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        //  Fields
        public double rcv_tow { get; set; }
        // s - Measurement time of week
        public ushort week { get; set; }
        // weeks - GPS week number
        public sbyte leap_s { get; set; }
        // s - GPS leap seconds
        public byte num_meas { get; set; }
        // Number of measurements
        public RecStat rec_stat { get; set; }
        // Receiver tracking status bitfield
        public byte version { get; set; }
        // Message version
        //  uint8[2] reserved0   # Reserved
        public RawxData[] rawx_data { get; set; }
        // Repeated group of data for each satellite

        public UBXRxmRawx()
        {
            this.header = new Header();
            this.rcv_tow = 0.0;
            this.week = 0;
            this.leap_s = 0;
            this.num_meas = 0;
            this.rec_stat = new RecStat();
            this.version = 0;
            this.rawx_data = new RawxData[0];
        }

        public UBXRxmRawx(Header header, double rcv_tow, ushort week, sbyte leap_s, byte num_meas, RecStat rec_stat, byte version, RawxData[] rawx_data)
        {
            this.header = header;
            this.rcv_tow = rcv_tow;
            this.week = week;
            this.leap_s = leap_s;
            this.num_meas = num_meas;
            this.rec_stat = rec_stat;
            this.version = version;
            this.rawx_data = rawx_data;
        }
    }
}
#endif
