/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXRxmMeasx : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXRxmMeasx";

        //  UBX-RXM-MEASX (0x02 0x14) - Satellite measurements for RRLP
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        //  Constants for TOW Set
        public const byte TOW_NOT_SET = 0;
        public const byte TOW_SET = 1;
        public const byte TOW_SET2 = 2;
        //  Fields
        public byte version { get; set; }
        // Message version
        //  uint8[3] reserved_0   # Reserved
        public uint gps_tow { get; set; }
        // ms - GPS measurement reference time
        public uint glo_tow { get; set; }
        // ms - GLONASS measurement reference time
        public uint bds_tow { get; set; }
        // ms - BeiDou measurement reference time
        //  uint8[4] reserved_1   # Reserved
        public uint qzss_tow { get; set; }
        // ms - QZSS measurement reference time
        public ushort gps_tow_acc { get; set; }
        // 2^-4 ms - GPS measurement reference time accuracy
        public ushort glo_tow_acc { get; set; }
        // 2^-4 ms - GLONASS measurement reference time accuracy
        public ushort bds_tow_acc { get; set; }
        // 2^-4 ms - BeiDou measurement reference time accuracy
        //  uint8[2] reserved_2   # Reserved
        public ushort qzss_tow_acc { get; set; }
        // 2^-4 ms - QZSS measurement reference time accuracy
        public byte num_sv { get; set; }
        // Number of satellites in repeated block
        public byte flags { get; set; }
        // Flags (refer to constants for TOW Set)
        //  uint8[8] reserved_3   # Reserved
        public MeasxData[] sv_data { get; set; }
        // Repeated group of data for each satellite

        public UBXRxmMeasx()
        {
            this.header = new Header();
            this.version = 0;
            this.gps_tow = 0;
            this.glo_tow = 0;
            this.bds_tow = 0;
            this.qzss_tow = 0;
            this.gps_tow_acc = 0;
            this.glo_tow_acc = 0;
            this.bds_tow_acc = 0;
            this.qzss_tow_acc = 0;
            this.num_sv = 0;
            this.flags = 0;
            this.sv_data = new MeasxData[0];
        }

        public UBXRxmMeasx(Header header, byte version, uint gps_tow, uint glo_tow, uint bds_tow, uint qzss_tow, ushort gps_tow_acc, ushort glo_tow_acc, ushort bds_tow_acc, ushort qzss_tow_acc, byte num_sv, byte flags, MeasxData[] sv_data)
        {
            this.header = header;
            this.version = version;
            this.gps_tow = gps_tow;
            this.glo_tow = glo_tow;
            this.bds_tow = bds_tow;
            this.qzss_tow = qzss_tow;
            this.gps_tow_acc = gps_tow_acc;
            this.glo_tow_acc = glo_tow_acc;
            this.bds_tow_acc = bds_tow_acc;
            this.qzss_tow_acc = qzss_tow_acc;
            this.num_sv = num_sv;
            this.flags = flags;
            this.sv_data = sv_data;
        }
    }
}
#endif
