/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXRxmSpartnKey : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXRxmSpartnKey";

        //  UBX-RXM-SPARTNKEY (0x02 0x36) - Transfer dynamic SPARTN keys
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        //  Fields
        public byte version { get; set; }
        // Message version
        public byte num_keys { get; set; }
        // Number of keys in the message (0, 1, or 2)
        public byte[] reserved0 { get; set; }
        // Reserved
        public SpartnKeyInfo[] key_info { get; set; }
        // Repeated group for key info
        public byte[] key_payload { get; set; }
        // Concatenated key payloads (raw bytes)

        public UBXRxmSpartnKey()
        {
            this.header = new Header();
            this.version = 0;
            this.num_keys = 0;
            this.reserved0 = new byte[2];
            this.key_info = new SpartnKeyInfo[0];
            this.key_payload = new byte[0];
        }

        public UBXRxmSpartnKey(Header header, byte version, byte num_keys, byte[] reserved0, SpartnKeyInfo[] key_info, byte[] key_payload)
        {
            this.header = header;
            this.version = version;
            this.num_keys = num_keys;
            this.reserved0 = reserved0;
            this.key_info = key_info;
            this.key_payload = key_payload;
        }
    }
}
#endif
