/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXSecSig : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXSecSig";

        //  UBX-SEC-SIG (0x27 0x09) - Signal security information
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        //  Constants for Jamming States
        public const byte JAM_UNKNOWN = 0;
        public const byte JAM_NO_JAMMING = 1;
        public const byte JAM_WARNING = 2;
        public const byte JAM_CRITICAL = 3;
        //  Constants for Spoofing States
        public const byte SPF_UNKNOWN = 0;
        public const byte SPF_NO_SPOOFING = 1;
        public const byte SPF_SPOOFING_INDICATED = 2;
        public const byte SPF_SPOOFING_AFFIRMED = 3;
        //  Fields
        public byte version { get; set; }
        // Message version
        //  Information related to jamming/interference
        public byte jam_det_enabled { get; set; }
        // Flag indicates whether jamming/interference detection is enabled
        public byte jamming_state { get; set; }
        // Jamming/interference state
        //  Information related to GNSS spoofing
        public byte spf_det_enabled { get; set; }
        // Flag indicates whether spoofing detection is enabled
        public byte spoofing_state { get; set; }
        // Spoofing state
        //  uint8[1] reserved_0    # Reserved
        public byte jam_num_cent_freqs { get; set; }
        // The number of center frequencies with jamming information
        public JamStateCentFreq[] jam_state_cent_freqs { get; set; }
        // Jamming state of given center frequencies

        public UBXSecSig()
        {
            this.header = new Header();
            this.version = 0;
            this.jam_det_enabled = 0;
            this.jamming_state = 0;
            this.spf_det_enabled = 0;
            this.spoofing_state = 0;
            this.jam_num_cent_freqs = 0;
            this.jam_state_cent_freqs = new JamStateCentFreq[0];
        }

        public UBXSecSig(Header header, byte version, byte jam_det_enabled, byte jamming_state, byte spf_det_enabled, byte spoofing_state, byte jam_num_cent_freqs, JamStateCentFreq[] jam_state_cent_freqs)
        {
            this.header = header;
            this.version = version;
            this.jam_det_enabled = jam_det_enabled;
            this.jamming_state = jamming_state;
            this.spf_det_enabled = spf_det_enabled;
            this.spoofing_state = spoofing_state;
            this.jam_num_cent_freqs = jam_num_cent_freqs;
            this.jam_state_cent_freqs = jam_state_cent_freqs;
        }
    }
}
#endif
