/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXSecSigLog : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXSecSigLog";

        //  UBX-SEC-SIGLOG (0x27 0x10) - Signal security log
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        //  Fields
        public byte version { get; set; }
        // Message version
        public byte num_events { get; set; }
        // Number of events
        //  uint8[6] reserved_0     # Reserved
        //  Repeated group of events
        public SigLogEvent[] events { get; set; }
        // Array of SigLogEvent messages

        public UBXSecSigLog()
        {
            this.header = new Header();
            this.version = 0;
            this.num_events = 0;
            this.events = new SigLogEvent[0];
        }

        public UBXSecSigLog(Header header, byte version, byte num_events, SigLogEvent[] events)
        {
            this.header = header;
            this.version = version;
            this.num_events = num_events;
            this.events = events;
        }
    }
}
#endif
