/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UBXSecUniqid : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UBXSecUniqid";

        //  UBX-SEC-UNIQID (0x27 0x03) - Unique chip ID
        public Header header { get; set; }
        // Header timestamp should be acquisition time
        //  Fields
        public byte version { get; set; }
        // Message version
        //  uint8[3] reserved_0    # Reserved
        public byte[] unique_id { get; set; }
        // Unique chip ID

        public UBXSecUniqid()
        {
            this.header = new Header();
            this.version = 0;
            this.unique_id = new byte[5];
        }

        public UBXSecUniqid(Header header, byte version, byte[] unique_id)
        {
            this.header = header;
            this.version = version;
            this.unique_id = unique_id;
        }
    }
}
#endif
