/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UbloxUbx
{
    public class UtcStd : Message
    {
        public const string RosMessageName = "ublox_ubx_msgs/msg/UtcStd";

        public const byte NOT_AVAILABLE = 0;
        public const byte CRL = 1;
        // Communications Research Labratory (CRL),Tokyo, Japan
        public const byte NIST = 2;
        // National Institute of Standards andTechnology (NIST)
        public const byte USNO = 3;
        // U.S. Naval Observatory (USNO)
        public const byte BIPM = 4;
        // International Bureau of Weights andMeasures (BIPM)
        public const byte EURO = 5;
        // European laboratories
        public const byte SU = 6;
        // Former Soviet Union
        public const byte NTSC = 7;
        // National Time Service Center (NTSC) China
        public const byte UTC_UNKNOWN = 15;
        // Unknown time source
        public byte id { get; set; }
        // uc standard id

        public UtcStd()
        {
            this.id = 0;
        }

        public UtcStd(byte id)
        {
            this.id = id;
        }
    }
}
#endif
