/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.FfmpegImageTransport
{
    public class FFMPEGPacket : Message
    {
        public const string RosMessageName = "ffmpeg_image_transport_msgs/msg/FFMPEGPacket";

        public Header header { get; set; }
        public int width { get; set; }
        // original image width
        public int height { get; set; }
        // original image height
        public string encoding { get; set; }
        // encoding used
        public ulong pts { get; set; }
        // packet pts
        public byte flags { get; set; }
        // packet flags
        public bool is_bigendian { get; set; }
        // true if machine stores in big endian format
        public byte[] data { get; set; }
        // ffmpeg compressed payload

        public FFMPEGPacket()
        {
            this.header = new Header();
            this.width = 0;
            this.height = 0;
            this.encoding = "";
            this.pts = 0;
            this.flags = 0;
            this.is_bigendian = false;
            this.data = new byte[0];
        }

        public FFMPEGPacket(Header header, int width, int height, string encoding, ulong pts, byte flags, bool is_bigendian, byte[] data)
        {
            this.header = header;
            this.width = width;
            this.height = height;
            this.encoding = encoding;
            this.pts = pts;
            this.flags = flags;
            this.is_bigendian = is_bigendian;
            this.data = data;
        }
    }
}
#endif
