/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Geometry;
using RosSharp.RosBridgeClient.MessageTypes.Foxglove;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class ArrowPrimitive : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/ArrowPrimitive";

        //  foxglove_msgs/msg/ArrowPrimitive
        //  A primitive representing an arrow
        //  Generated by https://github.com/foxglove/schemas
        //  Position of the arrow's tail and orientation of the arrow. Identity orientation means the arrow points in the +x direction.
        public Pose pose { get; set; }
        //  Length of the arrow shaft
        public double shaft_length { get; set; }
        //  Diameter of the arrow shaft
        public double shaft_diameter { get; set; }
        //  Length of the arrow head
        public double head_length { get; set; }
        //  Diameter of the arrow head
        public double head_diameter { get; set; }
        //  Color of the arrow
        public Color color { get; set; }

        public ArrowPrimitive()
        {
            this.pose = new Pose();
            this.shaft_length = 0.0;
            this.shaft_diameter = 0.0;
            this.head_length = 0.0;
            this.head_diameter = 0.0;
            this.color = new Color();
        }

        public ArrowPrimitive(Pose pose, double shaft_length, double shaft_diameter, double head_length, double head_diameter, Color color)
        {
            this.pose = pose;
            this.shaft_length = shaft_length;
            this.shaft_diameter = shaft_diameter;
            this.head_length = head_length;
            this.head_diameter = head_diameter;
            this.color = color;
        }
    }
}
#endif
