/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class CameraCalibration : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/CameraCalibration";

        //  foxglove_msgs/msg/CameraCalibration
        //  Camera calibration parameters
        //  Generated by https://github.com/foxglove/schemas
        //  Timestamp of calibration data
        public Time timestamp { get; set; }
        //  Frame of reference for the camera. The origin of the frame is the optical center of the camera. +x points to the right in the image, +y points down, and +z points into the plane of the image.
        public string frame_id { get; set; }
        //  Image width
        public uint width { get; set; }
        //  Image height
        public uint height { get; set; }
        //  Name of distortion model
        // 
        //  Supported values: `plumb_bob` and `rational_polynomial`
        public string distortion_model { get; set; }
        //  Distortion parameters
        public double[] d { get; set; }
        //  Intrinsic camera matrix (3x3 row-major matrix)
        // 
        //  A 3x3 row-major matrix for the raw (distorted) image.
        // 
        //  Projects 3D points in the camera coordinate frame to 2D pixel coordinates using the focal lengths (fx, fy) and principal point (cx, cy).
        // 
        //  ```
        //      [fx  0 cx]
        //  K = [ 0 fy cy]
        //      [ 0  0  1]
        //  ```
        public double[] k { get; set; }
        //  Rectification matrix (stereo cameras only, 3x3 row-major matrix)
        // 
        //  A rotation matrix aligning the camera coordinate system to the ideal stereo image plane so that epipolar lines in both stereo images are parallel.
        public double[] r { get; set; }
        //  Projection/camera matrix (3x4 row-major matrix)
        // 
        //  ```
        //      [fx'  0  cx' Tx]
        //  P = [ 0  fy' cy' Ty]
        //      [ 0   0   1   0]
        //  ```
        // 
        //  By convention, this matrix specifies the intrinsic (camera) matrix of the processed (rectified) image. That is, the left 3x3 portion is the normal camera intrinsic matrix for the rectified image.
        // 
        //  It projects 3D points in the camera coordinate frame to 2D pixel coordinates using the focal lengths (fx', fy') and principal point (cx', cy') - these may differ from the values in K.
        // 
        //  For monocular cameras, Tx = Ty = 0. Normally, monocular cameras will also have R = the identity and P[1:3,1:3] = K.
        // 
        //  For a stereo pair, the fourth column [Tx Ty 0]' is related to the position of the optical center of the second camera in the first camera's frame. We assume Tz = 0 so both cameras are in the same stereo image plane. The first camera always has Tx = Ty = 0. For the right (second) camera of a horizontal stereo pair, Ty = 0 and Tx = -fx' * B, where B is the baseline between the cameras.
        // 
        //  Given a 3D point [X Y Z]', the projection (x, y) of the point onto the rectified image is given by:
        // 
        //  ```
        //  [u v w]' = P * [X Y Z 1]'
        //         x = u / w
        //         y = v / w
        //  ```
        // 
        //  This holds for both images of a stereo pair.
        public double[] p { get; set; }

        public CameraCalibration()
        {
            this.timestamp = new Time();
            this.frame_id = "";
            this.width = 0;
            this.height = 0;
            this.distortion_model = "";
            this.d = new double[0];
            this.k = new double[9];
            this.r = new double[9];
            this.p = new double[12];
        }

        public CameraCalibration(Time timestamp, string frame_id, uint width, uint height, string distortion_model, double[] d, double[] k, double[] r, double[] p)
        {
            this.timestamp = timestamp;
            this.frame_id = frame_id;
            this.width = width;
            this.height = height;
            this.distortion_model = distortion_model;
            this.d = d;
            this.k = k;
            this.r = r;
            this.p = p;
        }
    }
}
#endif
