/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;
using RosSharp.RosBridgeClient.MessageTypes.Foxglove;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class CircleAnnotation : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/CircleAnnotation";

        //  foxglove_msgs/msg/CircleAnnotation
        //  A circle annotation on a 2D image
        //  Generated by https://github.com/foxglove/schemas
        //  Timestamp of circle
        public Time timestamp { get; set; }
        //  Center of the circle in 2D image coordinates (pixels)
        public Point2 position { get; set; }
        //  Circle diameter in pixels
        public double diameter { get; set; }
        //  Line thickness in pixels
        public double thickness { get; set; }
        //  Fill color
        public Color fill_color { get; set; }
        //  Outline color
        public Color outline_color { get; set; }

        public CircleAnnotation()
        {
            this.timestamp = new Time();
            this.position = new Point2();
            this.diameter = 0.0;
            this.thickness = 0.0;
            this.fill_color = new Color();
            this.outline_color = new Color();
        }

        public CircleAnnotation(Time timestamp, Point2 position, double diameter, double thickness, Color fill_color, Color outline_color)
        {
            this.timestamp = timestamp;
            this.position = position;
            this.diameter = diameter;
            this.thickness = thickness;
            this.fill_color = fill_color;
            this.outline_color = outline_color;
        }
    }
}
#endif
