/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class Color : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/Color";

        //  foxglove_msgs/msg/Color
        //  A color in RGBA format
        //  Generated by https://github.com/foxglove/schemas
        //  Red value between 0 and 1
        public double r { get; set; }
        //  Green value between 0 and 1
        public double g { get; set; }
        //  Blue value between 0 and 1
        public double b { get; set; }
        //  Alpha value between 0 and 1
        public double a { get; set; }

        public Color()
        {
            this.r = 0.0;
            this.g = 0.0;
            this.b = 0.0;
            this.a = 0.0;
        }

        public Color(double r, double g, double b, double a)
        {
            this.r = r;
            this.g = g;
            this.b = b;
            this.a = a;
        }
    }
}
#endif
