/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class CompressedImage : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/CompressedImage";

        //  foxglove_msgs/msg/CompressedImage
        //  A compressed image
        //  Generated by https://github.com/foxglove/schemas
        //  Timestamp of image
        public Time timestamp { get; set; }
        //  Frame of reference for the image. The origin of the frame is the optical center of the camera. +x points to the right in the image, +y points down, and +z points into the plane of the image.
        public string frame_id { get; set; }
        //  Compressed image data
        public byte[] data { get; set; }
        //  Image format
        // 
        //  Supported values: image media types supported by Chrome, such as `webp`, `jpeg`, `png`
        public string format { get; set; }

        public CompressedImage()
        {
            this.timestamp = new Time();
            this.frame_id = "";
            this.data = new byte[0];
            this.format = "";
        }

        public CompressedImage(Time timestamp, string frame_id, byte[] data, string format)
        {
            this.timestamp = timestamp;
            this.frame_id = frame_id;
            this.data = data;
            this.format = format;
        }
    }
}
#endif
