/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class CompressedVideo : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/CompressedVideo";

        //  foxglove_msgs/msg/CompressedVideo
        //  A single frame of a compressed video bitstream
        //  Generated by https://github.com/foxglove/schemas
        //  Timestamp of video frame
        public Time timestamp { get; set; }
        //  Frame of reference for the video.
        // 
        //  The origin of the frame is the optical center of the camera. +x points to the right in the video, +y points down, and +z points into the plane of the video.
        public string frame_id { get; set; }
        //  Compressed video frame data.
        // 
        //  For packet-based video codecs this data must begin and end on packet boundaries (no partial packets), and must contain enough video packets to decode exactly one image (either a keyframe or delta frame). Note: Foxglove Studio does not support video streams that include B frames because they require lookahead.
        public byte[] data { get; set; }
        //  Video format.
        // 
        //  Supported values: `h264` (Annex B formatted data only)
        public string format { get; set; }

        public CompressedVideo()
        {
            this.timestamp = new Time();
            this.frame_id = "";
            this.data = new byte[0];
            this.format = "";
        }

        public CompressedVideo(Time timestamp, string frame_id, byte[] data, string format)
        {
            this.timestamp = timestamp;
            this.frame_id = frame_id;
            this.data = data;
            this.format = format;
        }
    }
}
#endif
