/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Geometry;
using RosSharp.RosBridgeClient.MessageTypes.Foxglove;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class ConePrimitive : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/ConePrimitive";

        //  foxglove_msgs/msg/ConePrimitive
        //  A primitive representing a possibly truncated, possibly elliptic cone or cylinder
        //  Generated by https://github.com/foxglove/schemas
        //  Position of the center of the cone and orientation of the cone. The flat face(s) are perpendicular to the z-axis.
        public Pose pose { get; set; }
        //  Size of the cone's bounding box
        public Vector3 size { get; set; }
        //  0-1, size of the cone's bottom face (min z) relative to the bottom of the bounding box
        public double bottom_scale { get; set; }
        //  0-1, size of the cone's top face (max z) relative to the top of the bounding box
        public double top_scale { get; set; }
        //  Color of the cone
        public Color color { get; set; }

        public ConePrimitive()
        {
            this.pose = new Pose();
            this.size = new Vector3();
            this.bottom_scale = 0.0;
            this.top_scale = 0.0;
            this.color = new Color();
        }

        public ConePrimitive(Pose pose, Vector3 size, double bottom_scale, double top_scale, Color color)
        {
            this.pose = pose;
            this.size = size;
            this.bottom_scale = bottom_scale;
            this.top_scale = top_scale;
            this.color = color;
        }
    }
}
#endif
