/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Geometry;
using RosSharp.RosBridgeClient.MessageTypes.Foxglove;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class CubeAttributes : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/CubeAttributes";

        //  foxglove_msgs/msg/CubeAttributes
        //  Data specifying the visual appearance of a cube or rectangular prism
        //  Generated by https://github.com/foxglove/schemas
        //  Position of the center of the cube and orientation of the cube
        public Pose pose { get; set; }
        //  Size of the cube along each axis
        public Vector3 size { get; set; }
        //  Color of the arrow
        public Color color { get; set; }

        public CubeAttributes()
        {
            this.pose = new Pose();
            this.size = new Vector3();
            this.color = new Color();
        }

        public CubeAttributes(Pose pose, Vector3 size, Color color)
        {
            this.pose = pose;
            this.size = size;
            this.color = color;
        }
    }
}
#endif
