/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;
using RosSharp.RosBridgeClient.MessageTypes.Foxglove;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class CubeListMarker : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/CubeListMarker";

        //  foxglove_msgs/msg/CubeListMarker
        //  A marker representing a list of cubes or rectangular prisms
        //  Generated by https://github.com/foxglove/schemas
        //  Timestamp of the marker
        public Time timestamp { get; set; }
        //  Frame of reference
        public string frame_id { get; set; }
        //  Identifier for the marker. A marker will replace any prior marker on the same topic with the same `id`.
        public string id { get; set; }
        //  Length of time (relative to `timestamp`) after which the marker should be automatically removed. Zero value indicates the marker should remain visible until it is replaced or deleted.
        public Duration lifetime { get; set; }
        //  Whether the marker should keep its location in the fixed frame (false) or follow the frame specified in `frame_id` as it moves relative to the fixed frame (true)
        public bool frame_locked { get; set; }
        //  Additional user-provided metadata associated with the marker. Keys must be unique.
        public KeyValuePair[] metadata { get; set; }
        //  Attributes of each cube
        public CubeAttributes[] attributes { get; set; }

        public CubeListMarker()
        {
            this.timestamp = new Time();
            this.frame_id = "";
            this.id = "";
            this.lifetime = new Duration();
            this.frame_locked = false;
            this.metadata = new KeyValuePair[0];
            this.attributes = new CubeAttributes[0];
        }

        public CubeListMarker(Time timestamp, string frame_id, string id, Duration lifetime, bool frame_locked, KeyValuePair[] metadata, CubeAttributes[] attributes)
        {
            this.timestamp = timestamp;
            this.frame_id = frame_id;
            this.id = id;
            this.lifetime = lifetime;
            this.frame_locked = frame_locked;
            this.metadata = metadata;
            this.attributes = attributes;
        }
    }
}
#endif
