/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;
using RosSharp.RosBridgeClient.MessageTypes.Foxglove;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class CylinderMarker : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/CylinderMarker";

        //  foxglove_msgs/msg/CylinderMarker
        //  A marker representing a cylinder or elliptic cylinder
        //  Generated by https://github.com/foxglove/schemas
        //  Timestamp of the marker
        public Time timestamp { get; set; }
        //  Frame of reference
        public string frame_id { get; set; }
        //  Identifier for the marker. A marker will replace any prior marker on the same topic with the same `id`.
        public string id { get; set; }
        //  Length of time (relative to `timestamp`) after which the marker should be automatically removed. Zero value indicates the marker should remain visible until it is replaced or deleted.
        public Duration lifetime { get; set; }
        //  Whether the marker should keep its location in the fixed frame (false) or follow the frame specified in `frame_id` as it moves relative to the fixed frame (true)
        public bool frame_locked { get; set; }
        //  Additional user-provided metadata associated with the marker. Keys must be unique.
        public KeyValuePair[] metadata { get; set; }
        //  Position of the center of the cylinder and orientation of the cylinder. The cylinder's flat faces are perpendicular to the z-axis.
        public Pose pose { get; set; }
        //  Radius of the cylinder at min z
        public double bottom_radius { get; set; }
        //  Radius of the cylinder at max z
        public double top_radius { get; set; }
        //  Height of the cylinder along the z axis
        public double height { get; set; }
        //  Color of the sphere
        public Color color { get; set; }

        public CylinderMarker()
        {
            this.timestamp = new Time();
            this.frame_id = "";
            this.id = "";
            this.lifetime = new Duration();
            this.frame_locked = false;
            this.metadata = new KeyValuePair[0];
            this.pose = new Pose();
            this.bottom_radius = 0.0;
            this.top_radius = 0.0;
            this.height = 0.0;
            this.color = new Color();
        }

        public CylinderMarker(Time timestamp, string frame_id, string id, Duration lifetime, bool frame_locked, KeyValuePair[] metadata, Pose pose, double bottom_radius, double top_radius, double height, Color color)
        {
            this.timestamp = timestamp;
            this.frame_id = frame_id;
            this.id = id;
            this.lifetime = lifetime;
            this.frame_locked = frame_locked;
            this.metadata = metadata;
            this.pose = pose;
            this.bottom_radius = bottom_radius;
            this.top_radius = top_radius;
            this.height = height;
            this.color = color;
        }
    }
}
#endif
