/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Foxglove;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class FrameTransforms : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/FrameTransforms";

        //  foxglove_msgs/msg/FrameTransforms
        //  An array of FrameTransform messages
        //  Generated by https://github.com/foxglove/schemas
        //  Array of transforms
        public FrameTransform[] transforms { get; set; }

        public FrameTransforms()
        {
            this.transforms = new FrameTransform[0];
        }

        public FrameTransforms(FrameTransform[] transforms)
        {
            this.transforms = transforms;
        }
    }
}
#endif
