/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class FrameTransform : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/FrameTransform";

        //  foxglove_msgs/msg/FrameTransform
        //  A transform between two reference frames in 3D space
        //  Generated by https://github.com/foxglove/schemas
        //  Timestamp of transform
        public Time timestamp { get; set; }
        //  Name of the parent frame
        public string parent_frame_id { get; set; }
        //  Name of the child frame
        public string child_frame_id { get; set; }
        //  Translation component of the transform
        public Vector3 translation { get; set; }
        //  Rotation component of the transform
        public Quaternion rotation { get; set; }

        public FrameTransform()
        {
            this.timestamp = new Time();
            this.parent_frame_id = "";
            this.child_frame_id = "";
            this.translation = new Vector3();
            this.rotation = new Quaternion();
        }

        public FrameTransform(Time timestamp, string parent_frame_id, string child_frame_id, Vector3 translation, Quaternion rotation)
        {
            this.timestamp = timestamp;
            this.parent_frame_id = parent_frame_id;
            this.child_frame_id = child_frame_id;
            this.translation = translation;
            this.rotation = rotation;
        }
    }
}
#endif
