/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class GeoJSON : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/GeoJSON";

        //  foxglove_msgs/msg/GeoJSON
        //  GeoJSON data for annotating maps
        //  Generated by https://github.com/foxglove/schemas
        //  GeoJSON data encoded as a UTF-8 string
        public string geojson { get; set; }

        public GeoJSON()
        {
            this.geojson = "";
        }

        public GeoJSON(string geojson)
        {
            this.geojson = geojson;
        }
    }
}
#endif
