/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;
using RosSharp.RosBridgeClient.MessageTypes.Foxglove;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class Grid : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/Grid";

        //  foxglove_msgs/msg/Grid
        //  A 2D grid of data
        //  Generated by https://github.com/foxglove/schemas
        //  Timestamp of grid
        public Time timestamp { get; set; }
        //  Frame of reference
        public string frame_id { get; set; }
        //  Origin of grid's corner relative to frame of reference; grid is positioned in the x-y plane relative to this origin
        public Pose pose { get; set; }
        //  Number of grid columns
        public uint column_count { get; set; }
        //  Size of single grid cell along x and y axes, relative to `pose`
        public Vector2 cell_size { get; set; }
        //  Number of bytes between rows in `data`
        public uint row_stride { get; set; }
        //  Number of bytes between cells within a row in `data`
        public uint cell_stride { get; set; }
        //  Fields in `data`. `red`, `green`, `blue`, and `alpha` are optional for customizing the grid's color.
        public PackedElementField[] fields { get; set; }
        //  Grid cell data, interpreted using `fields`, in row-major (y-major) order
        public byte[] data { get; set; }

        public Grid()
        {
            this.timestamp = new Time();
            this.frame_id = "";
            this.pose = new Pose();
            this.column_count = 0;
            this.cell_size = new Vector2();
            this.row_stride = 0;
            this.cell_stride = 0;
            this.fields = new PackedElementField[0];
            this.data = new byte[0];
        }

        public Grid(Time timestamp, string frame_id, Pose pose, uint column_count, Vector2 cell_size, uint row_stride, uint cell_stride, PackedElementField[] fields, byte[] data)
        {
            this.timestamp = timestamp;
            this.frame_id = frame_id;
            this.pose = pose;
            this.column_count = column_count;
            this.cell_size = cell_size;
            this.row_stride = row_stride;
            this.cell_stride = cell_stride;
            this.fields = fields;
            this.data = data;
        }
    }
}
#endif
