/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Visualization;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class ImageMarkerArray : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/ImageMarkerArray";

        public ImageMarker[] markers { get; set; }

        public ImageMarkerArray()
        {
            this.markers = new ImageMarker[0];
        }

        public ImageMarkerArray(ImageMarker[] markers)
        {
            this.markers = markers;
        }
    }
}
#endif
