/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Foxglove;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class ImageAnnotations : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/ImageAnnotations";

        //  foxglove_msgs/msg/ImageAnnotations
        //  Array of annotations for a 2D image
        //  Generated by https://github.com/foxglove/schemas
        //  Circle annotations
        public CircleAnnotation[] circles { get; set; }
        //  Points annotations
        public PointsAnnotation[] points { get; set; }
        //  Text annotations
        public TextAnnotation[] texts { get; set; }

        public ImageAnnotations()
        {
            this.circles = new CircleAnnotation[0];
            this.points = new PointsAnnotation[0];
            this.texts = new TextAnnotation[0];
        }

        public ImageAnnotations(CircleAnnotation[] circles, PointsAnnotation[] points, TextAnnotation[] texts)
        {
            this.circles = circles;
            this.points = points;
            this.texts = texts;
        }
    }
}
#endif
