/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class KeyValuePair : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/KeyValuePair";

        //  foxglove_msgs/msg/KeyValuePair
        //  A key with its associated value
        //  Generated by https://github.com/foxglove/schemas
        //  Key
        public string key { get; set; }
        //  Value
        public string @value { get; set; }

        public KeyValuePair()
        {
            this.key = "";
            this.@value = "";
        }

        public KeyValuePair(string key, string @value)
        {
            this.key = key;
            this.@value = @value;
        }
    }
}
#endif
