/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class LaserScan : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/LaserScan";

        //  foxglove_msgs/msg/LaserScan
        //  A single scan from a planar laser range-finder
        //  Generated by https://github.com/foxglove/schemas
        //  Timestamp of scan
        public Time timestamp { get; set; }
        //  Frame of reference
        public string frame_id { get; set; }
        //  Origin of scan relative to frame of reference; points are positioned in the x-y plane relative to this origin; angles are interpreted as counterclockwise rotations around the z axis with 0 rad being in the +x direction
        public Pose pose { get; set; }
        //  Bearing of first point, in radians
        public double start_angle { get; set; }
        //  Bearing of last point, in radians
        public double end_angle { get; set; }
        //  Distance of detections from origin; assumed to be at equally-spaced angles between `start_angle` and `end_angle`
        public double[] ranges { get; set; }
        //  Intensity of detections
        public double[] intensities { get; set; }

        public LaserScan()
        {
            this.timestamp = new Time();
            this.frame_id = "";
            this.pose = new Pose();
            this.start_angle = 0.0;
            this.end_angle = 0.0;
            this.ranges = new double[0];
            this.intensities = new double[0];
        }

        public LaserScan(Time timestamp, string frame_id, Pose pose, double start_angle, double end_angle, double[] ranges, double[] intensities)
        {
            this.timestamp = timestamp;
            this.frame_id = frame_id;
            this.pose = pose;
            this.start_angle = start_angle;
            this.end_angle = end_angle;
            this.ranges = ranges;
            this.intensities = intensities;
        }
    }
}
#endif
