/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Geometry;
using RosSharp.RosBridgeClient.MessageTypes.Foxglove;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class LineMarker : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/LineMarker";

        //  foxglove_msgs/msg/LineMarker
        //  A marker representing a series of points connected by lines
        //  Generated by https://github.com/foxglove/schemas
        //  0-1, 1-2, ..., (n-1)-n
        public const byte LINE_STRIP = 0;
        //  0-1, 1-2, ..., (n-1)-n, n-0
        public const byte LINE_LOOP = 1;
        //  0-1, 2-3, 4-5, ...
        public const byte LINE_LIST = 2;
        //  Drawing primitive to use for lines
        public byte type { get; set; }
        //  Origin of lines relative to reference frame
        public Pose pose { get; set; }
        //  Line thickness
        public double thickness { get; set; }
        //  Indicates whether `thickness` is a fixed size in screen pixels (true), or specified in world coordinates and scales with distance from the camera (false)
        public bool scale_invariant { get; set; }
        //  Points along the line
        public Point[] points { get; set; }
        //  Solid color to use for the whole line. One of `color` or `colors` must be provided.
        public Color color { get; set; }
        //  Per-point colors (if specified, must have the same length as `points`). One of `color` or `colors` must be provided.
        public Color[] colors { get; set; }
        //  Indices into the `points` and `colors` attribute arrays, which can be used to avoid duplicating attribute data.
        // 
        //  If omitted or empty, indexing will not be used. This default behavior is equivalent to specifying [0, 1, ..., N-1] for the indices (where N is the number of `points` provided).
        public uint[] indices { get; set; }

        public LineMarker()
        {
            this.type = 0;
            this.pose = new Pose();
            this.thickness = 0.0;
            this.scale_invariant = false;
            this.points = new Point[0];
            this.color = new Color();
            this.colors = new Color[0];
            this.indices = new uint[0];
        }

        public LineMarker(byte type, Pose pose, double thickness, bool scale_invariant, Point[] points, Color color, Color[] colors, uint[] indices)
        {
            this.type = type;
            this.pose = pose;
            this.thickness = thickness;
            this.scale_invariant = scale_invariant;
            this.points = points;
            this.color = color;
            this.colors = colors;
            this.indices = indices;
        }
    }
}
#endif
