/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class LocationFix : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/LocationFix";

        //  foxglove_msgs/msg/LocationFix
        //  A navigation satellite fix for any Global Navigation Satellite System
        //  Generated by https://github.com/foxglove/schemas
        //  Timestamp of the message
        public Time timestamp { get; set; }
        //  Frame for the sensor. Latitude and longitude readings are at the origin of the frame.
        public string frame_id { get; set; }
        //  Latitude in degrees
        public double latitude { get; set; }
        //  Longitude in degrees
        public double longitude { get; set; }
        //  Altitude in meters
        public double altitude { get; set; }
        //  Position covariance (m^2) defined relative to a tangential plane through the reported position. The components are East, North, and Up (ENU), in row-major order.
        public double[] position_covariance { get; set; }
        public const byte UNKNOWN = 0;
        public const byte APPROXIMATED = 1;
        public const byte DIAGONAL_KNOWN = 2;
        public const byte KNOWN = 3;
        //  If `position_covariance` is available, `position_covariance_type` must be set to indicate the type of covariance.
        public byte position_covariance_type { get; set; }

        public LocationFix()
        {
            this.timestamp = new Time();
            this.frame_id = "";
            this.latitude = 0.0;
            this.longitude = 0.0;
            this.altitude = 0.0;
            this.position_covariance = new double[9];
            this.position_covariance_type = 0;
        }

        public LocationFix(Time timestamp, string frame_id, double latitude, double longitude, double altitude, double[] position_covariance, byte position_covariance_type)
        {
            this.timestamp = timestamp;
            this.frame_id = frame_id;
            this.latitude = latitude;
            this.longitude = longitude;
            this.altitude = altitude;
            this.position_covariance = position_covariance;
            this.position_covariance_type = position_covariance_type;
        }
    }
}
#endif
