/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class Log : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/Log";

        //  foxglove_msgs/msg/Log
        //  A log message
        //  Generated by https://github.com/foxglove/schemas
        //  Timestamp of log message
        public Time timestamp { get; set; }
        public const byte UNKNOWN = 0;
        public const byte DEBUG = 1;
        public const byte INFO = 2;
        public const byte WARNING = 3;
        public const byte ERROR = 4;
        public const byte FATAL = 5;
        //  Log level
        public byte level { get; set; }
        //  Log message
        public string message { get; set; }
        //  Process or node name
        public string name { get; set; }
        //  Filename
        public string @file { get; set; }
        //  Line number in the file
        public uint line { get; set; }

        public Log()
        {
            this.timestamp = new Time();
            this.level = 0;
            this.message = "";
            this.name = "";
            this.@file = "";
            this.line = 0;
        }

        public Log(Time timestamp, byte level, string message, string name, string @file, uint line)
        {
            this.timestamp = timestamp;
            this.level = level;
            this.message = message;
            this.name = name;
            this.@file = @file;
            this.line = line;
        }
    }
}
#endif
