/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Foxglove;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class Markers : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/Markers";

        //  foxglove_msgs/msg/Markers
        //  A list of any number or type of markers
        //  Generated by https://github.com/foxglove/schemas
        //  Marker deletion actions
        public MarkerDeletion[] deletions { get; set; }
        //  Arrow markers
        public ArrowMarker[] arrows { get; set; }
        //  Cube list markers
        public CubeListMarker[] cubes { get; set; }
        //  Sphere list markers
        public SphereListMarker[] spheres { get; set; }
        //  Cone list markers
        public ConeListMarker[] cones { get; set; }
        //  Line markers
        public LineMarker[] lines { get; set; }
        //  Triangle list markers
        public TriangleListMarker[] triangles { get; set; }
        //  Text markers
        public TextMarker[] texts { get; set; }
        //  Model markers
        public ModelMarker[] models { get; set; }

        public Markers()
        {
            this.deletions = new MarkerDeletion[0];
            this.arrows = new ArrowMarker[0];
            this.cubes = new CubeListMarker[0];
            this.spheres = new SphereListMarker[0];
            this.cones = new ConeListMarker[0];
            this.lines = new LineMarker[0];
            this.triangles = new TriangleListMarker[0];
            this.texts = new TextMarker[0];
            this.models = new ModelMarker[0];
        }

        public Markers(MarkerDeletion[] deletions, ArrowMarker[] arrows, CubeListMarker[] cubes, SphereListMarker[] spheres, ConeListMarker[] cones, LineMarker[] lines, TriangleListMarker[] triangles, TextMarker[] texts, ModelMarker[] models)
        {
            this.deletions = deletions;
            this.arrows = arrows;
            this.cubes = cubes;
            this.spheres = spheres;
            this.cones = cones;
            this.lines = lines;
            this.triangles = triangles;
            this.texts = texts;
            this.models = models;
        }
    }
}
#endif
