/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Geometry;
using RosSharp.RosBridgeClient.MessageTypes.Foxglove;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class ModelMarker : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/ModelMarker";

        //  foxglove_msgs/msg/ModelMarker
        //  A marker representing a 3D model
        //  Generated by https://github.com/foxglove/schemas
        //  Origin of model relative to reference frame
        public Pose pose { get; set; }
        //  Scale factor to apply to the model along each axis
        public Vector3 scale { get; set; }
        //  Solid color to use for the whole model. If `use_embedded_materials` is true, this color is blended on top of the embedded material color.
        public Color color { get; set; }
        //  Whether to use materials embedded in the model, or only the `color`
        public bool use_embedded_materials { get; set; }
        //  URL pointing to model file. Either `url` or `mime_type` and `data` should be provided.
        public string url { get; set; }
        //  MIME type of embedded model (e.g. `model/gltf-binary`). Either `url` or `mime_type` and `data` should be provided.
        public string mime_type { get; set; }
        //  Embedded model. Either `url` or `mime_type` and `data` should be provided.
        public byte[] data { get; set; }

        public ModelMarker()
        {
            this.pose = new Pose();
            this.scale = new Vector3();
            this.color = new Color();
            this.use_embedded_materials = false;
            this.url = "";
            this.mime_type = "";
            this.data = new byte[0];
        }

        public ModelMarker(Pose pose, Vector3 scale, Color color, bool use_embedded_materials, string url, string mime_type, byte[] data)
        {
            this.pose = pose;
            this.scale = scale;
            this.color = color;
            this.use_embedded_materials = use_embedded_materials;
            this.url = url;
            this.mime_type = mime_type;
            this.data = data;
        }
    }
}
#endif
