/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class PackedElementField : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/PackedElementField";

        //  foxglove_msgs/msg/PackedElementField
        //  A field present within each element in a byte array of packed elements.
        //  Generated by https://github.com/foxglove/schemas
        //  Name of the field
        public string name { get; set; }
        //  Byte offset from start of data buffer
        public uint offset { get; set; }
        public const byte UNKNOWN = 0;
        public const byte UINT8 = 1;
        public const byte INT8 = 2;
        public const byte UINT16 = 3;
        public const byte INT16 = 4;
        public const byte UINT32 = 5;
        public const byte INT32 = 6;
        public const byte FLOAT32 = 7;
        public const byte FLOAT64 = 8;
        //  Type of data in the field. Integers are stored using little-endian byte order.
        public byte type { get; set; }

        public PackedElementField()
        {
            this.name = "";
            this.offset = 0;
            this.type = 0;
        }

        public PackedElementField(string name, uint offset, byte type)
        {
            this.name = name;
            this.offset = offset;
            this.type = type;
        }
    }
}
#endif
