/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class Point2 : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/Point2";

        //  foxglove_msgs/msg/Point2
        //  A point representing a position in 2D space
        //  Generated by https://github.com/foxglove/schemas
        //  x coordinate position
        public double x { get; set; }
        //  y coordinate position
        public double y { get; set; }

        public Point2()
        {
            this.x = 0.0;
            this.y = 0.0;
        }

        public Point2(double x, double y)
        {
            this.x = x;
            this.y = y;
        }
    }
}
#endif
