/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;
using RosSharp.RosBridgeClient.MessageTypes.Foxglove;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class PointsAnnotation : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/PointsAnnotation";

        //  foxglove_msgs/msg/PointsAnnotation
        //  An array of points on a 2D image
        //  Generated by https://github.com/foxglove/schemas
        //  Timestamp of annotation
        public Time timestamp { get; set; }
        public const byte UNKNOWN = 0;
        //  Individual points: 0, 1, 2, ...
        public const byte POINTS = 1;
        //  Closed polygon: 0-1, 1-2, ..., (n-1)-n, n-0
        public const byte LINE_LOOP = 2;
        //  Connected line segments: 0-1, 1-2, ..., (n-1)-n
        public const byte LINE_STRIP = 3;
        //  Individual line segments: 0-1, 2-3, 4-5, ...
        public const byte LINE_LIST = 4;
        //  Type of points annotation to draw
        public byte type { get; set; }
        //  Points in 2D image coordinates (pixels)
        public Point2[] points { get; set; }
        //  Outline color
        public Color outline_color { get; set; }
        //  Per-point colors, if `type` is `POINTS`, or per-segment stroke colors, if `type` is `LINE_LIST`, `LINE_STRIP` or `LINE_LOOP`.
        public Color[] outline_colors { get; set; }
        //  Fill color
        public Color fill_color { get; set; }
        //  Stroke thickness in pixels
        public double thickness { get; set; }

        public PointsAnnotation()
        {
            this.timestamp = new Time();
            this.type = 0;
            this.points = new Point2[0];
            this.outline_color = new Color();
            this.outline_colors = new Color[0];
            this.fill_color = new Color();
            this.thickness = 0.0;
        }

        public PointsAnnotation(Time timestamp, byte type, Point2[] points, Color outline_color, Color[] outline_colors, Color fill_color, double thickness)
        {
            this.timestamp = timestamp;
            this.type = type;
            this.points = points;
            this.outline_color = outline_color;
            this.outline_colors = outline_colors;
            this.fill_color = fill_color;
            this.thickness = thickness;
        }
    }
}
#endif
