/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;
using RosSharp.RosBridgeClient.MessageTypes.Foxglove;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class PointCloud : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/PointCloud";

        //  foxglove_msgs/msg/PointCloud
        //  A collection of N-dimensional points, which may contain additional fields with information like normals, intensity, etc.
        //  Generated by https://github.com/foxglove/schemas
        //  Timestamp of point cloud
        public Time timestamp { get; set; }
        //  Frame of reference
        public string frame_id { get; set; }
        //  The origin of the point cloud relative to the frame of reference
        public Pose pose { get; set; }
        //  Number of bytes between points in the `data`
        public uint point_stride { get; set; }
        //  Fields in `data`. At least 2 coordinate fields from `x`, `y`, and `z` are required for each point's position; `red`, `green`, `blue`, and `alpha` are optional for customizing each point's color.
        public PackedElementField[] fields { get; set; }
        //  Point data, interpreted using `fields`
        public byte[] data { get; set; }

        public PointCloud()
        {
            this.timestamp = new Time();
            this.frame_id = "";
            this.pose = new Pose();
            this.point_stride = 0;
            this.fields = new PackedElementField[0];
            this.data = new byte[0];
        }

        public PointCloud(Time timestamp, string frame_id, Pose pose, uint point_stride, PackedElementField[] fields, byte[] data)
        {
            this.timestamp = timestamp;
            this.frame_id = frame_id;
            this.pose = pose;
            this.point_stride = point_stride;
            this.fields = fields;
            this.data = data;
        }
    }
}
#endif
