/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class PoseInFrame : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/PoseInFrame";

        //  foxglove_msgs/msg/PoseInFrame
        //  A timestamped pose for an object or reference frame in 3D space
        //  Generated by https://github.com/foxglove/schemas
        //  Timestamp of pose
        public Time timestamp { get; set; }
        //  Frame of reference for pose position and orientation
        public string frame_id { get; set; }
        //  Pose in 3D space
        public Pose pose { get; set; }

        public PoseInFrame()
        {
            this.timestamp = new Time();
            this.frame_id = "";
            this.pose = new Pose();
        }

        public PoseInFrame(Time timestamp, string frame_id, Pose pose)
        {
            this.timestamp = timestamp;
            this.frame_id = frame_id;
            this.pose = pose;
        }
    }
}
#endif
