/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class PrimitiveDeletion : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/PrimitiveDeletion";

        //  foxglove_msgs/msg/PrimitiveDeletion
        //  Command to remove previously published markers
        //  Generated by https://github.com/foxglove/schemas
        //  Timestamp of the marker. Only matching markers earlier than this timestamp will be deleted.
        public Time timestamp { get; set; }
        public const byte MATCHING_ID = 0;
        public const byte ALL = 1;
        //  Type of deletion action to perform
        public byte type { get; set; }
        //  Numeric identifier which must match if `kind` is `MATCHING_ID`.
        public string id { get; set; }

        public PrimitiveDeletion()
        {
            this.timestamp = new Time();
            this.type = 0;
            this.id = "";
        }

        public PrimitiveDeletion(Time timestamp, byte type, string id)
        {
            this.timestamp = timestamp;
            this.type = type;
            this.id = id;
        }
    }
}
#endif
