/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class RawImage : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/RawImage";

        //  foxglove_msgs/msg/RawImage
        //  A raw image
        //  Generated by https://github.com/foxglove/schemas
        //  Timestamp of image
        public Time timestamp { get; set; }
        //  Frame of reference for the image. The origin of the frame is the optical center of the camera. +x points to the right in the image, +y points down, and +z points into the plane of the image.
        public string frame_id { get; set; }
        //  Image width
        public uint width { get; set; }
        //  Image height
        public uint height { get; set; }
        //  Encoding of the raw image data
        // 
        //  Supported values: `8UC1`, `8UC3`, `16UC1`, `32FC1`, `bayer_bggr8`, `bayer_gbrg8`, `bayer_grbg8`, `bayer_rggb8`, `bgr8`, `bgra8`, `mono8`, `mono16`, `rgb8`, `rgba8`, `uyvy` or `yuv422`, `yuyv` or `yuv422_yuy2`
        public string encoding { get; set; }
        //  Byte length of a single row
        public uint step { get; set; }
        //  Raw image data
        public byte[] data { get; set; }

        public RawImage()
        {
            this.timestamp = new Time();
            this.frame_id = "";
            this.width = 0;
            this.height = 0;
            this.encoding = "";
            this.step = 0;
            this.data = new byte[0];
        }

        public RawImage(Time timestamp, string frame_id, uint width, uint height, string encoding, uint step, byte[] data)
        {
            this.timestamp = timestamp;
            this.frame_id = frame_id;
            this.width = width;
            this.height = height;
            this.encoding = encoding;
            this.step = step;
            this.data = data;
        }
    }
}
#endif
