/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Foxglove;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class SceneEntities : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/SceneEntities";

        //  foxglove_msgs/msg/SceneEntities
        //  An update to the entities displayed in a 3D scene
        //  Generated by https://github.com/foxglove/schemas
        //  Scene entities to delete
        public SceneEntityDeletion[] deletions { get; set; }
        //  Scene entities to add or replace
        public SceneEntity[] entities { get; set; }

        public SceneEntities()
        {
            this.deletions = new SceneEntityDeletion[0];
            this.entities = new SceneEntity[0];
        }

        public SceneEntities(SceneEntityDeletion[] deletions, SceneEntity[] entities)
        {
            this.deletions = deletions;
            this.entities = entities;
        }
    }
}
#endif
