/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;
using RosSharp.RosBridgeClient.MessageTypes.Foxglove;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class SceneEntity : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/SceneEntity";

        //  foxglove_msgs/msg/SceneEntity
        //  A visual element in a 3D scene. An entity may be composed of multiple primitives which all share the same frame of reference.
        //  Generated by https://github.com/foxglove/schemas
        //  Timestamp of the entity
        public Time timestamp { get; set; }
        //  Frame of reference
        public string frame_id { get; set; }
        //  Identifier for the entity. A entity will replace any prior entity on the same topic with the same `id`.
        public string id { get; set; }
        //  Length of time (relative to `timestamp`) after which the entity should be automatically removed. Zero value indicates the entity should remain visible until it is replaced or deleted.
        public Duration lifetime { get; set; }
        //  Whether the entity should keep its location in the fixed frame (false) or follow the frame specified in `frame_id` as it moves relative to the fixed frame (true)
        public bool frame_locked { get; set; }
        //  Additional user-provided metadata associated with the entity. Keys must be unique.
        public KeyValuePair[] metadata { get; set; }
        //  Arrow primitives
        public ArrowPrimitive[] arrows { get; set; }
        //  Cube primitives
        public CubePrimitive[] cubes { get; set; }
        //  Sphere primitives
        public SpherePrimitive[] spheres { get; set; }
        //  Cylinder primitives
        public CylinderPrimitive[] cylinders { get; set; }
        //  Line primitives
        public LinePrimitive[] lines { get; set; }
        //  Triangle list primitives
        public TriangleListPrimitive[] triangles { get; set; }
        //  Text primitives
        public TextPrimitive[] texts { get; set; }
        //  Model primitives
        public ModelPrimitive[] models { get; set; }

        public SceneEntity()
        {
            this.timestamp = new Time();
            this.frame_id = "";
            this.id = "";
            this.lifetime = new Duration();
            this.frame_locked = false;
            this.metadata = new KeyValuePair[0];
            this.arrows = new ArrowPrimitive[0];
            this.cubes = new CubePrimitive[0];
            this.spheres = new SpherePrimitive[0];
            this.cylinders = new CylinderPrimitive[0];
            this.lines = new LinePrimitive[0];
            this.triangles = new TriangleListPrimitive[0];
            this.texts = new TextPrimitive[0];
            this.models = new ModelPrimitive[0];
        }

        public SceneEntity(Time timestamp, string frame_id, string id, Duration lifetime, bool frame_locked, KeyValuePair[] metadata, ArrowPrimitive[] arrows, CubePrimitive[] cubes, SpherePrimitive[] spheres, CylinderPrimitive[] cylinders, LinePrimitive[] lines, TriangleListPrimitive[] triangles, TextPrimitive[] texts, ModelPrimitive[] models)
        {
            this.timestamp = timestamp;
            this.frame_id = frame_id;
            this.id = id;
            this.lifetime = lifetime;
            this.frame_locked = frame_locked;
            this.metadata = metadata;
            this.arrows = arrows;
            this.cubes = cubes;
            this.spheres = spheres;
            this.cylinders = cylinders;
            this.lines = lines;
            this.triangles = triangles;
            this.texts = texts;
            this.models = models;
        }
    }
}
#endif
