/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class SceneEntityDeletion : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/SceneEntityDeletion";

        //  foxglove_msgs/msg/SceneEntityDeletion
        //  Command to remove previously published entities
        //  Generated by https://github.com/foxglove/schemas
        //  Timestamp of the deletion. Only matching entities earlier than this timestamp will be deleted.
        public Time timestamp { get; set; }
        //  Delete the existing entity on the same topic that has the provided `id`
        public const byte MATCHING_ID = 0;
        //  Delete all existing entities on the same topic
        public const byte ALL = 1;
        //  Type of deletion action to perform
        public byte type { get; set; }
        //  Identifier which must match if `type` is `MATCHING_ID`.
        public string id { get; set; }

        public SceneEntityDeletion()
        {
            this.timestamp = new Time();
            this.type = 0;
            this.id = "";
        }

        public SceneEntityDeletion(Time timestamp, byte type, string id)
        {
            this.timestamp = timestamp;
            this.type = type;
            this.id = id;
        }
    }
}
#endif
