/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Geometry;
using RosSharp.RosBridgeClient.MessageTypes.Foxglove;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class TextMarker : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/TextMarker";

        //  foxglove_msgs/msg/TextMarker
        //  A marker representing a text label
        //  Generated by https://github.com/foxglove/schemas
        //  Position of the center of the text box and orientation of the text. Identity orientation means the text is oriented in the xy-plane and flows from -x to +x.
        public Pose pose { get; set; }
        //  Whether the text should respect `pose.orientation` (false) or always face the camera (true)
        public bool billboard { get; set; }
        //  Font size (height of one line of text)
        public double font_size { get; set; }
        //  Indicates whether `font_size` is a fixed size in screen pixels (true), or specified in world coordinates and scales with distance from the camera (false)
        public bool scale_invariant { get; set; }
        //  Color of the text
        public Color color { get; set; }
        //  Text
        public string text { get; set; }

        public TextMarker()
        {
            this.pose = new Pose();
            this.billboard = false;
            this.font_size = 0.0;
            this.scale_invariant = false;
            this.color = new Color();
            this.text = "";
        }

        public TextMarker(Pose pose, bool billboard, double font_size, bool scale_invariant, Color color, string text)
        {
            this.pose = pose;
            this.billboard = billboard;
            this.font_size = font_size;
            this.scale_invariant = scale_invariant;
            this.color = color;
            this.text = text;
        }
    }
}
#endif
