/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;
using RosSharp.RosBridgeClient.MessageTypes.Foxglove;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class TextAnnotation : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/TextAnnotation";

        //  foxglove_msgs/msg/TextAnnotation
        //  A text label on a 2D image
        //  Generated by https://github.com/foxglove/schemas
        //  Timestamp of annotation
        public Time timestamp { get; set; }
        //  Bottom-left origin of the text label in 2D image coordinates (pixels)
        public Point2 position { get; set; }
        //  Text to display
        public string text { get; set; }
        //  Font size in pixels
        public double font_size { get; set; }
        //  Text color
        public Color text_color { get; set; }
        //  Background fill color
        public Color background_color { get; set; }

        public TextAnnotation()
        {
            this.timestamp = new Time();
            this.position = new Point2();
            this.text = "";
            this.font_size = 0.0;
            this.text_color = new Color();
            this.background_color = new Color();
        }

        public TextAnnotation(Time timestamp, Point2 position, string text, double font_size, Color text_color, Color background_color)
        {
            this.timestamp = timestamp;
            this.position = position;
            this.text = text;
            this.font_size = font_size;
            this.text_color = text_color;
            this.background_color = background_color;
        }
    }
}
#endif
