/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class Transform : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/Transform";

        //  Generated from Transform by @foxglove/schemas
        //  Transform time
        public Time timestamp { get; set; }
        //  Translation component of the transform
        public Vector3 translation { get; set; }
        //  Rotation component of the transform
        public Quaternion rotation { get; set; }

        public Transform()
        {
            this.timestamp = new Time();
            this.translation = new Vector3();
            this.rotation = new Quaternion();
        }

        public Transform(Time timestamp, Vector3 translation, Quaternion rotation)
        {
            this.timestamp = timestamp;
            this.translation = translation;
            this.rotation = rotation;
        }
    }
}
#endif
