/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;
using RosSharp.RosBridgeClient.MessageTypes.Foxglove;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Foxglove
{
    public class TrianglesMarker : Message
    {
        public const string RosMessageName = "foxglove_msgs/msg/TrianglesMarker";

        //  foxglove_msgs/msg/TrianglesMarker
        //  A marker representing a set of triangles or a surface tiled by triangles
        //  Generated by https://github.com/foxglove/schemas
        //  Timestamp of the marker
        public Time timestamp { get; set; }
        //  Frame of reference
        public string frame_id { get; set; }
        //  Identifier for the marker. A marker will replace any prior marker on the same topic with the same `id`.
        public string id { get; set; }
        //  Length of time (relative to `timestamp`) after which the marker should be automatically removed. Zero value indicates the marker should remain visible until it is replaced or deleted.
        public Duration lifetime { get; set; }
        //  Whether the marker should keep its location in the fixed frame (false) or follow the frame specified in `frame_id` as it moves relative to the fixed frame (true)
        public bool frame_locked { get; set; }
        //  Additional user-provided metadata associated with the marker. Keys must be unique.
        public KeyValuePair[] metadata { get; set; }
        //  Origin of triangles relative to reference frame
        public Pose pose { get; set; }
        //  Vertices to use for triangles, interpreted as a list of triples (0-1-2, 3-4-5, ...)
        public Point[] points { get; set; }
        //  Solid color to use for the whole shape. One of `color` or `colors` must be provided.
        public Color color { get; set; }
        //  Per-vertex colors (if specified, must have the same length as `points`). One of `color` or `colors` should be provided.
        public Color[] colors { get; set; }
        //  Indices into the `points` and `colors` attribute arrays, which can be used to avoid duplicating attribute data.
        // 
        //  If omitted or empty, indexing will not be used. This default behavior is equivalent to specifying [0, 1, ..., N-1] for the indices (where N is the number of `points` provided).
        public uint[] indices { get; set; }

        public TrianglesMarker()
        {
            this.timestamp = new Time();
            this.frame_id = "";
            this.id = "";
            this.lifetime = new Duration();
            this.frame_locked = false;
            this.metadata = new KeyValuePair[0];
            this.pose = new Pose();
            this.points = new Point[0];
            this.color = new Color();
            this.colors = new Color[0];
            this.indices = new uint[0];
        }

        public TrianglesMarker(Time timestamp, string frame_id, string id, Duration lifetime, bool frame_locked, KeyValuePair[] metadata, Pose pose, Point[] points, Color color, Color[] colors, uint[] indices)
        {
            this.timestamp = timestamp;
            this.frame_id = frame_id;
            this.id = id;
            this.lifetime = lifetime;
            this.frame_locked = frame_locked;
            this.metadata = metadata;
            this.pose = pose;
            this.points = points;
            this.color = color;
            this.colors = colors;
            this.indices = indices;
        }
    }
}
#endif
