/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Lifecycle;

namespace RosSharp.RosBridgeClient.MessageTypes.ControllerManager
{
    public class HardwareComponentState : Message
    {
        public const string RosMessageName = "controller_manager_msgs/msg/HardwareComponentState";

        public string name { get; set; }
        public string type { get; set; }
        public string class_type { get; set; }
        // DEPRECATED
        public string plugin_name { get; set; }
        public State state { get; set; }
        public HardwareInterface[] command_interfaces { get; set; }
        public HardwareInterface[] state_interfaces { get; set; }

        public HardwareComponentState()
        {
            this.name = "";
            this.type = "";
            this.class_type = "";
            this.plugin_name = "";
            this.state = new State();
            this.command_interfaces = new HardwareInterface[0];
            this.state_interfaces = new HardwareInterface[0];
        }

        public HardwareComponentState(string name, string type, string class_type, string plugin_name, State state, HardwareInterface[] command_interfaces, HardwareInterface[] state_interfaces)
        {
            this.name = name;
            this.type = type;
            this.class_type = class_type;
            this.plugin_name = plugin_name;
            this.state = state;
            this.command_interfaces = command_interfaces;
            this.state_interfaces = state_interfaces;
        }
    }
}
#endif
