/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.ControllerManager
{
    public class HardwareInterface : Message
    {
        public const string RosMessageName = "controller_manager_msgs/msg/HardwareInterface";

        public string name { get; set; }
        public bool is_available { get; set; }
        public bool is_claimed { get; set; }

        public HardwareInterface()
        {
            this.name = "";
            this.is_available = false;
            this.is_claimed = false;
        }

        public HardwareInterface(string name, bool is_available, bool is_claimed)
        {
            this.name = name;
            this.is_available = is_available;
            this.is_claimed = is_claimed;
        }
    }
}
#endif
