/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.RmwDdsCommon
{
    public class Gid : Message
    {
        public const string RosMessageName = "rmw_dds_common/msg/Gid";

        public byte[] data { get; set; }

        public Gid()
        {
            this.data = new byte[16];
        }

        public Gid(byte[] data)
        {
            this.data = data;
        }
    }
}
#endif
