/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.TypeDescriptionInterfaces
{
    public class Field : Message
    {
        public const string RosMessageName = "type_description_interfaces/msg/Field";

        //  Represents a single field in a type.
        //  Name of the field.
        public string name { get; set; }
        //  Type of the field, including details about the type like length, nested name, etc.
        public FieldType type { get; set; }
        //  Literal default value of the field as a string, as it appeared in the original
        //  message description file, whether that be .msg/.srv/.action or .idl.
        public string default_value { get; set; }

        public Field()
        {
            this.name = "";
            this.type = new FieldType();
            this.default_value = "";
        }

        public Field(string name, FieldType type, string default_value)
        {
            this.name = name;
            this.type = type;
            this.default_value = default_value;
        }
    }
}
#endif
