/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.TypeDescriptionInterfaces
{
    public class IndividualTypeDescription : Message
    {
        public const string RosMessageName = "type_description_interfaces/msg/IndividualTypeDescription";

        //  Represents a single type, without the types it references, if any.
        //  Name of the type.
        //  This is limited to 255 characters.
        //  TODO(wjwwood): this 255 character limit was chosen due to this being the limit
        //    for DDSI-RTPS based middlewares, which is the most commonly used right now.
        //    We lack a ROS 2 specific limit in our design documents, but we should update
        //    this and/or link to the design doc when that is available.
        public string type_name { get; set; }
        //  Fields of the type.
        public Field[] fields { get; set; }

        public IndividualTypeDescription()
        {
            this.type_name = "";
            this.fields = new Field[0];
        }

        public IndividualTypeDescription(string type_name, Field[] fields)
        {
            this.type_name = type_name;
            this.fields = fields;
        }
    }
}
#endif
