/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.TypeDescriptionInterfaces
{
    public class KeyValue : Message
    {
        public const string RosMessageName = "type_description_interfaces/msg/KeyValue";

        //  Represents an arbitrary key-value pair for application-specific information.
        public string key { get; set; }
        public string @value { get; set; }

        public KeyValue()
        {
            this.key = "";
            this.@value = "";
        }

        public KeyValue(string key, string @value)
        {
            this.key = key;
            this.@value = @value;
        }
    }
}
#endif
