/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Actuator
{
    public class ActuatorsNormalized : Message
    {
        public const string RosMessageName = "actuator_msgs/msg/ActuatorsNormalized";

        public Header header { get; set; }
        //  This message defines lowest level commands to be sent
        //  to the actuator(s) for normalized outputs.
        public double[] normalized { get; set; }
        // Normalized between [-1 ... 1].

        public ActuatorsNormalized()
        {
            this.header = new Header();
            this.normalized = new double[0];
        }

        public ActuatorsNormalized(Header header, double[] normalized)
        {
            this.header = header;
            this.normalized = normalized;
        }
    }
}
#endif
