/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Actuator
{
    public class ActuatorsPosition : Message
    {
        public const string RosMessageName = "actuator_msgs/msg/ActuatorsPosition";

        public Header header { get; set; }
        //  This message defines lowest level commands to be sent
        //  to the actuator(s) for position.
        public ActuatorsAngularPosition angular { get; set; }
        // Position of the actuators in [rad]
        public ActuatorsLinearPosition linear { get; set; }
        // Position of the actuators in [m]

        public ActuatorsPosition()
        {
            this.header = new Header();
            this.angular = new ActuatorsAngularPosition();
            this.linear = new ActuatorsLinearPosition();
        }

        public ActuatorsPosition(Header header, ActuatorsAngularPosition angular, ActuatorsLinearPosition linear)
        {
            this.header = header;
            this.angular = angular;
            this.linear = linear;
        }
    }
}
#endif
