/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Actuator
{
    public class ActuatorsLinearPosition : Message
    {
        public const string RosMessageName = "actuator_msgs/msg/ActuatorsLinearPosition";

        //  This message defines lowest level commands to be sent
        //  to the actuator(s) for linear position.
        public double[] position { get; set; }
        // Position of the actuators in [m]

        public ActuatorsLinearPosition()
        {
            this.position = new double[0];
        }

        public ActuatorsLinearPosition(double[] position)
        {
            this.position = position;
        }
    }
}
#endif
