/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Actuator
{
    public class Actuators : Message
    {
        public const string RosMessageName = "actuator_msgs/msg/Actuators";

        public Header header { get; set; }
        //  This message defines lowest level commands to be sent to the actuator(s).
        public double[] position { get; set; }
        // Position of the actuators in [rad] for angular actuators
        //  and [m] for linear actuators.
        public double[] velocity { get; set; }
        // Velocities of the actuators in [rad/s] for angular actuators
        //  and [m/s] for linear actuators.
        public double[] normalized { get; set; }
        // Everything that does not fit the above,
        //  normalized between [-1 ... 1].

        public Actuators()
        {
            this.header = new Header();
            this.position = new double[0];
            this.velocity = new double[0];
            this.normalized = new double[0];
        }

        public Actuators(Header header, double[] position, double[] velocity, double[] normalized)
        {
            this.header = header;
            this.position = position;
            this.velocity = velocity;
            this.normalized = normalized;
        }
    }
}
#endif
