/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Actuator
{
    public class ActuatorsLinearVelocity : Message
    {
        public const string RosMessageName = "actuator_msgs/msg/ActuatorsLinearVelocity";

        //  This message defines lowest level commands to be sent
        //  to the actuator(s) for linear velocity.
        public double[] velocity { get; set; }
        // Velocity of the actuators in [m/s]

        public ActuatorsLinearVelocity()
        {
            this.velocity = new double[0];
        }

        public ActuatorsLinearVelocity(double[] velocity)
        {
            this.velocity = velocity;
        }
    }
}
#endif
