/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.InputInterfaces
{
    public class InputKeyboard : Message
    {
        public const string RosMessageName = "input_interfaces/msg/InputKeyboard";

        //  Keyboard Input Message
        public bool connected { get; set; }
        //  Code of key pressed from esc to capslock
        public uint[] keys_pressed { get; set; }
        public uint[] keys_repeated { get; set; }

        public InputKeyboard()
        {
            this.connected = false;
            this.keys_pressed = new uint[0];
            this.keys_repeated = new uint[0];
        }

        public InputKeyboard(bool connected, uint[] keys_pressed, uint[] keys_repeated)
        {
            this.connected = connected;
            this.keys_pressed = keys_pressed;
            this.keys_repeated = keys_repeated;
        }
    }
}
#endif
