/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.InputInterfaces
{
    public class InputGamepad : Message
    {
        public const string RosMessageName = "input_interfaces/msg/InputGamepad";

        //  Gamepad Input Message
        public bool connected { get; set; }
        //  Button State Data
        //  State input flags show the button frame state where:
        //    0 - Nothing
        //    1 - Down
        //    2 - Held
        //    3 - Up
        public sbyte btn_a_state { get; set; }
        public sbyte btn_b_state { get; set; }
        public sbyte btn_x_state { get; set; }
        public sbyte btn_y_state { get; set; }
        public sbyte btn_shoulder_l_state { get; set; }
        public sbyte btn_shoulder_r_state { get; set; }
        public sbyte btn_back_state { get; set; }
        public sbyte btn_start_state { get; set; }
        public sbyte btn_xbox_state { get; set; }
        public sbyte btn_thumb_l_state { get; set; }
        public sbyte btn_thumb_r_state { get; set; }
        public sbyte btn_dpad_l_state { get; set; }
        public sbyte btn_dpad_r_state { get; set; }
        public sbyte btn_dpad_u_state { get; set; }
        public sbyte btn_dpad_d_state { get; set; }
        //  Axis Data
        //  Each axis data ranges between -1 and 1
        //  By default, no input from an axis will be 0
        public float ax_stick_l_x { get; set; }
        public float ax_stick_l_y { get; set; }
        public float ax_stick_r_x { get; set; }
        public float ax_stick_r_y { get; set; }
        //  DPAD Data
        //  Each DPAD axis can be -1, 0 or 1
        public float ax_dpad_x { get; set; }
        public float ax_dpad_y { get; set; }
        //  Trigger Data
        //  Each trigger ranges between 0 and 1
        public float trg_l_val { get; set; }
        public float trg_r_val { get; set; }
        //  Each trigger also has a state of whether it is pressed
        public bool btn_trigger_l_down { get; set; }
        public bool btn_trigger_r_down { get; set; }

        public InputGamepad()
        {
            this.connected = false;
            this.btn_a_state = 0;
            this.btn_b_state = 0;
            this.btn_x_state = 0;
            this.btn_y_state = 0;
            this.btn_shoulder_l_state = 0;
            this.btn_shoulder_r_state = 0;
            this.btn_back_state = 0;
            this.btn_start_state = 0;
            this.btn_xbox_state = 0;
            this.btn_thumb_l_state = 0;
            this.btn_thumb_r_state = 0;
            this.btn_dpad_l_state = 0;
            this.btn_dpad_r_state = 0;
            this.btn_dpad_u_state = 0;
            this.btn_dpad_d_state = 0;
            this.ax_stick_l_x = 0.0f;
            this.ax_stick_l_y = 0.0f;
            this.ax_stick_r_x = 0.0f;
            this.ax_stick_r_y = 0.0f;
            this.ax_dpad_x = 0.0f;
            this.ax_dpad_y = 0.0f;
            this.trg_l_val = 0.0f;
            this.trg_r_val = 0.0f;
            this.btn_trigger_l_down = false;
            this.btn_trigger_r_down = false;
        }

        public InputGamepad(bool connected, sbyte btn_a_state, sbyte btn_b_state, sbyte btn_x_state, sbyte btn_y_state, sbyte btn_shoulder_l_state, sbyte btn_shoulder_r_state, sbyte btn_back_state, sbyte btn_start_state, sbyte btn_xbox_state, sbyte btn_thumb_l_state, sbyte btn_thumb_r_state, sbyte btn_dpad_l_state, sbyte btn_dpad_r_state, sbyte btn_dpad_u_state, sbyte btn_dpad_d_state, float ax_stick_l_x, float ax_stick_l_y, float ax_stick_r_x, float ax_stick_r_y, float ax_dpad_x, float ax_dpad_y, float trg_l_val, float trg_r_val, bool btn_trigger_l_down, bool btn_trigger_r_down)
        {
            this.connected = connected;
            this.btn_a_state = btn_a_state;
            this.btn_b_state = btn_b_state;
            this.btn_x_state = btn_x_state;
            this.btn_y_state = btn_y_state;
            this.btn_shoulder_l_state = btn_shoulder_l_state;
            this.btn_shoulder_r_state = btn_shoulder_r_state;
            this.btn_back_state = btn_back_state;
            this.btn_start_state = btn_start_state;
            this.btn_xbox_state = btn_xbox_state;
            this.btn_thumb_l_state = btn_thumb_l_state;
            this.btn_thumb_r_state = btn_thumb_r_state;
            this.btn_dpad_l_state = btn_dpad_l_state;
            this.btn_dpad_r_state = btn_dpad_r_state;
            this.btn_dpad_u_state = btn_dpad_u_state;
            this.btn_dpad_d_state = btn_dpad_d_state;
            this.ax_stick_l_x = ax_stick_l_x;
            this.ax_stick_l_y = ax_stick_l_y;
            this.ax_stick_r_x = ax_stick_r_x;
            this.ax_stick_r_y = ax_stick_r_y;
            this.ax_dpad_x = ax_dpad_x;
            this.ax_dpad_y = ax_dpad_y;
            this.trg_l_val = trg_l_val;
            this.trg_r_val = trg_r_val;
            this.btn_trigger_l_down = btn_trigger_l_down;
            this.btn_trigger_r_down = btn_trigger_r_down;
        }
    }
}
#endif
