/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.TheoraImageTransport
{
    public class Packet : Message
    {
        public const string RosMessageName = "theora_image_transport/msg/Packet";

        //  ROS message adaptation of the ogg_packet struct from libogg,
        //  see http://www.xiph.org/ogg/doc/libogg/ogg_packet.html.
        public Header header { get; set; }
        // Original sensor_msgs/Image header
        public byte[] data { get; set; }
        // Raw Theora packet data (combines packet and bytes fields from ogg_packet)
        public int b_o_s { get; set; }
        // Flag indicating whether this packet begins a logical bitstream
        public int e_o_s { get; set; }
        // Flag indicating whether this packet ends a bitstream
        public long granulepos { get; set; }
        // A number indicating the position of this packet in the decoded data
        public long packetno { get; set; }
        // Sequential number of this packet in the ogg bitstream

        public Packet()
        {
            this.header = new Header();
            this.data = new byte[0];
            this.b_o_s = 0;
            this.e_o_s = 0;
            this.granulepos = 0;
            this.packetno = 0;
        }

        public Packet(Header header, byte[] data, int b_o_s, int e_o_s, long granulepos, long packetno)
        {
            this.header = header;
            this.data = data;
            this.b_o_s = b_o_s;
            this.e_o_s = e_o_s;
            this.granulepos = granulepos;
            this.packetno = packetno;
        }
    }
}
#endif
