/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.DepthaiRos
{
    public class AutoFocusCtrl : Message
    {
        public const string RosMessageName = "depthai_ros_msgs/msg/AutoFocusCtrl";

        public const byte AF_MODE_AUTO = 0;
        public const byte AF_MODE_MACRO = 1;
        public const byte AF_MODE_CONTINUOUS_VIDEO = 2;
        public const byte AF_MODE_CONTINUOUS_PICTURE = 3;
        public const byte AF_MODE_EDOF = 4;
        public byte auto_focus_mode { get; set; }
        public bool trigger_auto_focus { get; set; }

        public AutoFocusCtrl()
        {
            this.auto_focus_mode = 0;
            this.trigger_auto_focus = false;
        }

        public AutoFocusCtrl(byte auto_focus_mode, bool trigger_auto_focus)
        {
            this.auto_focus_mode = auto_focus_mode;
            this.trigger_auto_focus = trigger_auto_focus;
        }
    }
}
#endif
