/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.DepthaiRos
{
    public class HandLandmark : Message
    {
        public const string RosMessageName = "depthai_ros_msgs/msg/HandLandmark";

        //  Center of the
        public string label { get; set; }
        //  Landmarks score.
        public float lm_score { get; set; }
        public Pose2D[] landmark { get; set; }
        public Point position { get; set; }
        public bool is_spatial { get; set; }

        public HandLandmark()
        {
            this.label = "";
            this.lm_score = 0.0f;
            this.landmark = new Pose2D[0];
            this.position = new Point();
            this.is_spatial = false;
        }

        public HandLandmark(string label, float lm_score, Pose2D[] landmark, Point position, bool is_spatial)
        {
            this.label = label;
            this.lm_score = lm_score;
            this.landmark = landmark;
            this.position = position;
            this.is_spatial = is_spatial;
        }
    }
}
#endif
