/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.DepthaiRos
{
    public class HandLandmarkArray : Message
    {
        public const string RosMessageName = "depthai_ros_msgs/msg/HandLandmarkArray";

        //  A list of hand landmark detections
        public Header header { get; set; }
        //  A list of the detected proposals. A multi-proposal detector might generate along with the 3D depth information
        //    this list with many candidate detections generated from a single input.
        public HandLandmark[] landmarks { get; set; }

        public HandLandmarkArray()
        {
            this.header = new Header();
            this.landmarks = new HandLandmark[0];
        }

        public HandLandmarkArray(Header header, HandLandmark[] landmarks)
        {
            this.header = header;
            this.landmarks = landmarks;
        }
    }
}
#endif
