/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Sensor;

namespace RosSharp.RosBridgeClient.MessageTypes.DepthaiRos
{
    public class ImuWithMagneticField : Message
    {
        public const string RosMessageName = "depthai_ros_msgs/msg/ImuWithMagneticField";

        public Header header { get; set; }
        public Imu imu { get; set; }
        public MagneticField @field { get; set; }

        public ImuWithMagneticField()
        {
            this.header = new Header();
            this.imu = new Imu();
            this.@field = new MagneticField();
        }

        public ImuWithMagneticField(Header header, Imu imu, MagneticField @field)
        {
            this.header = header;
            this.imu = imu;
            this.@field = @field;
        }
    }
}
#endif
