/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.DepthaiRos
{
    public class SpatialDetectionArray : Message
    {
        public const string RosMessageName = "depthai_ros_msgs/msg/SpatialDetectionArray";

        //  A list of 2D detections, for a multi-object 2D detector along with 3D depth information.
        public Header header { get; set; }
        //  A list of the detected proposals. A multi-proposal detector might generate along with the 3D depth information
        //    this list with many candidate detections generated from a single input.
        public SpatialDetection[] detections { get; set; }
        // # These messages are created as close as possible to the official vision_msgs(http://wiki.ros.org/vision_msgs)

        public SpatialDetectionArray()
        {
            this.header = new Header();
            this.detections = new SpatialDetection[0];
        }

        public SpatialDetectionArray(Header header, SpatialDetection[] detections)
        {
            this.header = header;
            this.detections = detections;
        }
    }
}
#endif
