/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Vision;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.DepthaiRos
{
    public class SpatialDetection : Message
    {
        public const string RosMessageName = "depthai_ros_msgs/msg/SpatialDetection";

        //  Class probabilities
        public ObjectHypothesis[] results { get; set; }
        //  2D bounding box surrounding the object.
        public BoundingBox2D bbox { get; set; }
        //  Center of the detected object in meters
        public Point position { get; set; }
        //  If true, this message contains object tracking information.
        public bool is_tracking { get; set; }
        //  ID used for consistency across multiple detection messages. This value will
        //  likely differ from the id field set in each individual ObjectHypothesis.
        //  If you set this field, be sure to also set is_tracking to True.
        public string tracking_id { get; set; }

        public SpatialDetection()
        {
            this.results = new ObjectHypothesis[0];
            this.bbox = new BoundingBox2D();
            this.position = new Point();
            this.is_tracking = false;
            this.tracking_id = "";
        }

        public SpatialDetection(ObjectHypothesis[] results, BoundingBox2D bbox, Point position, bool is_tracking, string tracking_id)
        {
            this.results = results;
            this.bbox = bbox;
            this.position = position;
            this.is_tracking = is_tracking;
            this.tracking_id = tracking_id;
        }
    }
}
#endif
