/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.DepthaiRos
{
    public class TrackedFeature : Message
    {
        public const string RosMessageName = "depthai_ros_msgs/msg/TrackedFeature";

        public Header header { get; set; }
        public Point position { get; set; }
        public uint id { get; set; }
        public uint age { get; set; }
        public float harris_score { get; set; }
        public float tracking_error { get; set; }

        public TrackedFeature()
        {
            this.header = new Header();
            this.position = new Point();
            this.id = 0;
            this.age = 0;
            this.harris_score = 0.0f;
            this.tracking_error = 0.0f;
        }

        public TrackedFeature(Header header, Point position, uint id, uint age, float harris_score, float tracking_error)
        {
            this.header = header;
            this.position = position;
            this.id = id;
            this.age = age;
            this.harris_score = harris_score;
            this.tracking_error = tracking_error;
        }
    }
}
#endif
