/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.DepthaiRos;

namespace RosSharp.RosBridgeClient.MessageTypes.DepthaiRos
{
    public class TrackedFeatures : Message
    {
        public const string RosMessageName = "depthai_ros_msgs/msg/TrackedFeatures";

        public Header header { get; set; }
        public TrackedFeature[] features { get; set; }

        public TrackedFeatures()
        {
            this.header = new Header();
            this.features = new TrackedFeature[0];
        }

        public TrackedFeatures(Header header, TrackedFeature[] features)
        {
            this.header = header;
            this.features = features;
        }
    }
}
#endif
