/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Dwb
{
    public class LocalPlanEvaluation : Message
    {
        public const string RosMessageName = "dwb_msgs/msg/LocalPlanEvaluation";

        //  Full Scoring for running the local planner
        //  Header, used for timestamp
        public Header header { get; set; }
        //  All the trajectories evaluated and their scores
        public TrajectoryScore[] twists { get; set; }
        //  Convenience index of the best (lowest) score in the twists array
        public ushort best_index { get; set; }
        //  Convenience index of the worst (highest) score in the twists array. Useful for scaling.
        public ushort worst_index { get; set; }

        public LocalPlanEvaluation()
        {
            this.header = new Header();
            this.twists = new TrajectoryScore[0];
            this.best_index = 0;
            this.worst_index = 0;
        }

        public LocalPlanEvaluation(Header header, TrajectoryScore[] twists, ushort best_index, ushort worst_index)
        {
            this.header = header;
            this.twists = twists;
            this.best_index = best_index;
            this.worst_index = worst_index;
        }
    }
}
#endif
