/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Nav2d;
using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Dwb
{
    public class Trajectory2D : Message
    {
        public const string RosMessageName = "dwb_msgs/msg/Trajectory2D";

        //  For a given velocity command, the poses that the robot will go to in the allotted time.
        //  Input Velocity
        public Twist2D velocity { get; set; }
        //  Time difference between first and last poses
        public Duration[] time_offsets { get; set; }
        //  Poses the robot will go to, given our kinematic model
        public Pose2D[] poses { get; set; }

        public Trajectory2D()
        {
            this.velocity = new Twist2D();
            this.time_offsets = new Duration[0];
            this.poses = new Pose2D[0];
        }

        public Trajectory2D(Twist2D velocity, Duration[] time_offsets, Pose2D[] poses)
        {
            this.velocity = velocity;
            this.time_offsets = time_offsets;
            this.poses = poses;
        }
    }
}
#endif
