/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class DynamicInterfaceValues : Message
    {
        public const string RosMessageName = "control_msgs/msg/DynamicInterfaceValues";

        public Header header { get; set; }
        public InterfaceValue states { get; set; }
        public InterfaceValue commands { get; set; }

        public DynamicInterfaceValues()
        {
            this.header = new Header();
            this.states = new InterfaceValue();
            this.commands = new InterfaceValue();
        }

        public DynamicInterfaceValues(Header header, InterfaceValue states, InterfaceValue commands)
        {
            this.header = header;
            this.states = states;
            this.commands = commands;
        }
    }
}
#endif
